services:
  smart-parking:
    build:
      context: .
      dockerfile: Dockerfile
    image: smart-parking:latest
    container_name: smart-parking
    init: true
    volumes:
      - ./dataset:/data/dataset:ro
      - ./output:/output
      - /tools/Xilinx:/tools/Xilinx:ro
    stdin_open: true
    tty: true
