// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv3_conv3_Pipeline_LOAD_IC_LOAD_IY (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_AXI_IN_0_AWVALID,
        m_axi_AXI_IN_0_AWREADY,
        m_axi_AXI_IN_0_AWADDR,
        m_axi_AXI_IN_0_AWID,
        m_axi_AXI_IN_0_AWLEN,
        m_axi_AXI_IN_0_AWSIZE,
        m_axi_AXI_IN_0_AWBURST,
        m_axi_AXI_IN_0_AWLOCK,
        m_axi_AXI_IN_0_AWCACHE,
        m_axi_AXI_IN_0_AWPROT,
        m_axi_AXI_IN_0_AWQOS,
        m_axi_AXI_IN_0_AWREGION,
        m_axi_AXI_IN_0_AWUSER,
        m_axi_AXI_IN_0_WVALID,
        m_axi_AXI_IN_0_WREADY,
        m_axi_AXI_IN_0_WDATA,
        m_axi_AXI_IN_0_WSTRB,
        m_axi_AXI_IN_0_WLAST,
        m_axi_AXI_IN_0_WID,
        m_axi_AXI_IN_0_WUSER,
        m_axi_AXI_IN_0_ARVALID,
        m_axi_AXI_IN_0_ARREADY,
        m_axi_AXI_IN_0_ARADDR,
        m_axi_AXI_IN_0_ARID,
        m_axi_AXI_IN_0_ARLEN,
        m_axi_AXI_IN_0_ARSIZE,
        m_axi_AXI_IN_0_ARBURST,
        m_axi_AXI_IN_0_ARLOCK,
        m_axi_AXI_IN_0_ARCACHE,
        m_axi_AXI_IN_0_ARPROT,
        m_axi_AXI_IN_0_ARQOS,
        m_axi_AXI_IN_0_ARREGION,
        m_axi_AXI_IN_0_ARUSER,
        m_axi_AXI_IN_0_RVALID,
        m_axi_AXI_IN_0_RREADY,
        m_axi_AXI_IN_0_RDATA,
        m_axi_AXI_IN_0_RLAST,
        m_axi_AXI_IN_0_RID,
        m_axi_AXI_IN_0_RFIFONUM,
        m_axi_AXI_IN_0_RUSER,
        m_axi_AXI_IN_0_RRESP,
        m_axi_AXI_IN_0_BVALID,
        m_axi_AXI_IN_0_BREADY,
        m_axi_AXI_IN_0_BRESP,
        m_axi_AXI_IN_0_BID,
        m_axi_AXI_IN_0_BUSER,
        sext_ln28,
        in_buf_address0,
        in_buf_ce0,
        in_buf_we0,
        in_buf_d0,
        in_buf_1_address0,
        in_buf_1_ce0,
        in_buf_1_we0,
        in_buf_1_d0,
        in_buf_2_address0,
        in_buf_2_ce0,
        in_buf_2_we0,
        in_buf_2_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_AXI_IN_0_AWVALID;
input   m_axi_AXI_IN_0_AWREADY;
output  [63:0] m_axi_AXI_IN_0_AWADDR;
output  [0:0] m_axi_AXI_IN_0_AWID;
output  [31:0] m_axi_AXI_IN_0_AWLEN;
output  [2:0] m_axi_AXI_IN_0_AWSIZE;
output  [1:0] m_axi_AXI_IN_0_AWBURST;
output  [1:0] m_axi_AXI_IN_0_AWLOCK;
output  [3:0] m_axi_AXI_IN_0_AWCACHE;
output  [2:0] m_axi_AXI_IN_0_AWPROT;
output  [3:0] m_axi_AXI_IN_0_AWQOS;
output  [3:0] m_axi_AXI_IN_0_AWREGION;
output  [0:0] m_axi_AXI_IN_0_AWUSER;
output   m_axi_AXI_IN_0_WVALID;
input   m_axi_AXI_IN_0_WREADY;
output  [63:0] m_axi_AXI_IN_0_WDATA;
output  [7:0] m_axi_AXI_IN_0_WSTRB;
output   m_axi_AXI_IN_0_WLAST;
output  [0:0] m_axi_AXI_IN_0_WID;
output  [0:0] m_axi_AXI_IN_0_WUSER;
output   m_axi_AXI_IN_0_ARVALID;
input   m_axi_AXI_IN_0_ARREADY;
output  [63:0] m_axi_AXI_IN_0_ARADDR;
output  [0:0] m_axi_AXI_IN_0_ARID;
output  [31:0] m_axi_AXI_IN_0_ARLEN;
output  [2:0] m_axi_AXI_IN_0_ARSIZE;
output  [1:0] m_axi_AXI_IN_0_ARBURST;
output  [1:0] m_axi_AXI_IN_0_ARLOCK;
output  [3:0] m_axi_AXI_IN_0_ARCACHE;
output  [2:0] m_axi_AXI_IN_0_ARPROT;
output  [3:0] m_axi_AXI_IN_0_ARQOS;
output  [3:0] m_axi_AXI_IN_0_ARREGION;
output  [0:0] m_axi_AXI_IN_0_ARUSER;
input   m_axi_AXI_IN_0_RVALID;
output   m_axi_AXI_IN_0_RREADY;
input  [63:0] m_axi_AXI_IN_0_RDATA;
input   m_axi_AXI_IN_0_RLAST;
input  [0:0] m_axi_AXI_IN_0_RID;
input  [8:0] m_axi_AXI_IN_0_RFIFONUM;
input  [0:0] m_axi_AXI_IN_0_RUSER;
input  [1:0] m_axi_AXI_IN_0_RRESP;
input   m_axi_AXI_IN_0_BVALID;
output   m_axi_AXI_IN_0_BREADY;
input  [1:0] m_axi_AXI_IN_0_BRESP;
input  [0:0] m_axi_AXI_IN_0_BID;
input  [0:0] m_axi_AXI_IN_0_BUSER;
input  [60:0] sext_ln28;
output  [10:0] in_buf_address0;
output   in_buf_ce0;
output   in_buf_we0;
output  [31:0] in_buf_d0;
output  [10:0] in_buf_1_address0;
output   in_buf_1_ce0;
output   in_buf_1_we0;
output  [31:0] in_buf_1_d0;
output  [10:0] in_buf_2_address0;
output   in_buf_2_ce0;
output   in_buf_2_we0;
output  [31:0] in_buf_2_d0;

reg ap_idle;
reg m_axi_AXI_IN_0_RREADY;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln28_reg_494;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage4;
reg    ap_block_state5_pp0_stage4_iter0_grp4;
reg    ap_block_pp0_stage4_subdone;
reg    AXI_IN_blk_n_R;
wire    ap_block_pp0_stage1_grp1;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_grp3;
wire    ap_block_pp0_stage4_grp4;
wire    ap_block_pp0_stage0_grp5;
reg   [31:0] reg_218;
reg    ap_block_pp0_stage1_11001_grp1;
reg    ap_block_state3_pp0_stage2_iter0_grp2;
reg    ap_block_pp0_stage2_11001_grp2;
reg    ap_block_state4_pp0_stage3_iter0_grp3;
reg    ap_block_pp0_stage3_11001_grp3;
reg    ap_block_pp0_stage4_11001_grp4;
reg    ap_block_pp0_stage0_11001_grp5;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln28_fu_244_p2;
reg    ap_block_pp0_stage0_11001;
wire   [8:0] add_ln34_1_fu_331_p2;
reg   [8:0] add_ln34_1_reg_503;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
wire   [31:0] trunc_ln34_fu_337_p1;
reg   [31:0] trunc_ln34_reg_511;
wire   [63:0] zext_ln34_2_fu_364_p1;
reg   [63:0] zext_ln34_2_reg_516;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
reg    ap_block_pp0_stage2_subdone;
wire   [31:0] trunc_ln34_2_fu_379_p1;
reg   [31:0] trunc_ln34_2_reg_521;
wire   [63:0] zext_ln34_3_fu_390_p1;
reg   [63:0] zext_ln34_3_reg_526;
wire    ap_block_pp0_stage3_11001_grp0;
reg    ap_block_pp0_stage3_subdone_grp0_done_reg;
wire    ap_block_pp0_stage3_subdone_grp0;
reg    ap_block_pp0_stage3_subdone;
wire   [31:0] trunc_ln34_4_fu_404_p1;
reg   [31:0] trunc_ln34_4_reg_532;
wire   [31:0] trunc_ln34_6_fu_417_p1;
reg   [31:0] trunc_ln34_6_reg_537;
wire   [63:0] zext_ln34_4_fu_428_p1;
reg   [63:0] zext_ln34_4_reg_542;
wire   [31:0] trunc_ln34_8_fu_443_p1;
reg   [31:0] trunc_ln34_8_reg_547;
wire    ap_block_pp0_stage2_grp0;
wire    ap_block_pp0_stage3_grp0;
wire    ap_block_pp0_stage4_grp0;
wire    ap_block_pp0_stage0_grp0;
wire   [63:0] zext_ln34_5_fu_454_p1;
wire    ap_block_pp0_stage1_grp0;
reg   [3:0] iy_fu_90;
wire   [3:0] add_ln30_fu_341_p2;
wire    ap_loop_init;
reg   [5:0] ic_fu_94;
wire   [5:0] select_ln28_1_fu_293_p3;
reg   [8:0] indvar_flatten_fu_98;
wire   [8:0] add_ln28_1_fu_250_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg    in_buf_we0_local;
reg   [31:0] in_buf_d0_local;
wire   [31:0] bitcast_ln34_fu_370_p1;
reg    in_buf_ce0_local;
reg   [10:0] in_buf_address0_local;
wire   [31:0] bitcast_ln34_3_fu_399_p1;
wire   [31:0] bitcast_ln34_6_fu_434_p1;
wire   [31:0] bitcast_ln34_9_fu_463_p1;
reg    in_buf_1_we0_local;
reg   [31:0] in_buf_1_d0_local;
wire   [31:0] bitcast_ln34_1_fu_374_p1;
reg    in_buf_1_ce0_local;
reg   [10:0] in_buf_1_address0_local;
wire    ap_block_pp0_stage4_11001_grp0;
reg    ap_block_pp0_stage4_subdone_grp0_done_reg;
wire    ap_block_pp0_stage4_subdone_grp0;
wire   [31:0] bitcast_ln34_4_fu_408_p1;
wire   [31:0] bitcast_ln34_7_fu_438_p1;
reg    in_buf_2_we0_local;
reg   [31:0] in_buf_2_d0_local;
wire   [31:0] bitcast_ln34_2_fu_395_p1;
reg    in_buf_2_ce0_local;
reg   [10:0] in_buf_2_address0_local;
wire   [31:0] bitcast_ln34_5_fu_412_p1;
wire   [31:0] bitcast_ln34_8_fu_459_p1;
wire   [0:0] icmp_ln30_fu_279_p2;
wire   [5:0] add_ln28_fu_273_p2;
wire   [6:0] tmp_1_fu_309_p3;
wire   [8:0] tmp_fu_301_p3;
wire   [8:0] zext_ln34_fu_317_p1;
wire   [3:0] select_ln28_fu_285_p3;
wire   [8:0] add_ln34_fu_321_p2;
wire   [8:0] zext_ln34_1_fu_327_p1;
wire   [10:0] tmp_2_fu_357_p3;
wire   [10:0] tmp_5_fu_383_p3;
wire   [10:0] tmp_6_fu_421_p3;
wire   [10:0] tmp_7_fu_447_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp0_done_reg = 1'b0;
#0 iy_fu_90 = 4'd0;
#0 ic_fu_94 = 6'd0;
#0 indvar_flatten_fu_98 = 9'd0;
#0 ap_block_pp0_stage4_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp0)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage4_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage4)) begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_block_pp0_stage4_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage4_subdone_grp0)) begin
                ap_block_pp0_stage4_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        ic_fu_94 <= 6'd0;
    end else if (((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ic_fu_94 <= select_ln28_1_fu_293_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_fu_244_p2 == 1'd0))) begin
            indvar_flatten_fu_98 <= add_ln28_1_fu_250_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_98 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        iy_fu_90 <= 4'd0;
    end else if (((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        iy_fu_90 <= add_ln30_fu_341_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        add_ln34_1_reg_503 <= add_ln34_1_fu_331_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln28_reg_494 <= icmp_ln28_fu_244_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp5)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)))) begin
        reg_218 <= {{m_axi_AXI_IN_0_RDATA[63:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp2))) begin
        trunc_ln34_2_reg_521 <= trunc_ln34_2_fu_379_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp3))) begin
        trunc_ln34_4_reg_532 <= trunc_ln34_4_fu_404_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001_grp4))) begin
        trunc_ln34_6_reg_537 <= trunc_ln34_6_fu_417_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp5))) begin
        trunc_ln34_8_reg_547 <= trunc_ln34_8_fu_443_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp1))) begin
        trunc_ln34_reg_511 <= trunc_ln34_fu_337_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        zext_ln34_2_reg_516[10 : 2] <= zext_ln34_2_fu_364_p1[10 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
        zext_ln34_3_reg_526[10 : 2] <= zext_ln34_3_fu_390_p1[10 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        zext_ln34_4_reg_542[10 : 2] <= zext_ln34_4_fu_428_p1[10 : 2];
    end
end

always @ (*) begin
    if ((((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp5)))) begin
        AXI_IN_blk_n_R = m_axi_AXI_IN_0_RVALID;
    end else begin
        AXI_IN_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln28_reg_494 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_98;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp0))) begin
        in_buf_1_address0_local = zext_ln34_4_fu_428_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_1_address0_local = zext_ln34_3_reg_526;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_1_address0_local = zext_ln34_2_fu_364_p1;
    end else begin
        in_buf_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)))) begin
        in_buf_1_ce0_local = 1'b1;
    end else begin
        in_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp0))) begin
        in_buf_1_d0_local = bitcast_ln34_7_fu_438_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_1_d0_local = bitcast_ln34_4_fu_408_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_1_d0_local = bitcast_ln34_1_fu_374_p1;
    end else begin
        in_buf_1_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        in_buf_1_we0_local = 1'b1;
    end else begin
        in_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
        in_buf_2_address0_local = zext_ln34_4_reg_542;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_2_address0_local = zext_ln34_3_reg_526;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_2_address0_local = zext_ln34_2_reg_516;
    end else begin
        in_buf_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)))) begin
        in_buf_2_ce0_local = 1'b1;
    end else begin
        in_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
        in_buf_2_d0_local = bitcast_ln34_8_fu_459_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_2_d0_local = bitcast_ln34_5_fu_412_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_2_d0_local = bitcast_ln34_2_fu_395_p1;
    end else begin
        in_buf_2_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)))) begin
        in_buf_2_we0_local = 1'b1;
    end else begin
        in_buf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
        in_buf_address0_local = zext_ln34_5_fu_454_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp0))) begin
        in_buf_address0_local = zext_ln34_4_fu_428_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_address0_local = zext_ln34_3_fu_390_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_address0_local = zext_ln34_2_fu_364_p1;
    end else begin
        in_buf_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)))) begin
        in_buf_ce0_local = 1'b1;
    end else begin
        in_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
        in_buf_d0_local = bitcast_ln34_9_fu_463_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp0))) begin
        in_buf_d0_local = bitcast_ln34_6_fu_434_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_d0_local = bitcast_ln34_3_fu_399_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        in_buf_d0_local = bitcast_ln34_fu_370_p1;
    end else begin
        in_buf_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        in_buf_we0_local = 1'b1;
    end else begin
        in_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln28_reg_494 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp5)))) begin
        m_axi_AXI_IN_0_RREADY = 1'b1;
    end else begin
        m_axi_AXI_IN_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln28_1_fu_250_p2 = (ap_sig_allocacmp_indvar_flatten_load + 9'd1);

assign add_ln28_fu_273_p2 = (ic_fu_94 + 6'd1);

assign add_ln30_fu_341_p2 = (select_ln28_fu_285_p3 + 4'd1);

assign add_ln34_1_fu_331_p2 = (add_ln34_fu_321_p2 + zext_ln34_1_fu_327_p1);

assign add_ln34_fu_321_p2 = (tmp_fu_301_p3 + zext_ln34_fu_317_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_AXI_IN_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp5 = ((m_axi_AXI_IN_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_AXI_IN_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((1'b1 == ap_block_state2_pp0_stage1_iter0_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((1'b1 == ap_block_state2_pp0_stage1_iter0_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((1'b1 == ap_block_state3_pp0_stage2_iter0_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((1'b1 == ap_block_state3_pp0_stage2_iter0_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001_grp3 = ((1'b1 == ap_block_state4_pp0_stage3_iter0_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage3_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((1'b1 == ap_block_state4_pp0_stage3_iter0_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage3_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001_grp4 = ((1'b1 == ap_block_state5_pp0_stage4_iter0_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage4_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((1'b1 == ap_block_state5_pp0_stage4_iter0_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage4_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = ((icmp_ln28_reg_494 == 1'd0) & (m_axi_AXI_IN_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0_grp2 = ((icmp_ln28_reg_494 == 1'd0) & (m_axi_AXI_IN_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0_grp3 = ((icmp_ln28_reg_494 == 1'd0) & (m_axi_AXI_IN_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0_grp4 = ((icmp_ln28_reg_494 == 1'd0) & (m_axi_AXI_IN_0_RVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign bitcast_ln34_1_fu_374_p1 = reg_218;

assign bitcast_ln34_2_fu_395_p1 = trunc_ln34_2_reg_521;

assign bitcast_ln34_3_fu_399_p1 = reg_218;

assign bitcast_ln34_4_fu_408_p1 = trunc_ln34_4_reg_532;

assign bitcast_ln34_5_fu_412_p1 = reg_218;

assign bitcast_ln34_6_fu_434_p1 = trunc_ln34_6_reg_537;

assign bitcast_ln34_7_fu_438_p1 = reg_218;

assign bitcast_ln34_8_fu_459_p1 = trunc_ln34_8_reg_547;

assign bitcast_ln34_9_fu_463_p1 = reg_218;

assign bitcast_ln34_fu_370_p1 = trunc_ln34_reg_511;

assign icmp_ln28_fu_244_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 9'd320) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_279_p2 = ((iy_fu_90 == 4'd10) ? 1'b1 : 1'b0);

assign in_buf_1_address0 = in_buf_1_address0_local;

assign in_buf_1_ce0 = in_buf_1_ce0_local;

assign in_buf_1_d0 = in_buf_1_d0_local;

assign in_buf_1_we0 = in_buf_1_we0_local;

assign in_buf_2_address0 = in_buf_2_address0_local;

assign in_buf_2_ce0 = in_buf_2_ce0_local;

assign in_buf_2_d0 = in_buf_2_d0_local;

assign in_buf_2_we0 = in_buf_2_we0_local;

assign in_buf_address0 = in_buf_address0_local;

assign in_buf_ce0 = in_buf_ce0_local;

assign in_buf_d0 = in_buf_d0_local;

assign in_buf_we0 = in_buf_we0_local;

assign m_axi_AXI_IN_0_ARADDR = 64'd0;

assign m_axi_AXI_IN_0_ARBURST = 2'd0;

assign m_axi_AXI_IN_0_ARCACHE = 4'd0;

assign m_axi_AXI_IN_0_ARID = 1'd0;

assign m_axi_AXI_IN_0_ARLEN = 32'd0;

assign m_axi_AXI_IN_0_ARLOCK = 2'd0;

assign m_axi_AXI_IN_0_ARPROT = 3'd0;

assign m_axi_AXI_IN_0_ARQOS = 4'd0;

assign m_axi_AXI_IN_0_ARREGION = 4'd0;

assign m_axi_AXI_IN_0_ARSIZE = 3'd0;

assign m_axi_AXI_IN_0_ARUSER = 1'd0;

assign m_axi_AXI_IN_0_ARVALID = 1'b0;

assign m_axi_AXI_IN_0_AWADDR = 64'd0;

assign m_axi_AXI_IN_0_AWBURST = 2'd0;

assign m_axi_AXI_IN_0_AWCACHE = 4'd0;

assign m_axi_AXI_IN_0_AWID = 1'd0;

assign m_axi_AXI_IN_0_AWLEN = 32'd0;

assign m_axi_AXI_IN_0_AWLOCK = 2'd0;

assign m_axi_AXI_IN_0_AWPROT = 3'd0;

assign m_axi_AXI_IN_0_AWQOS = 4'd0;

assign m_axi_AXI_IN_0_AWREGION = 4'd0;

assign m_axi_AXI_IN_0_AWSIZE = 3'd0;

assign m_axi_AXI_IN_0_AWUSER = 1'd0;

assign m_axi_AXI_IN_0_AWVALID = 1'b0;

assign m_axi_AXI_IN_0_BREADY = 1'b0;

assign m_axi_AXI_IN_0_WDATA = 64'd0;

assign m_axi_AXI_IN_0_WID = 1'd0;

assign m_axi_AXI_IN_0_WLAST = 1'b0;

assign m_axi_AXI_IN_0_WSTRB = 8'd0;

assign m_axi_AXI_IN_0_WUSER = 1'd0;

assign m_axi_AXI_IN_0_WVALID = 1'b0;

assign select_ln28_1_fu_293_p3 = ((icmp_ln30_fu_279_p2[0:0] == 1'b1) ? add_ln28_fu_273_p2 : ic_fu_94);

assign select_ln28_fu_285_p3 = ((icmp_ln30_fu_279_p2[0:0] == 1'b1) ? 4'd0 : iy_fu_90);

assign tmp_1_fu_309_p3 = {{select_ln28_1_fu_293_p3}, {1'd0}};

assign tmp_2_fu_357_p3 = {{add_ln34_1_reg_503}, {2'd0}};

assign tmp_5_fu_383_p3 = {{add_ln34_1_reg_503}, {2'd1}};

assign tmp_6_fu_421_p3 = {{add_ln34_1_reg_503}, {2'd2}};

assign tmp_7_fu_447_p3 = {{add_ln34_1_reg_503}, {2'd3}};

assign tmp_fu_301_p3 = {{select_ln28_1_fu_293_p3}, {3'd0}};

assign trunc_ln34_2_fu_379_p1 = m_axi_AXI_IN_0_RDATA[31:0];

assign trunc_ln34_4_fu_404_p1 = m_axi_AXI_IN_0_RDATA[31:0];

assign trunc_ln34_6_fu_417_p1 = m_axi_AXI_IN_0_RDATA[31:0];

assign trunc_ln34_8_fu_443_p1 = m_axi_AXI_IN_0_RDATA[31:0];

assign trunc_ln34_fu_337_p1 = m_axi_AXI_IN_0_RDATA[31:0];

assign zext_ln34_1_fu_327_p1 = select_ln28_fu_285_p3;

assign zext_ln34_2_fu_364_p1 = tmp_2_fu_357_p3;

assign zext_ln34_3_fu_390_p1 = tmp_5_fu_383_p3;

assign zext_ln34_4_fu_428_p1 = tmp_6_fu_421_p3;

assign zext_ln34_5_fu_454_p1 = tmp_7_fu_447_p3;

assign zext_ln34_fu_317_p1 = tmp_1_fu_309_p3;

always @ (posedge ap_clk) begin
    zext_ln34_2_reg_516[1:0] <= 2'b00;
    zext_ln34_2_reg_516[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln34_3_reg_526[1:0] <= 2'b01;
    zext_ln34_3_reg_526[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln34_4_reg_542[1:0] <= 2'b10;
    zext_ln34_4_reg_542[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //conv3_conv3_Pipeline_LOAD_IC_LOAD_IY
