-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2_pool2_conv2_pool2_Pipeline_POOL_PY_POOL_PX is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_AWVALID : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_AWREADY : IN STD_LOGIC;
    m_axi_AXI_OUT_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_OUT_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AXI_OUT_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_OUT_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_OUT_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_WVALID : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_WREADY : IN STD_LOGIC;
    m_axi_AXI_OUT_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_OUT_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_AXI_OUT_0_WLAST : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_ARVALID : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_ARREADY : IN STD_LOGIC;
    m_axi_AXI_OUT_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_OUT_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AXI_OUT_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_OUT_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_OUT_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_RVALID : IN STD_LOGIC;
    m_axi_AXI_OUT_0_RREADY : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_OUT_0_RLAST : IN STD_LOGIC;
    m_axi_AXI_OUT_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_AXI_OUT_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_BVALID : IN STD_LOGIC;
    m_axi_AXI_OUT_0_BREADY : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln42 : IN STD_LOGIC_VECTOR (60 downto 0);
    conv_buf_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    conv_buf_ce0 : OUT STD_LOGIC;
    conv_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_buf_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    conv_buf_ce1 : OUT STD_LOGIC;
    conv_buf_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_buf_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    conv_buf_1_ce0 : OUT STD_LOGIC;
    conv_buf_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_buf_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    conv_buf_1_ce1 : OUT STD_LOGIC;
    conv_buf_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_322_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_322_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_322_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_322_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_322_p_ce : OUT STD_LOGIC );
end;


architecture behav of conv2_pool2_conv2_pool2_Pipeline_POOL_PY_POOL_PX is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_64 : STD_LOGIC_VECTOR (6 downto 0) := "1100100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv8_B : STD_LOGIC_VECTOR (7 downto 0) := "00001011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal trunc_ln66_reg_682 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_reg_682_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state14_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln64_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal AXI_OUT_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln66_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_662 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_662_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_662_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_662_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_662_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_662_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_662_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_662_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_662_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_662_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_662_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln64_fu_234_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln64_reg_667 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln64_reg_667_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln66_fu_274_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_reg_682_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_reg_682_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_reg_682_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_reg_682_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_reg_682_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_reg_682_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_reg_682_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_reg_682_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_reg_682_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_reg_682_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln69_fu_294_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_617_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln71_reg_698 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln71_reg_698_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal v00_reg_708 : STD_LOGIC_VECTOR (31 downto 0);
    signal v00_reg_708_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v01_reg_715 : STD_LOGIC_VECTOR (31 downto 0);
    signal v01_reg_715_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln71_fu_302_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln71_reg_722 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln71_reg_722_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal v10_reg_732 : STD_LOGIC_VECTOR (31 downto 0);
    signal v10_reg_732_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal maxv_2_fu_388_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal maxv_2_reg_739 : STD_LOGIC_VECTOR (31 downto 0);
    signal maxv_2_reg_739_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v11_reg_751 : STD_LOGIC_VECTOR (31 downto 0);
    signal v11_reg_751_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal maxv_4_fu_476_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal maxv_4_reg_758 : STD_LOGIC_VECTOR (31 downto 0);
    signal maxv_4_reg_758_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal maxv_6_fu_564_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal maxv_6_reg_765 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln64_1_fu_573_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln64_1_reg_770 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln77_fu_580_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln77_reg_775 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln69_1_fu_297_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal phi_ln77_fu_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln66_fu_583_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal px_fu_84 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln66_fu_278_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal py_fu_88 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln64_2_fu_242_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten90_fu_92 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln64_1_fu_205_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten90_load : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal conv_buf_ce1_local : STD_LOGIC;
    signal conv_buf_ce0_local : STD_LOGIC;
    signal conv_buf_1_ce1_local : STD_LOGIC;
    signal conv_buf_1_ce0_local : STD_LOGIC;
    signal add_ln64_fu_222_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_250_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_10_fu_262_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_608_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal bitcast_ln74_fu_306_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln74_1_fu_323_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_309_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln74_fu_319_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln74_1_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_326_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln74_1_fu_336_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln74_3_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_2_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln74_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln74_1_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln74_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln74_1_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln75_fu_394_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln75_1_fu_411_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_397_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln75_fu_407_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln75_1_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln75_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_414_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln75_1_fu_424_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln75_3_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln75_2_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln75_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln75_1_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln75_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln75_1_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln76_fu_482_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln76_1_fu_499_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_485_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln76_fu_495_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln76_1_fu_522_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_502_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln76_1_fu_512_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln76_3_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_2_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln76_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln76_1_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln76_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln76_1_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_608_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_608_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_608_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_617_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_617_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_617_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_160_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_00001_grp1 : BOOLEAN;
    signal grp_fu_164_ce : STD_LOGIC;
    signal grp_fu_168_ce : STD_LOGIC;
    signal grp_fu_608_ce : STD_LOGIC;
    signal grp_fu_617_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_608_p00 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_617_p00 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv2_pool2_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2_pool2_mac_muladd_5ns_4ns_4ns_8_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component conv2_pool2_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fcmp_32ns_32ns_1_2_no_dsp_1_U31 : component conv2_pool2_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => v10_reg_732,
        din1 => maxv_2_reg_739,
        ce => grp_fu_164_ce,
        opcode => ap_const_lv5_2,
        dout => grp_fu_164_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U32 : component conv2_pool2_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => v11_reg_751,
        din1 => maxv_4_reg_758,
        ce => grp_fu_168_ce,
        opcode => ap_const_lv5_2,
        dout => grp_fu_168_p2);

    mac_muladd_5ns_4ns_4ns_8_4_1_U33 : component conv2_pool2_mac_muladd_5ns_4ns_4ns_8_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 5,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_608_p0,
        din1 => grp_fu_608_p1,
        din2 => grp_fu_608_p2,
        ce => grp_fu_608_ce,
        dout => grp_fu_608_p3);

    mac_muladd_5ns_4ns_4ns_8_4_1_U34 : component conv2_pool2_mac_muladd_5ns_4ns_4ns_8_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 5,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_617_p0,
        din1 => grp_fu_617_p1,
        din2 => grp_fu_617_p2,
        ce => grp_fu_617_ce,
        dout => grp_fu_617_p3);

    flow_control_loop_pipe_sequential_init_U : component conv2_pool2_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten90_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln64_fu_199_p2 = ap_const_lv1_0))) then 
                    indvar_flatten90_fu_92 <= add_ln64_1_fu_205_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten90_fu_92 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    phi_ln77_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    phi_ln77_fu_80 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter12 = ap_const_logic_1)) then 
                    phi_ln77_fu_80 <= select_ln66_fu_583_p3;
                end if;
            end if; 
        end if;
    end process;

    px_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    px_fu_84 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    px_fu_84 <= add_ln66_fu_278_p2;
                end if;
            end if; 
        end if;
    end process;

    py_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    py_fu_88 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    py_fu_88 <= select_ln64_2_fu_242_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                add_ln71_reg_698 <= grp_fu_617_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln71_reg_698_pp0_iter5_reg <= add_ln71_reg_698;
                bitcast_ln77_reg_775 <= bitcast_ln77_fu_580_p1;
                icmp_ln66_reg_662_pp0_iter10_reg <= icmp_ln66_reg_662_pp0_iter9_reg;
                icmp_ln66_reg_662_pp0_iter11_reg <= icmp_ln66_reg_662_pp0_iter10_reg;
                icmp_ln66_reg_662_pp0_iter2_reg <= icmp_ln66_reg_662;
                icmp_ln66_reg_662_pp0_iter3_reg <= icmp_ln66_reg_662_pp0_iter2_reg;
                icmp_ln66_reg_662_pp0_iter4_reg <= icmp_ln66_reg_662_pp0_iter3_reg;
                icmp_ln66_reg_662_pp0_iter5_reg <= icmp_ln66_reg_662_pp0_iter4_reg;
                icmp_ln66_reg_662_pp0_iter6_reg <= icmp_ln66_reg_662_pp0_iter5_reg;
                icmp_ln66_reg_662_pp0_iter7_reg <= icmp_ln66_reg_662_pp0_iter6_reg;
                icmp_ln66_reg_662_pp0_iter8_reg <= icmp_ln66_reg_662_pp0_iter7_reg;
                icmp_ln66_reg_662_pp0_iter9_reg <= icmp_ln66_reg_662_pp0_iter8_reg;
                maxv_2_reg_739 <= maxv_2_fu_388_p3;
                maxv_2_reg_739_pp0_iter8_reg <= maxv_2_reg_739;
                maxv_4_reg_758 <= maxv_4_fu_476_p3;
                maxv_4_reg_758_pp0_iter10_reg <= maxv_4_reg_758;
                maxv_6_reg_765 <= maxv_6_fu_564_p3;
                select_ln64_1_reg_770 <= select_ln64_1_fu_573_p3;
                select_ln64_reg_667_pp0_iter2_reg <= select_ln64_reg_667;
                trunc_ln66_reg_682_pp0_iter10_reg <= trunc_ln66_reg_682_pp0_iter9_reg;
                trunc_ln66_reg_682_pp0_iter11_reg <= trunc_ln66_reg_682_pp0_iter10_reg;
                trunc_ln66_reg_682_pp0_iter12_reg <= trunc_ln66_reg_682_pp0_iter11_reg;
                trunc_ln66_reg_682_pp0_iter2_reg <= trunc_ln66_reg_682;
                trunc_ln66_reg_682_pp0_iter3_reg <= trunc_ln66_reg_682_pp0_iter2_reg;
                trunc_ln66_reg_682_pp0_iter4_reg <= trunc_ln66_reg_682_pp0_iter3_reg;
                trunc_ln66_reg_682_pp0_iter5_reg <= trunc_ln66_reg_682_pp0_iter4_reg;
                trunc_ln66_reg_682_pp0_iter6_reg <= trunc_ln66_reg_682_pp0_iter5_reg;
                trunc_ln66_reg_682_pp0_iter7_reg <= trunc_ln66_reg_682_pp0_iter6_reg;
                trunc_ln66_reg_682_pp0_iter8_reg <= trunc_ln66_reg_682_pp0_iter7_reg;
                trunc_ln66_reg_682_pp0_iter9_reg <= trunc_ln66_reg_682_pp0_iter8_reg;
                v00_reg_708_pp0_iter6_reg <= v00_reg_708;
                v01_reg_715_pp0_iter6_reg <= v01_reg_715;
                v10_reg_732_pp0_iter8_reg <= v10_reg_732;
                v11_reg_751_pp0_iter10_reg <= v11_reg_751;
                    zext_ln71_reg_722(7 downto 0) <= zext_ln71_fu_302_p1(7 downto 0);
                    zext_ln71_reg_722_pp0_iter7_reg(7 downto 0) <= zext_ln71_reg_722(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                icmp_ln66_reg_662 <= icmp_ln66_fu_228_p2;
                select_ln64_reg_667 <= select_ln64_fu_234_p3;
                trunc_ln66_reg_682 <= trunc_ln66_fu_274_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                v00_reg_708 <= conv_buf_q1;
                v01_reg_715 <= conv_buf_1_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                v10_reg_732 <= conv_buf_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                v11_reg_751 <= conv_buf_1_q0;
            end if;
        end if;
    end process;
    zext_ln71_reg_722(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln71_reg_722_pp0_iter7_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    AXI_OUT_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter13, m_axi_AXI_OUT_0_WREADY, trunc_ln66_reg_682_pp0_iter12_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (trunc_ln66_reg_682_pp0_iter12_reg = ap_const_lv1_1))) then 
            AXI_OUT_blk_n_W <= m_axi_AXI_OUT_0_WREADY;
        else 
            AXI_OUT_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    add_ln64_1_fu_205_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten90_load) + unsigned(ap_const_lv7_1));
    add_ln64_fu_222_p2 <= std_logic_vector(unsigned(py_fu_88) + unsigned(ap_const_lv4_1));
    add_ln66_fu_278_p2 <= std_logic_vector(unsigned(select_ln64_fu_234_p3) + unsigned(ap_const_lv4_1));
    and_ln74_1_fu_382_p2 <= (grp_fu_322_p_dout0 and and_ln74_fu_376_p2);
    and_ln74_fu_376_p2 <= (or_ln74_fu_352_p2 and or_ln74_1_fu_370_p2);
    and_ln75_1_fu_470_p2 <= (grp_fu_164_p2 and and_ln75_fu_464_p2);
    and_ln75_fu_464_p2 <= (or_ln75_fu_440_p2 and or_ln75_1_fu_458_p2);
    and_ln76_1_fu_558_p2 <= (grp_fu_168_p2 and and_ln76_fu_552_p2);
    and_ln76_fu_552_p2 <= (or_ln76_fu_528_p2 and or_ln76_1_fu_546_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_state14_io_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_io_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_state14_io_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_io_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_state14_io_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_io_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state14_io_grp1_assign_proc : process(m_axi_AXI_OUT_0_WREADY, trunc_ln66_reg_682_pp0_iter12_reg)
    begin
                ap_block_state14_io_grp1 <= ((m_axi_AXI_OUT_0_WREADY = ap_const_logic_0) and (trunc_ln66_reg_682_pp0_iter12_reg = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln64_fu_199_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln64_fu_199_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter12_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten90_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten90_fu_92, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten90_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten90_load <= indvar_flatten90_fu_92;
        end if; 
    end process;

    bitcast_ln74_1_fu_323_p1 <= v00_reg_708_pp0_iter6_reg;
    bitcast_ln74_fu_306_p1 <= v01_reg_715_pp0_iter6_reg;
    bitcast_ln75_1_fu_411_p1 <= maxv_2_reg_739_pp0_iter8_reg;
    bitcast_ln75_fu_394_p1 <= v10_reg_732_pp0_iter8_reg;
    bitcast_ln76_1_fu_499_p1 <= maxv_4_reg_758_pp0_iter10_reg;
    bitcast_ln76_fu_482_p1 <= v11_reg_751_pp0_iter10_reg;
    bitcast_ln77_fu_580_p1 <= maxv_6_reg_765;
    conv_buf_1_address0 <= zext_ln71_reg_722_pp0_iter7_reg(8 - 1 downto 0);
    conv_buf_1_address1 <= zext_ln69_1_fu_297_p1(8 - 1 downto 0);
    conv_buf_1_ce0 <= conv_buf_1_ce0_local;

    conv_buf_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            conv_buf_1_ce0_local <= ap_const_logic_1;
        else 
            conv_buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv_buf_1_ce1 <= conv_buf_1_ce1_local;

    conv_buf_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            conv_buf_1_ce1_local <= ap_const_logic_1;
        else 
            conv_buf_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    conv_buf_address0 <= zext_ln71_fu_302_p1(8 - 1 downto 0);
    conv_buf_address1 <= zext_ln69_1_fu_297_p1(8 - 1 downto 0);
    conv_buf_ce0 <= conv_buf_ce0_local;

    conv_buf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            conv_buf_ce0_local <= ap_const_logic_1;
        else 
            conv_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv_buf_ce1 <= conv_buf_ce1_local;

    conv_buf_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            conv_buf_ce1_local <= ap_const_logic_1;
        else 
            conv_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_160_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_160_ce <= ap_const_logic_1;
        else 
            grp_fu_160_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_164_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_164_ce <= ap_const_logic_1;
        else 
            grp_fu_164_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_168_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_168_ce <= ap_const_logic_1;
        else 
            grp_fu_168_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_322_p_ce <= grp_fu_160_ce;
    grp_fu_322_p_din0 <= v01_reg_715;
    grp_fu_322_p_din1 <= v00_reg_708;
    grp_fu_322_p_opcode <= ap_const_lv5_2;

    grp_fu_608_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_608_ce <= ap_const_logic_1;
        else 
            grp_fu_608_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_608_p0 <= grp_fu_608_p00(5 - 1 downto 0);
    grp_fu_608_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_250_p3),8));
    grp_fu_608_p1 <= ap_const_lv8_B(4 - 1 downto 0);
    grp_fu_608_p2 <= zext_ln69_fu_294_p1(4 - 1 downto 0);

    grp_fu_617_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_617_ce <= ap_const_logic_1;
        else 
            grp_fu_617_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_617_p0 <= grp_fu_617_p00(5 - 1 downto 0);
    grp_fu_617_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_262_p3),8));
    grp_fu_617_p1 <= ap_const_lv8_B(4 - 1 downto 0);
    grp_fu_617_p2 <= zext_ln69_fu_294_p1(4 - 1 downto 0);
    icmp_ln64_fu_199_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten90_load = ap_const_lv7_64) else "0";
    icmp_ln66_fu_228_p2 <= "1" when (px_fu_84 = ap_const_lv4_A) else "0";
    icmp_ln74_1_fu_346_p2 <= "1" when (trunc_ln74_fu_319_p1 = ap_const_lv23_0) else "0";
    icmp_ln74_2_fu_358_p2 <= "0" when (tmp_2_fu_326_p4 = ap_const_lv8_FF) else "1";
    icmp_ln74_3_fu_364_p2 <= "1" when (trunc_ln74_1_fu_336_p1 = ap_const_lv23_0) else "0";
    icmp_ln74_fu_340_p2 <= "0" when (tmp_1_fu_309_p4 = ap_const_lv8_FF) else "1";
    icmp_ln75_1_fu_434_p2 <= "1" when (trunc_ln75_fu_407_p1 = ap_const_lv23_0) else "0";
    icmp_ln75_2_fu_446_p2 <= "0" when (tmp_5_fu_414_p4 = ap_const_lv8_FF) else "1";
    icmp_ln75_3_fu_452_p2 <= "1" when (trunc_ln75_1_fu_424_p1 = ap_const_lv23_0) else "0";
    icmp_ln75_fu_428_p2 <= "0" when (tmp_4_fu_397_p4 = ap_const_lv8_FF) else "1";
    icmp_ln76_1_fu_522_p2 <= "1" when (trunc_ln76_fu_495_p1 = ap_const_lv23_0) else "0";
    icmp_ln76_2_fu_534_p2 <= "0" when (tmp_8_fu_502_p4 = ap_const_lv8_FF) else "1";
    icmp_ln76_3_fu_540_p2 <= "1" when (trunc_ln76_1_fu_512_p1 = ap_const_lv23_0) else "0";
    icmp_ln76_fu_516_p2 <= "0" when (tmp_7_fu_485_p4 = ap_const_lv8_FF) else "1";
    m_axi_AXI_OUT_0_ARADDR <= ap_const_lv64_0;
    m_axi_AXI_OUT_0_ARBURST <= ap_const_lv2_0;
    m_axi_AXI_OUT_0_ARCACHE <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_ARID <= ap_const_lv1_0;
    m_axi_AXI_OUT_0_ARLEN <= ap_const_lv32_0;
    m_axi_AXI_OUT_0_ARLOCK <= ap_const_lv2_0;
    m_axi_AXI_OUT_0_ARPROT <= ap_const_lv3_0;
    m_axi_AXI_OUT_0_ARQOS <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_ARREGION <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_ARSIZE <= ap_const_lv3_0;
    m_axi_AXI_OUT_0_ARUSER <= ap_const_lv1_0;
    m_axi_AXI_OUT_0_ARVALID <= ap_const_logic_0;
    m_axi_AXI_OUT_0_AWADDR <= ap_const_lv64_0;
    m_axi_AXI_OUT_0_AWBURST <= ap_const_lv2_0;
    m_axi_AXI_OUT_0_AWCACHE <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_AWID <= ap_const_lv1_0;
    m_axi_AXI_OUT_0_AWLEN <= ap_const_lv32_0;
    m_axi_AXI_OUT_0_AWLOCK <= ap_const_lv2_0;
    m_axi_AXI_OUT_0_AWPROT <= ap_const_lv3_0;
    m_axi_AXI_OUT_0_AWQOS <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_AWREGION <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_AWSIZE <= ap_const_lv3_0;
    m_axi_AXI_OUT_0_AWUSER <= ap_const_lv1_0;
    m_axi_AXI_OUT_0_AWVALID <= ap_const_logic_0;
    m_axi_AXI_OUT_0_BREADY <= ap_const_logic_0;
    m_axi_AXI_OUT_0_RREADY <= ap_const_logic_0;
    m_axi_AXI_OUT_0_WDATA <= (bitcast_ln77_reg_775 & select_ln64_1_reg_770);
    m_axi_AXI_OUT_0_WID <= ap_const_lv1_0;
    m_axi_AXI_OUT_0_WLAST <= ap_const_logic_0;
    m_axi_AXI_OUT_0_WSTRB <= ap_const_lv8_FF;
    m_axi_AXI_OUT_0_WUSER <= ap_const_lv1_0;

    m_axi_AXI_OUT_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter13, trunc_ln66_reg_682_pp0_iter12_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln66_reg_682_pp0_iter12_reg = ap_const_lv1_1))) then 
            m_axi_AXI_OUT_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_AXI_OUT_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    maxv_2_fu_388_p3 <= 
        v01_reg_715_pp0_iter6_reg when (and_ln74_1_fu_382_p2(0) = '1') else 
        v00_reg_708_pp0_iter6_reg;
    maxv_4_fu_476_p3 <= 
        v10_reg_732_pp0_iter8_reg when (and_ln75_1_fu_470_p2(0) = '1') else 
        maxv_2_reg_739_pp0_iter8_reg;
    maxv_6_fu_564_p3 <= 
        v11_reg_751_pp0_iter10_reg when (and_ln76_1_fu_558_p2(0) = '1') else 
        maxv_4_reg_758_pp0_iter10_reg;
    or_ln74_1_fu_370_p2 <= (icmp_ln74_3_fu_364_p2 or icmp_ln74_2_fu_358_p2);
    or_ln74_fu_352_p2 <= (icmp_ln74_fu_340_p2 or icmp_ln74_1_fu_346_p2);
    or_ln75_1_fu_458_p2 <= (icmp_ln75_3_fu_452_p2 or icmp_ln75_2_fu_446_p2);
    or_ln75_fu_440_p2 <= (icmp_ln75_fu_428_p2 or icmp_ln75_1_fu_434_p2);
    or_ln76_1_fu_546_p2 <= (icmp_ln76_3_fu_540_p2 or icmp_ln76_2_fu_534_p2);
    or_ln76_fu_528_p2 <= (icmp_ln76_fu_516_p2 or icmp_ln76_1_fu_522_p2);
    select_ln64_1_fu_573_p3 <= 
        ap_const_lv32_0 when (icmp_ln66_reg_662_pp0_iter11_reg(0) = '1') else 
        phi_ln77_fu_80;
    select_ln64_2_fu_242_p3 <= 
        add_ln64_fu_222_p2 when (icmp_ln66_fu_228_p2(0) = '1') else 
        py_fu_88;
    select_ln64_fu_234_p3 <= 
        ap_const_lv4_0 when (icmp_ln66_fu_228_p2(0) = '1') else 
        px_fu_84;
    select_ln66_fu_583_p3 <= 
        ap_const_lv32_0 when (trunc_ln66_reg_682_pp0_iter11_reg(0) = '1') else 
        bitcast_ln77_fu_580_p1;
    tmp_10_fu_262_p3 <= (select_ln64_2_fu_242_p3 & ap_const_lv1_1);
    tmp_1_fu_309_p4 <= bitcast_ln74_fu_306_p1(30 downto 23);
    tmp_2_fu_326_p4 <= bitcast_ln74_1_fu_323_p1(30 downto 23);
    tmp_4_fu_397_p4 <= bitcast_ln75_fu_394_p1(30 downto 23);
    tmp_5_fu_414_p4 <= bitcast_ln75_1_fu_411_p1(30 downto 23);
    tmp_7_fu_485_p4 <= bitcast_ln76_fu_482_p1(30 downto 23);
    tmp_8_fu_502_p4 <= bitcast_ln76_1_fu_499_p1(30 downto 23);
    tmp_s_fu_250_p3 <= (select_ln64_2_fu_242_p3 & ap_const_lv1_0);
    trunc_ln66_fu_274_p1 <= select_ln64_fu_234_p3(1 - 1 downto 0);
    trunc_ln74_1_fu_336_p1 <= bitcast_ln74_1_fu_323_p1(23 - 1 downto 0);
    trunc_ln74_fu_319_p1 <= bitcast_ln74_fu_306_p1(23 - 1 downto 0);
    trunc_ln75_1_fu_424_p1 <= bitcast_ln75_1_fu_411_p1(23 - 1 downto 0);
    trunc_ln75_fu_407_p1 <= bitcast_ln75_fu_394_p1(23 - 1 downto 0);
    trunc_ln76_1_fu_512_p1 <= bitcast_ln76_1_fu_499_p1(23 - 1 downto 0);
    trunc_ln76_fu_495_p1 <= bitcast_ln76_fu_482_p1(23 - 1 downto 0);
    zext_ln69_1_fu_297_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_608_p3),64));
    zext_ln69_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln64_reg_667_pp0_iter2_reg),8));
    zext_ln71_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln71_reg_698_pp0_iter5_reg),64));
end behav;
