// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv1_pool1_conv1_pool1_Pipeline_LOAD (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_AXI_IN_0_AWVALID,
        m_axi_AXI_IN_0_AWREADY,
        m_axi_AXI_IN_0_AWADDR,
        m_axi_AXI_IN_0_AWID,
        m_axi_AXI_IN_0_AWLEN,
        m_axi_AXI_IN_0_AWSIZE,
        m_axi_AXI_IN_0_AWBURST,
        m_axi_AXI_IN_0_AWLOCK,
        m_axi_AXI_IN_0_AWCACHE,
        m_axi_AXI_IN_0_AWPROT,
        m_axi_AXI_IN_0_AWQOS,
        m_axi_AXI_IN_0_AWREGION,
        m_axi_AXI_IN_0_AWUSER,
        m_axi_AXI_IN_0_WVALID,
        m_axi_AXI_IN_0_WREADY,
        m_axi_AXI_IN_0_WDATA,
        m_axi_AXI_IN_0_WSTRB,
        m_axi_AXI_IN_0_WLAST,
        m_axi_AXI_IN_0_WID,
        m_axi_AXI_IN_0_WUSER,
        m_axi_AXI_IN_0_ARVALID,
        m_axi_AXI_IN_0_ARREADY,
        m_axi_AXI_IN_0_ARADDR,
        m_axi_AXI_IN_0_ARID,
        m_axi_AXI_IN_0_ARLEN,
        m_axi_AXI_IN_0_ARSIZE,
        m_axi_AXI_IN_0_ARBURST,
        m_axi_AXI_IN_0_ARLOCK,
        m_axi_AXI_IN_0_ARCACHE,
        m_axi_AXI_IN_0_ARPROT,
        m_axi_AXI_IN_0_ARQOS,
        m_axi_AXI_IN_0_ARREGION,
        m_axi_AXI_IN_0_ARUSER,
        m_axi_AXI_IN_0_RVALID,
        m_axi_AXI_IN_0_RREADY,
        m_axi_AXI_IN_0_RDATA,
        m_axi_AXI_IN_0_RLAST,
        m_axi_AXI_IN_0_RID,
        m_axi_AXI_IN_0_RFIFONUM,
        m_axi_AXI_IN_0_RUSER,
        m_axi_AXI_IN_0_RRESP,
        m_axi_AXI_IN_0_BVALID,
        m_axi_AXI_IN_0_BREADY,
        m_axi_AXI_IN_0_BRESP,
        m_axi_AXI_IN_0_BID,
        m_axi_AXI_IN_0_BUSER,
        in_buf_address0,
        in_buf_ce0,
        in_buf_we0,
        in_buf_d0,
        in_buf_1_address0,
        in_buf_1_ce0,
        in_buf_1_we0,
        in_buf_1_d0,
        in_buf_2_address0,
        in_buf_2_ce0,
        in_buf_2_we0,
        in_buf_2_d0,
        in_buf_3_address0,
        in_buf_3_ce0,
        in_buf_3_we0,
        in_buf_3_d0,
        in_buf_4_address0,
        in_buf_4_ce0,
        in_buf_4_we0,
        in_buf_4_d0,
        in_buf_5_address0,
        in_buf_5_ce0,
        in_buf_5_we0,
        in_buf_5_d0,
        in_buf_6_address0,
        in_buf_6_ce0,
        in_buf_6_we0,
        in_buf_6_d0,
        in_buf_7_address0,
        in_buf_7_ce0,
        in_buf_7_we0,
        in_buf_7_d0,
        in_buf_8_address0,
        in_buf_8_ce0,
        in_buf_8_we0,
        in_buf_8_d0,
        in_buf_9_address0,
        in_buf_9_ce0,
        in_buf_9_we0,
        in_buf_9_d0,
        in_buf_10_address0,
        in_buf_10_ce0,
        in_buf_10_we0,
        in_buf_10_d0,
        in_buf_11_address0,
        in_buf_11_ce0,
        in_buf_11_we0,
        in_buf_11_d0,
        in_buf_12_address0,
        in_buf_12_ce0,
        in_buf_12_we0,
        in_buf_12_d0,
        in_buf_13_address0,
        in_buf_13_ce0,
        in_buf_13_we0,
        in_buf_13_d0,
        in_buf_14_address0,
        in_buf_14_ce0,
        in_buf_14_we0,
        in_buf_14_d0,
        in_buf_15_address0,
        in_buf_15_ce0,
        in_buf_15_we0,
        in_buf_15_d0,
        in_buf_16_address0,
        in_buf_16_ce0,
        in_buf_16_we0,
        in_buf_16_d0,
        in_buf_17_address0,
        in_buf_17_ce0,
        in_buf_17_we0,
        in_buf_17_d0,
        in_buf_18_address0,
        in_buf_18_ce0,
        in_buf_18_we0,
        in_buf_18_d0,
        in_buf_19_address0,
        in_buf_19_ce0,
        in_buf_19_we0,
        in_buf_19_d0,
        in_buf_20_address0,
        in_buf_20_ce0,
        in_buf_20_we0,
        in_buf_20_d0,
        in_buf_21_address0,
        in_buf_21_ce0,
        in_buf_21_we0,
        in_buf_21_d0,
        in_buf_22_address0,
        in_buf_22_ce0,
        in_buf_22_we0,
        in_buf_22_d0,
        in_buf_23_address0,
        in_buf_23_ce0,
        in_buf_23_we0,
        in_buf_23_d0,
        sext_ln67
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_AXI_IN_0_AWVALID;
input   m_axi_AXI_IN_0_AWREADY;
output  [63:0] m_axi_AXI_IN_0_AWADDR;
output  [0:0] m_axi_AXI_IN_0_AWID;
output  [31:0] m_axi_AXI_IN_0_AWLEN;
output  [2:0] m_axi_AXI_IN_0_AWSIZE;
output  [1:0] m_axi_AXI_IN_0_AWBURST;
output  [1:0] m_axi_AXI_IN_0_AWLOCK;
output  [3:0] m_axi_AXI_IN_0_AWCACHE;
output  [2:0] m_axi_AXI_IN_0_AWPROT;
output  [3:0] m_axi_AXI_IN_0_AWQOS;
output  [3:0] m_axi_AXI_IN_0_AWREGION;
output  [0:0] m_axi_AXI_IN_0_AWUSER;
output   m_axi_AXI_IN_0_WVALID;
input   m_axi_AXI_IN_0_WREADY;
output  [511:0] m_axi_AXI_IN_0_WDATA;
output  [63:0] m_axi_AXI_IN_0_WSTRB;
output   m_axi_AXI_IN_0_WLAST;
output  [0:0] m_axi_AXI_IN_0_WID;
output  [0:0] m_axi_AXI_IN_0_WUSER;
output   m_axi_AXI_IN_0_ARVALID;
input   m_axi_AXI_IN_0_ARREADY;
output  [63:0] m_axi_AXI_IN_0_ARADDR;
output  [0:0] m_axi_AXI_IN_0_ARID;
output  [31:0] m_axi_AXI_IN_0_ARLEN;
output  [2:0] m_axi_AXI_IN_0_ARSIZE;
output  [1:0] m_axi_AXI_IN_0_ARBURST;
output  [1:0] m_axi_AXI_IN_0_ARLOCK;
output  [3:0] m_axi_AXI_IN_0_ARCACHE;
output  [2:0] m_axi_AXI_IN_0_ARPROT;
output  [3:0] m_axi_AXI_IN_0_ARQOS;
output  [3:0] m_axi_AXI_IN_0_ARREGION;
output  [0:0] m_axi_AXI_IN_0_ARUSER;
input   m_axi_AXI_IN_0_RVALID;
output   m_axi_AXI_IN_0_RREADY;
input  [511:0] m_axi_AXI_IN_0_RDATA;
input   m_axi_AXI_IN_0_RLAST;
input  [0:0] m_axi_AXI_IN_0_RID;
input  [8:0] m_axi_AXI_IN_0_RFIFONUM;
input  [0:0] m_axi_AXI_IN_0_RUSER;
input  [1:0] m_axi_AXI_IN_0_RRESP;
input   m_axi_AXI_IN_0_BVALID;
output   m_axi_AXI_IN_0_BREADY;
input  [1:0] m_axi_AXI_IN_0_BRESP;
input  [0:0] m_axi_AXI_IN_0_BID;
input  [0:0] m_axi_AXI_IN_0_BUSER;
output  [6:0] in_buf_address0;
output   in_buf_ce0;
output   in_buf_we0;
output  [31:0] in_buf_d0;
output  [6:0] in_buf_1_address0;
output   in_buf_1_ce0;
output   in_buf_1_we0;
output  [31:0] in_buf_1_d0;
output  [6:0] in_buf_2_address0;
output   in_buf_2_ce0;
output   in_buf_2_we0;
output  [31:0] in_buf_2_d0;
output  [6:0] in_buf_3_address0;
output   in_buf_3_ce0;
output   in_buf_3_we0;
output  [31:0] in_buf_3_d0;
output  [6:0] in_buf_4_address0;
output   in_buf_4_ce0;
output   in_buf_4_we0;
output  [31:0] in_buf_4_d0;
output  [6:0] in_buf_5_address0;
output   in_buf_5_ce0;
output   in_buf_5_we0;
output  [31:0] in_buf_5_d0;
output  [6:0] in_buf_6_address0;
output   in_buf_6_ce0;
output   in_buf_6_we0;
output  [31:0] in_buf_6_d0;
output  [6:0] in_buf_7_address0;
output   in_buf_7_ce0;
output   in_buf_7_we0;
output  [31:0] in_buf_7_d0;
output  [6:0] in_buf_8_address0;
output   in_buf_8_ce0;
output   in_buf_8_we0;
output  [31:0] in_buf_8_d0;
output  [6:0] in_buf_9_address0;
output   in_buf_9_ce0;
output   in_buf_9_we0;
output  [31:0] in_buf_9_d0;
output  [6:0] in_buf_10_address0;
output   in_buf_10_ce0;
output   in_buf_10_we0;
output  [31:0] in_buf_10_d0;
output  [6:0] in_buf_11_address0;
output   in_buf_11_ce0;
output   in_buf_11_we0;
output  [31:0] in_buf_11_d0;
output  [6:0] in_buf_12_address0;
output   in_buf_12_ce0;
output   in_buf_12_we0;
output  [31:0] in_buf_12_d0;
output  [6:0] in_buf_13_address0;
output   in_buf_13_ce0;
output   in_buf_13_we0;
output  [31:0] in_buf_13_d0;
output  [6:0] in_buf_14_address0;
output   in_buf_14_ce0;
output   in_buf_14_we0;
output  [31:0] in_buf_14_d0;
output  [6:0] in_buf_15_address0;
output   in_buf_15_ce0;
output   in_buf_15_we0;
output  [31:0] in_buf_15_d0;
output  [6:0] in_buf_16_address0;
output   in_buf_16_ce0;
output   in_buf_16_we0;
output  [31:0] in_buf_16_d0;
output  [6:0] in_buf_17_address0;
output   in_buf_17_ce0;
output   in_buf_17_we0;
output  [31:0] in_buf_17_d0;
output  [6:0] in_buf_18_address0;
output   in_buf_18_ce0;
output   in_buf_18_we0;
output  [31:0] in_buf_18_d0;
output  [6:0] in_buf_19_address0;
output   in_buf_19_ce0;
output   in_buf_19_we0;
output  [31:0] in_buf_19_d0;
output  [6:0] in_buf_20_address0;
output   in_buf_20_ce0;
output   in_buf_20_we0;
output  [31:0] in_buf_20_d0;
output  [6:0] in_buf_21_address0;
output   in_buf_21_ce0;
output   in_buf_21_we0;
output  [31:0] in_buf_21_d0;
output  [6:0] in_buf_22_address0;
output   in_buf_22_ce0;
output   in_buf_22_we0;
output  [31:0] in_buf_22_d0;
output  [6:0] in_buf_23_address0;
output   in_buf_23_ce0;
output   in_buf_23_we0;
output  [31:0] in_buf_23_d0;
input  [57:0] sext_ln67;

reg ap_idle;
reg m_axi_AXI_IN_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln67_reg_840;
reg   [0:0] icmp_ln67_reg_840_pp0_iter9_reg;
reg   [0:0] icmp_ln69_reg_844;
reg   [0:0] icmp_ln69_reg_844_pp0_iter9_reg;
reg    ap_predicate_op60_read_state11;
reg    ap_block_state11_pp0_stage0_iter10_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln67_fu_544_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    AXI_IN_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln67_reg_840_pp0_iter2_reg;
reg   [0:0] icmp_ln67_reg_840_pp0_iter3_reg;
reg   [0:0] icmp_ln67_reg_840_pp0_iter4_reg;
reg   [0:0] icmp_ln67_reg_840_pp0_iter5_reg;
reg   [0:0] icmp_ln67_reg_840_pp0_iter6_reg;
reg   [0:0] icmp_ln67_reg_840_pp0_iter7_reg;
reg   [0:0] icmp_ln67_reg_840_pp0_iter8_reg;
reg   [0:0] icmp_ln67_reg_840_pp0_iter10_reg;
wire   [0:0] icmp_ln69_fu_560_p2;
reg   [0:0] icmp_ln69_reg_844_pp0_iter2_reg;
reg   [0:0] icmp_ln69_reg_844_pp0_iter3_reg;
reg   [0:0] icmp_ln69_reg_844_pp0_iter4_reg;
reg   [0:0] icmp_ln69_reg_844_pp0_iter5_reg;
reg   [0:0] icmp_ln69_reg_844_pp0_iter6_reg;
reg   [0:0] icmp_ln69_reg_844_pp0_iter7_reg;
reg   [0:0] icmp_ln69_reg_844_pp0_iter8_reg;
reg   [0:0] icmp_ln69_reg_844_pp0_iter10_reg;
wire   [2:0] trunc_ln69_2_fu_569_p1;
reg   [2:0] trunc_ln69_2_reg_848;
reg   [2:0] trunc_ln69_2_reg_848_pp0_iter2_reg;
reg   [2:0] trunc_ln69_2_reg_848_pp0_iter3_reg;
reg   [2:0] trunc_ln69_2_reg_848_pp0_iter4_reg;
reg   [2:0] trunc_ln69_2_reg_848_pp0_iter5_reg;
reg   [2:0] trunc_ln69_2_reg_848_pp0_iter6_reg;
reg   [2:0] trunc_ln69_2_reg_848_pp0_iter7_reg;
reg   [2:0] trunc_ln69_2_reg_848_pp0_iter8_reg;
reg   [2:0] trunc_ln69_2_reg_848_pp0_iter9_reg;
reg   [2:0] trunc_ln69_2_reg_848_pp0_iter10_reg;
reg   [511:0] AXI_IN_addr_read_reg_857;
wire   [1:0] trunc_ln69_4_fu_611_p1;
reg   [1:0] trunc_ln69_4_reg_862;
reg   [511:0] ap_phi_mux_empty_phi_fu_506_p4;
wire   [511:0] ap_phi_reg_pp0_iter11_empty_reg_503;
wire   [511:0] zext_ln67_fu_618_p1;
wire   [63:0] zext_ln69_2_fu_733_p1;
reg   [11:0] phi_urem_fu_160;
wire   [11:0] select_ln67_fu_776_p3;
wire    ap_loop_init;
reg   [24:0] phi_mul49_fu_164;
wire   [24:0] add_ln69_2_fu_671_p2;
reg   [23:0] phi_mul_fu_168;
wire   [23:0] add_ln69_1_fu_573_p2;
wire    ap_block_pp0_stage0;
reg   [479:0] shiftreg_fu_172;
reg   [11:0] i_fu_176;
wire   [11:0] add_ln67_fu_550_p2;
reg    in_buf_19_we0_local;
wire   [31:0] bitcast_ln69_fu_633_p1;
reg    in_buf_19_ce0_local;
reg    in_buf_18_we0_local;
reg    in_buf_18_ce0_local;
reg    in_buf_20_we0_local;
reg    in_buf_20_ce0_local;
reg    in_buf_16_we0_local;
reg    in_buf_16_ce0_local;
reg    in_buf_15_we0_local;
reg    in_buf_15_ce0_local;
reg    in_buf_17_we0_local;
reg    in_buf_17_ce0_local;
reg    in_buf_13_we0_local;
reg    in_buf_13_ce0_local;
reg    in_buf_12_we0_local;
reg    in_buf_12_ce0_local;
reg    in_buf_14_we0_local;
reg    in_buf_14_ce0_local;
reg    in_buf_10_we0_local;
reg    in_buf_10_ce0_local;
reg    in_buf_9_we0_local;
reg    in_buf_9_ce0_local;
reg    in_buf_11_we0_local;
reg    in_buf_11_ce0_local;
reg    in_buf_7_we0_local;
reg    in_buf_7_ce0_local;
reg    in_buf_6_we0_local;
reg    in_buf_6_ce0_local;
reg    in_buf_8_we0_local;
reg    in_buf_8_ce0_local;
reg    in_buf_4_we0_local;
reg    in_buf_4_ce0_local;
reg    in_buf_3_we0_local;
reg    in_buf_3_ce0_local;
reg    in_buf_5_we0_local;
reg    in_buf_5_ce0_local;
reg    in_buf_1_we0_local;
reg    in_buf_1_ce0_local;
reg    in_buf_we0_local;
reg    in_buf_ce0_local;
reg    in_buf_2_we0_local;
reg    in_buf_2_ce0_local;
reg    in_buf_22_we0_local;
reg    in_buf_22_ce0_local;
reg    in_buf_21_we0_local;
reg    in_buf_21_ce0_local;
reg    in_buf_23_we0_local;
reg    in_buf_23_ce0_local;
wire   [3:0] trunc_ln67_fu_556_p1;
wire   [5:0] grp_fu_589_p0;
wire   [2:0] grp_fu_589_p1;
wire   [1:0] grp_fu_589_p2;
wire   [31:0] trunc_ln69_fu_629_p1;
wire   [3:0] tmp_fu_677_p4;
wire   [4:0] tmp_1_fu_695_p3;
wire   [6:0] p_shl_fu_687_p3;
wire   [6:0] zext_ln69_fu_703_p1;
wire   [2:0] lshr_ln69_1_fu_713_p4;
wire   [6:0] sub_ln69_fu_707_p2;
wire   [6:0] zext_ln69_1_fu_723_p1;
wire   [6:0] add_ln69_fu_727_p2;
wire   [0:0] icmp_ln67_1_fu_770_p2;
wire   [11:0] add_ln67_1_fu_764_p2;
reg    grp_fu_589_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 phi_urem_fu_160 = 12'd0;
#0 phi_mul49_fu_164 = 25'd0;
#0 phi_mul_fu_168 = 24'd0;
#0 shiftreg_fu_172 = 480'd0;
#0 i_fu_176 = 12'd0;
#0 ap_done_reg = 1'b0;
end

conv1_pool1_urem_6ns_3ns_2_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_6ns_3ns_2_10_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_589_p0),
    .din1(grp_fu_589_p1),
    .ce(grp_fu_589_ce),
    .dout(grp_fu_589_p2)
);

conv1_pool1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_176 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln67_fu_544_p2 == 1'd0))) begin
            i_fu_176 <= add_ln67_fu_550_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            phi_mul49_fu_164 <= 25'd0;
        end else if ((ap_enable_reg_pp0_iter11 == 1'b1)) begin
            phi_mul49_fu_164 <= add_ln69_2_fu_671_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_mul_fu_168 <= 24'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln67_fu_544_p2 == 1'd0))) begin
            phi_mul_fu_168 <= add_ln69_1_fu_573_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            phi_urem_fu_160 <= 12'd0;
        end else if ((ap_enable_reg_pp0_iter11 == 1'b1)) begin
            phi_urem_fu_160 <= select_ln67_fu_776_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            shiftreg_fu_172 <= 480'd0;
        end else if ((ap_enable_reg_pp0_iter11 == 1'b1)) begin
            shiftreg_fu_172 <= {{ap_phi_mux_empty_phi_fu_506_p4[511:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        AXI_IN_addr_read_reg_857 <= m_axi_AXI_IN_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln67_reg_840_pp0_iter10_reg <= icmp_ln67_reg_840_pp0_iter9_reg;
        icmp_ln67_reg_840_pp0_iter2_reg <= icmp_ln67_reg_840;
        icmp_ln67_reg_840_pp0_iter3_reg <= icmp_ln67_reg_840_pp0_iter2_reg;
        icmp_ln67_reg_840_pp0_iter4_reg <= icmp_ln67_reg_840_pp0_iter3_reg;
        icmp_ln67_reg_840_pp0_iter5_reg <= icmp_ln67_reg_840_pp0_iter4_reg;
        icmp_ln67_reg_840_pp0_iter6_reg <= icmp_ln67_reg_840_pp0_iter5_reg;
        icmp_ln67_reg_840_pp0_iter7_reg <= icmp_ln67_reg_840_pp0_iter6_reg;
        icmp_ln67_reg_840_pp0_iter8_reg <= icmp_ln67_reg_840_pp0_iter7_reg;
        icmp_ln67_reg_840_pp0_iter9_reg <= icmp_ln67_reg_840_pp0_iter8_reg;
        icmp_ln69_reg_844_pp0_iter10_reg <= icmp_ln69_reg_844_pp0_iter9_reg;
        icmp_ln69_reg_844_pp0_iter2_reg <= icmp_ln69_reg_844;
        icmp_ln69_reg_844_pp0_iter3_reg <= icmp_ln69_reg_844_pp0_iter2_reg;
        icmp_ln69_reg_844_pp0_iter4_reg <= icmp_ln69_reg_844_pp0_iter3_reg;
        icmp_ln69_reg_844_pp0_iter5_reg <= icmp_ln69_reg_844_pp0_iter4_reg;
        icmp_ln69_reg_844_pp0_iter6_reg <= icmp_ln69_reg_844_pp0_iter5_reg;
        icmp_ln69_reg_844_pp0_iter7_reg <= icmp_ln69_reg_844_pp0_iter6_reg;
        icmp_ln69_reg_844_pp0_iter8_reg <= icmp_ln69_reg_844_pp0_iter7_reg;
        icmp_ln69_reg_844_pp0_iter9_reg <= icmp_ln69_reg_844_pp0_iter8_reg;
        trunc_ln69_2_reg_848_pp0_iter10_reg <= trunc_ln69_2_reg_848_pp0_iter9_reg;
        trunc_ln69_2_reg_848_pp0_iter2_reg <= trunc_ln69_2_reg_848;
        trunc_ln69_2_reg_848_pp0_iter3_reg <= trunc_ln69_2_reg_848_pp0_iter2_reg;
        trunc_ln69_2_reg_848_pp0_iter4_reg <= trunc_ln69_2_reg_848_pp0_iter3_reg;
        trunc_ln69_2_reg_848_pp0_iter5_reg <= trunc_ln69_2_reg_848_pp0_iter4_reg;
        trunc_ln69_2_reg_848_pp0_iter6_reg <= trunc_ln69_2_reg_848_pp0_iter5_reg;
        trunc_ln69_2_reg_848_pp0_iter7_reg <= trunc_ln69_2_reg_848_pp0_iter6_reg;
        trunc_ln69_2_reg_848_pp0_iter8_reg <= trunc_ln69_2_reg_848_pp0_iter7_reg;
        trunc_ln69_2_reg_848_pp0_iter9_reg <= trunc_ln69_2_reg_848_pp0_iter8_reg;
        trunc_ln69_4_reg_862 <= trunc_ln69_4_fu_611_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln67_reg_840 <= icmp_ln67_fu_544_p2;
        icmp_ln69_reg_844 <= icmp_ln69_fu_560_p2;
        trunc_ln69_2_reg_848 <= trunc_ln69_2_fu_569_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op60_read_state11 == 1'b1))) begin
        AXI_IN_blk_n_R = m_axi_AXI_IN_0_RVALID;
    end else begin
        AXI_IN_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln67_fu_544_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln67_reg_840_pp0_iter10_reg == 1'd0)) begin
        if ((icmp_ln69_reg_844_pp0_iter10_reg == 1'd0)) begin
            ap_phi_mux_empty_phi_fu_506_p4 = zext_ln67_fu_618_p1;
        end else if ((icmp_ln69_reg_844_pp0_iter10_reg == 1'd1)) begin
            ap_phi_mux_empty_phi_fu_506_p4 = AXI_IN_addr_read_reg_857;
        end else begin
            ap_phi_mux_empty_phi_fu_506_p4 = ap_phi_reg_pp0_iter11_empty_reg_503;
        end
    end else begin
        ap_phi_mux_empty_phi_fu_506_p4 = ap_phi_reg_pp0_iter11_empty_reg_503;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_589_ce = 1'b1;
    end else begin
        grp_fu_589_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_10_ce0_local = 1'b1;
    end else begin
        in_buf_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_10_we0_local = 1'b1;
    end else begin
        in_buf_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_11_ce0_local = 1'b1;
    end else begin
        in_buf_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln69_4_reg_862 == 2'd0) & ~(trunc_ln69_4_reg_862 == 2'd1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_11_we0_local = 1'b1;
    end else begin
        in_buf_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_12_ce0_local = 1'b1;
    end else begin
        in_buf_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd0) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_12_we0_local = 1'b1;
    end else begin
        in_buf_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_13_ce0_local = 1'b1;
    end else begin
        in_buf_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_13_we0_local = 1'b1;
    end else begin
        in_buf_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_14_ce0_local = 1'b1;
    end else begin
        in_buf_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln69_4_reg_862 == 2'd0) & ~(trunc_ln69_4_reg_862 == 2'd1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_14_we0_local = 1'b1;
    end else begin
        in_buf_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_15_ce0_local = 1'b1;
    end else begin
        in_buf_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd0) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_15_we0_local = 1'b1;
    end else begin
        in_buf_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_16_ce0_local = 1'b1;
    end else begin
        in_buf_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_16_we0_local = 1'b1;
    end else begin
        in_buf_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_17_ce0_local = 1'b1;
    end else begin
        in_buf_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln69_4_reg_862 == 2'd0) & ~(trunc_ln69_4_reg_862 == 2'd1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_17_we0_local = 1'b1;
    end else begin
        in_buf_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_18_ce0_local = 1'b1;
    end else begin
        in_buf_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd0) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_18_we0_local = 1'b1;
    end else begin
        in_buf_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_19_ce0_local = 1'b1;
    end else begin
        in_buf_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_19_we0_local = 1'b1;
    end else begin
        in_buf_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_1_ce0_local = 1'b1;
    end else begin
        in_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_1_we0_local = 1'b1;
    end else begin
        in_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_20_ce0_local = 1'b1;
    end else begin
        in_buf_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln69_4_reg_862 == 2'd0) & ~(trunc_ln69_4_reg_862 == 2'd1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_20_we0_local = 1'b1;
    end else begin
        in_buf_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_21_ce0_local = 1'b1;
    end else begin
        in_buf_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd0) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_21_we0_local = 1'b1;
    end else begin
        in_buf_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_22_ce0_local = 1'b1;
    end else begin
        in_buf_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_22_we0_local = 1'b1;
    end else begin
        in_buf_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_23_ce0_local = 1'b1;
    end else begin
        in_buf_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln69_4_reg_862 == 2'd0) & ~(trunc_ln69_4_reg_862 == 2'd1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_23_we0_local = 1'b1;
    end else begin
        in_buf_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_2_ce0_local = 1'b1;
    end else begin
        in_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln69_4_reg_862 == 2'd0) & ~(trunc_ln69_4_reg_862 == 2'd1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_2_we0_local = 1'b1;
    end else begin
        in_buf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_3_ce0_local = 1'b1;
    end else begin
        in_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd0) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_3_we0_local = 1'b1;
    end else begin
        in_buf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_4_ce0_local = 1'b1;
    end else begin
        in_buf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_4_we0_local = 1'b1;
    end else begin
        in_buf_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_5_ce0_local = 1'b1;
    end else begin
        in_buf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln69_4_reg_862 == 2'd0) & ~(trunc_ln69_4_reg_862 == 2'd1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_5_we0_local = 1'b1;
    end else begin
        in_buf_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_6_ce0_local = 1'b1;
    end else begin
        in_buf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd0) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_6_we0_local = 1'b1;
    end else begin
        in_buf_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_7_ce0_local = 1'b1;
    end else begin
        in_buf_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_7_we0_local = 1'b1;
    end else begin
        in_buf_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_8_ce0_local = 1'b1;
    end else begin
        in_buf_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln69_4_reg_862 == 2'd0) & ~(trunc_ln69_4_reg_862 == 2'd1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_8_we0_local = 1'b1;
    end else begin
        in_buf_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_9_ce0_local = 1'b1;
    end else begin
        in_buf_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd0) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_9_we0_local = 1'b1;
    end else begin
        in_buf_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_ce0_local = 1'b1;
    end else begin
        in_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln69_4_reg_862 == 2'd0) & (trunc_ln69_2_reg_848_pp0_iter10_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_buf_we0_local = 1'b1;
    end else begin
        in_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op60_read_state11 == 1'b1))) begin
        m_axi_AXI_IN_0_RREADY = 1'b1;
    end else begin
        m_axi_AXI_IN_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_1_fu_764_p2 = (phi_urem_fu_160 + 12'd1);

assign add_ln67_fu_550_p2 = (i_fu_176 + 12'd1);

assign add_ln69_1_fu_573_p2 = (phi_mul_fu_168 + 24'd5462);

assign add_ln69_2_fu_671_p2 = (phi_mul49_fu_164 + 25'd7282);

assign add_ln69_fu_727_p2 = (sub_ln69_fu_707_p2 + zext_ln69_1_fu_723_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp0_stage0_iter10_grp1 = ((m_axi_AXI_IN_0_RVALID == 1'b0) & (ap_predicate_op60_read_state11 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter11_empty_reg_503 = 'bx;

always @ (*) begin
    ap_predicate_op60_read_state11 = ((icmp_ln69_reg_844_pp0_iter9_reg == 1'd1) & (icmp_ln67_reg_840_pp0_iter9_reg == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign bitcast_ln69_fu_633_p1 = trunc_ln69_fu_629_p1;

assign grp_fu_589_p0 = {{phi_mul_fu_168[23:18]}};

assign grp_fu_589_p1 = 6'd3;

assign icmp_ln67_1_fu_770_p2 = ((phi_urem_fu_160 == 12'd47) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_544_p2 = ((i_fu_176 == 12'd2304) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_560_p2 = ((trunc_ln67_fu_556_p1 == 4'd0) ? 1'b1 : 1'b0);

assign in_buf_10_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_10_ce0 = in_buf_10_ce0_local;

assign in_buf_10_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_10_we0 = in_buf_10_we0_local;

assign in_buf_11_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_11_ce0 = in_buf_11_ce0_local;

assign in_buf_11_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_11_we0 = in_buf_11_we0_local;

assign in_buf_12_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_12_ce0 = in_buf_12_ce0_local;

assign in_buf_12_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_12_we0 = in_buf_12_we0_local;

assign in_buf_13_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_13_ce0 = in_buf_13_ce0_local;

assign in_buf_13_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_13_we0 = in_buf_13_we0_local;

assign in_buf_14_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_14_ce0 = in_buf_14_ce0_local;

assign in_buf_14_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_14_we0 = in_buf_14_we0_local;

assign in_buf_15_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_15_ce0 = in_buf_15_ce0_local;

assign in_buf_15_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_15_we0 = in_buf_15_we0_local;

assign in_buf_16_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_16_ce0 = in_buf_16_ce0_local;

assign in_buf_16_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_16_we0 = in_buf_16_we0_local;

assign in_buf_17_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_17_ce0 = in_buf_17_ce0_local;

assign in_buf_17_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_17_we0 = in_buf_17_we0_local;

assign in_buf_18_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_18_ce0 = in_buf_18_ce0_local;

assign in_buf_18_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_18_we0 = in_buf_18_we0_local;

assign in_buf_19_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_19_ce0 = in_buf_19_ce0_local;

assign in_buf_19_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_19_we0 = in_buf_19_we0_local;

assign in_buf_1_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_1_ce0 = in_buf_1_ce0_local;

assign in_buf_1_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_1_we0 = in_buf_1_we0_local;

assign in_buf_20_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_20_ce0 = in_buf_20_ce0_local;

assign in_buf_20_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_20_we0 = in_buf_20_we0_local;

assign in_buf_21_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_21_ce0 = in_buf_21_ce0_local;

assign in_buf_21_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_21_we0 = in_buf_21_we0_local;

assign in_buf_22_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_22_ce0 = in_buf_22_ce0_local;

assign in_buf_22_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_22_we0 = in_buf_22_we0_local;

assign in_buf_23_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_23_ce0 = in_buf_23_ce0_local;

assign in_buf_23_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_23_we0 = in_buf_23_we0_local;

assign in_buf_2_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_2_ce0 = in_buf_2_ce0_local;

assign in_buf_2_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_2_we0 = in_buf_2_we0_local;

assign in_buf_3_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_3_ce0 = in_buf_3_ce0_local;

assign in_buf_3_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_3_we0 = in_buf_3_we0_local;

assign in_buf_4_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_4_ce0 = in_buf_4_ce0_local;

assign in_buf_4_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_4_we0 = in_buf_4_we0_local;

assign in_buf_5_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_5_ce0 = in_buf_5_ce0_local;

assign in_buf_5_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_5_we0 = in_buf_5_we0_local;

assign in_buf_6_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_6_ce0 = in_buf_6_ce0_local;

assign in_buf_6_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_6_we0 = in_buf_6_we0_local;

assign in_buf_7_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_7_ce0 = in_buf_7_ce0_local;

assign in_buf_7_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_7_we0 = in_buf_7_we0_local;

assign in_buf_8_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_8_ce0 = in_buf_8_ce0_local;

assign in_buf_8_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_8_we0 = in_buf_8_we0_local;

assign in_buf_9_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_9_ce0 = in_buf_9_ce0_local;

assign in_buf_9_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_9_we0 = in_buf_9_we0_local;

assign in_buf_address0 = zext_ln69_2_fu_733_p1;

assign in_buf_ce0 = in_buf_ce0_local;

assign in_buf_d0 = bitcast_ln69_fu_633_p1;

assign in_buf_we0 = in_buf_we0_local;

assign lshr_ln69_1_fu_713_p4 = {{phi_urem_fu_160[5:3]}};

assign m_axi_AXI_IN_0_ARADDR = 64'd0;

assign m_axi_AXI_IN_0_ARBURST = 2'd0;

assign m_axi_AXI_IN_0_ARCACHE = 4'd0;

assign m_axi_AXI_IN_0_ARID = 1'd0;

assign m_axi_AXI_IN_0_ARLEN = 32'd0;

assign m_axi_AXI_IN_0_ARLOCK = 2'd0;

assign m_axi_AXI_IN_0_ARPROT = 3'd0;

assign m_axi_AXI_IN_0_ARQOS = 4'd0;

assign m_axi_AXI_IN_0_ARREGION = 4'd0;

assign m_axi_AXI_IN_0_ARSIZE = 3'd0;

assign m_axi_AXI_IN_0_ARUSER = 1'd0;

assign m_axi_AXI_IN_0_ARVALID = 1'b0;

assign m_axi_AXI_IN_0_AWADDR = 64'd0;

assign m_axi_AXI_IN_0_AWBURST = 2'd0;

assign m_axi_AXI_IN_0_AWCACHE = 4'd0;

assign m_axi_AXI_IN_0_AWID = 1'd0;

assign m_axi_AXI_IN_0_AWLEN = 32'd0;

assign m_axi_AXI_IN_0_AWLOCK = 2'd0;

assign m_axi_AXI_IN_0_AWPROT = 3'd0;

assign m_axi_AXI_IN_0_AWQOS = 4'd0;

assign m_axi_AXI_IN_0_AWREGION = 4'd0;

assign m_axi_AXI_IN_0_AWSIZE = 3'd0;

assign m_axi_AXI_IN_0_AWUSER = 1'd0;

assign m_axi_AXI_IN_0_AWVALID = 1'b0;

assign m_axi_AXI_IN_0_BREADY = 1'b0;

assign m_axi_AXI_IN_0_WDATA = 512'd0;

assign m_axi_AXI_IN_0_WID = 1'd0;

assign m_axi_AXI_IN_0_WLAST = 1'b0;

assign m_axi_AXI_IN_0_WSTRB = 64'd0;

assign m_axi_AXI_IN_0_WUSER = 1'd0;

assign m_axi_AXI_IN_0_WVALID = 1'b0;

assign p_shl_fu_687_p3 = {{tmp_fu_677_p4}, {3'd0}};

assign select_ln67_fu_776_p3 = ((icmp_ln67_1_fu_770_p2[0:0] == 1'b1) ? 12'd0 : add_ln67_1_fu_764_p2);

assign sub_ln69_fu_707_p2 = (p_shl_fu_687_p3 - zext_ln69_fu_703_p1);

assign tmp_1_fu_695_p3 = {{tmp_fu_677_p4}, {1'd0}};

assign tmp_fu_677_p4 = {{phi_mul49_fu_164[23:20]}};

assign trunc_ln67_fu_556_p1 = i_fu_176[3:0];

assign trunc_ln69_2_fu_569_p1 = i_fu_176[2:0];

assign trunc_ln69_4_fu_611_p1 = grp_fu_589_p2[1:0];

assign trunc_ln69_fu_629_p1 = ap_phi_mux_empty_phi_fu_506_p4[31:0];

assign zext_ln67_fu_618_p1 = shiftreg_fu_172;

assign zext_ln69_1_fu_723_p1 = lshr_ln69_1_fu_713_p4;

assign zext_ln69_2_fu_733_p1 = add_ln69_fu_727_p2;

assign zext_ln69_fu_703_p1 = tmp_1_fu_695_p3;

endmodule //conv1_pool1_conv1_pool1_Pipeline_LOAD
