-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.2 (lin64) Build 5239630 Fri Nov 08 22:34:34 MST 2024
-- Date        : Thu Feb 26 16:48:58 2026
-- Host        : badhak-Precision-7720 running 64-bit Ubuntu 22.04.5 LTS
-- Command     : write_vhdl -force -mode synth_stub
--               /home/badhak/Téléchargements/conv1_pool1_v4/vivado_pynq/pynq_conv1.gen/sources_1/bd/design_1/ip/design_1_conv1_pool1_0_0/design_1_conv1_pool1_0_0_stub.vhdl
-- Design      : design_1_conv1_pool1_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity design_1_conv1_pool1_0_0 is
  Port ( 
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_AXI_IN_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_AXI_IN_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_IN_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_IN_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_AXI_IN_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_AXI_IN_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_IN_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_AXI_IN_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_IN_ARREADY : in STD_LOGIC;
    m_axi_AXI_IN_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_IN_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_AXI_IN_ARVALID : out STD_LOGIC;
    m_axi_AXI_IN_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_AXI_IN_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_IN_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_IN_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_AXI_IN_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_AXI_IN_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_IN_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_AXI_IN_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_IN_AWREADY : in STD_LOGIC;
    m_axi_AXI_IN_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_IN_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_AXI_IN_AWVALID : out STD_LOGIC;
    m_axi_AXI_IN_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_AXI_IN_BREADY : out STD_LOGIC;
    m_axi_AXI_IN_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_IN_BVALID : in STD_LOGIC;
    m_axi_AXI_IN_RDATA : in STD_LOGIC_VECTOR ( 511 downto 0 );
    m_axi_AXI_IN_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_AXI_IN_RLAST : in STD_LOGIC;
    m_axi_AXI_IN_RREADY : out STD_LOGIC;
    m_axi_AXI_IN_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_IN_RVALID : in STD_LOGIC;
    m_axi_AXI_IN_WDATA : out STD_LOGIC_VECTOR ( 511 downto 0 );
    m_axi_AXI_IN_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_AXI_IN_WLAST : out STD_LOGIC;
    m_axi_AXI_IN_WREADY : in STD_LOGIC;
    m_axi_AXI_IN_WSTRB : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_AXI_IN_WVALID : out STD_LOGIC;
    m_axi_AXI_OUT_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_AXI_OUT_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_OUT_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_OUT_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_AXI_OUT_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_AXI_OUT_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_OUT_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_AXI_OUT_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_OUT_ARREADY : in STD_LOGIC;
    m_axi_AXI_OUT_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_OUT_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_AXI_OUT_ARVALID : out STD_LOGIC;
    m_axi_AXI_OUT_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_AXI_OUT_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_OUT_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_OUT_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_AXI_OUT_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_AXI_OUT_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_OUT_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_AXI_OUT_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_OUT_AWREADY : in STD_LOGIC;
    m_axi_AXI_OUT_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_OUT_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_AXI_OUT_AWVALID : out STD_LOGIC;
    m_axi_AXI_OUT_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_AXI_OUT_BREADY : out STD_LOGIC;
    m_axi_AXI_OUT_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_OUT_BVALID : in STD_LOGIC;
    m_axi_AXI_OUT_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_AXI_OUT_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_AXI_OUT_RLAST : in STD_LOGIC;
    m_axi_AXI_OUT_RREADY : out STD_LOGIC;
    m_axi_AXI_OUT_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_AXI_OUT_RVALID : in STD_LOGIC;
    m_axi_AXI_OUT_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_AXI_OUT_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_AXI_OUT_WLAST : out STD_LOGIC;
    m_axi_AXI_OUT_WREADY : in STD_LOGIC;
    m_axi_AXI_OUT_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_AXI_OUT_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of design_1_conv1_pool1_0_0 : entity is "design_1_conv1_pool1_0_0,conv1_pool1,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of design_1_conv1_pool1_0_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of design_1_conv1_pool1_0_0 : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of design_1_conv1_pool1_0_0 : entity is "yes";
end design_1_conv1_pool1_0_0;

architecture stub of design_1_conv1_pool1_0_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_control_ARADDR[5:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[5:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_AXI_IN_ARADDR[63:0],m_axi_AXI_IN_ARBURST[1:0],m_axi_AXI_IN_ARCACHE[3:0],m_axi_AXI_IN_ARID[0:0],m_axi_AXI_IN_ARLEN[7:0],m_axi_AXI_IN_ARLOCK[1:0],m_axi_AXI_IN_ARPROT[2:0],m_axi_AXI_IN_ARQOS[3:0],m_axi_AXI_IN_ARREADY,m_axi_AXI_IN_ARREGION[3:0],m_axi_AXI_IN_ARSIZE[2:0],m_axi_AXI_IN_ARVALID,m_axi_AXI_IN_AWADDR[63:0],m_axi_AXI_IN_AWBURST[1:0],m_axi_AXI_IN_AWCACHE[3:0],m_axi_AXI_IN_AWID[0:0],m_axi_AXI_IN_AWLEN[7:0],m_axi_AXI_IN_AWLOCK[1:0],m_axi_AXI_IN_AWPROT[2:0],m_axi_AXI_IN_AWQOS[3:0],m_axi_AXI_IN_AWREADY,m_axi_AXI_IN_AWREGION[3:0],m_axi_AXI_IN_AWSIZE[2:0],m_axi_AXI_IN_AWVALID,m_axi_AXI_IN_BID[0:0],m_axi_AXI_IN_BREADY,m_axi_AXI_IN_BRESP[1:0],m_axi_AXI_IN_BVALID,m_axi_AXI_IN_RDATA[511:0],m_axi_AXI_IN_RID[0:0],m_axi_AXI_IN_RLAST,m_axi_AXI_IN_RREADY,m_axi_AXI_IN_RRESP[1:0],m_axi_AXI_IN_RVALID,m_axi_AXI_IN_WDATA[511:0],m_axi_AXI_IN_WID[0:0],m_axi_AXI_IN_WLAST,m_axi_AXI_IN_WREADY,m_axi_AXI_IN_WSTRB[63:0],m_axi_AXI_IN_WVALID,m_axi_AXI_OUT_ARADDR[63:0],m_axi_AXI_OUT_ARBURST[1:0],m_axi_AXI_OUT_ARCACHE[3:0],m_axi_AXI_OUT_ARID[0:0],m_axi_AXI_OUT_ARLEN[7:0],m_axi_AXI_OUT_ARLOCK[1:0],m_axi_AXI_OUT_ARPROT[2:0],m_axi_AXI_OUT_ARQOS[3:0],m_axi_AXI_OUT_ARREADY,m_axi_AXI_OUT_ARREGION[3:0],m_axi_AXI_OUT_ARSIZE[2:0],m_axi_AXI_OUT_ARVALID,m_axi_AXI_OUT_AWADDR[63:0],m_axi_AXI_OUT_AWBURST[1:0],m_axi_AXI_OUT_AWCACHE[3:0],m_axi_AXI_OUT_AWID[0:0],m_axi_AXI_OUT_AWLEN[7:0],m_axi_AXI_OUT_AWLOCK[1:0],m_axi_AXI_OUT_AWPROT[2:0],m_axi_AXI_OUT_AWQOS[3:0],m_axi_AXI_OUT_AWREADY,m_axi_AXI_OUT_AWREGION[3:0],m_axi_AXI_OUT_AWSIZE[2:0],m_axi_AXI_OUT_AWVALID,m_axi_AXI_OUT_BID[0:0],m_axi_AXI_OUT_BREADY,m_axi_AXI_OUT_BRESP[1:0],m_axi_AXI_OUT_BVALID,m_axi_AXI_OUT_RDATA[31:0],m_axi_AXI_OUT_RID[0:0],m_axi_AXI_OUT_RLAST,m_axi_AXI_OUT_RREADY,m_axi_AXI_OUT_RRESP[1:0],m_axi_AXI_OUT_RVALID,m_axi_AXI_OUT_WDATA[31:0],m_axi_AXI_OUT_WID[0:0],m_axi_AXI_OUT_WLAST,m_axi_AXI_OUT_WREADY,m_axi_AXI_OUT_WSTRB[3:0],m_axi_AXI_OUT_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 4, NUM_WRITE_THREADS 4, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_control:m_axi_AXI_IN:m_axi_AXI_OUT, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARADDR";
  attribute X_INTERFACE_MODE of m_axi_AXI_IN_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_AXI_IN_ARADDR : signal is "XIL_INTERFACENAME m_axi_AXI_IN, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 512, FREQ_HZ 100000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARBURST";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARID";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARLEN";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARPROT";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARQOS";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARREADY";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARREGION";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN ARVALID";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWADDR";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWBURST";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWID";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWLEN";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWPROT";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWQOS";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWREADY";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWREGION";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN AWVALID";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN BID";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN BREADY";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN BRESP";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN BVALID";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN RDATA";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN RID";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN RLAST";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN RREADY";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN RRESP";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN RVALID";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN WDATA";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN WID";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN WLAST";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN WREADY";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN WSTRB";
  attribute X_INTERFACE_INFO of m_axi_AXI_IN_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_IN WVALID";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARADDR";
  attribute X_INTERFACE_MODE of m_axi_AXI_OUT_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_AXI_OUT_ARADDR : signal is "XIL_INTERFACENAME m_axi_AXI_OUT, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARBURST";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARID";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARLEN";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARPROT";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARQOS";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARREADY";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARREGION";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT ARVALID";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWADDR";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWBURST";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWID";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWLEN";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWPROT";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWQOS";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWREADY";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWREGION";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT AWVALID";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT BID";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT BREADY";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT BRESP";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT BVALID";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT RDATA";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT RID";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT RLAST";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT RREADY";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT RRESP";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT RVALID";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT WDATA";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT WID";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT WLAST";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT WREADY";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT WSTRB";
  attribute X_INTERFACE_INFO of m_axi_AXI_OUT_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_AXI_OUT WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "conv1_pool1,Vivado 2024.2";
begin
end;
