-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv1_pool1_conv1_pool1_Pipeline_LOAD is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_AXI_IN_0_AWVALID : OUT STD_LOGIC;
    m_axi_AXI_IN_0_AWREADY : IN STD_LOGIC;
    m_axi_AXI_IN_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_IN_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AXI_IN_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_IN_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_IN_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_WVALID : OUT STD_LOGIC;
    m_axi_AXI_IN_0_WREADY : IN STD_LOGIC;
    m_axi_AXI_IN_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_AXI_IN_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_IN_0_WLAST : OUT STD_LOGIC;
    m_axi_AXI_IN_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_ARVALID : OUT STD_LOGIC;
    m_axi_AXI_IN_0_ARREADY : IN STD_LOGIC;
    m_axi_AXI_IN_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_IN_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AXI_IN_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_IN_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_IN_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_RVALID : IN STD_LOGIC;
    m_axi_AXI_IN_0_RREADY : OUT STD_LOGIC;
    m_axi_AXI_IN_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_AXI_IN_0_RLAST : IN STD_LOGIC;
    m_axi_AXI_IN_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_AXI_IN_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_BVALID : IN STD_LOGIC;
    m_axi_AXI_IN_0_BREADY : OUT STD_LOGIC;
    m_axi_AXI_IN_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_buf_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_ce0 : OUT STD_LOGIC;
    in_buf_we0 : OUT STD_LOGIC;
    in_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_1_ce0 : OUT STD_LOGIC;
    in_buf_1_we0 : OUT STD_LOGIC;
    in_buf_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_2_ce0 : OUT STD_LOGIC;
    in_buf_2_we0 : OUT STD_LOGIC;
    in_buf_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_3_ce0 : OUT STD_LOGIC;
    in_buf_3_we0 : OUT STD_LOGIC;
    in_buf_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_4_ce0 : OUT STD_LOGIC;
    in_buf_4_we0 : OUT STD_LOGIC;
    in_buf_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_5_ce0 : OUT STD_LOGIC;
    in_buf_5_we0 : OUT STD_LOGIC;
    in_buf_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_6_ce0 : OUT STD_LOGIC;
    in_buf_6_we0 : OUT STD_LOGIC;
    in_buf_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_7_ce0 : OUT STD_LOGIC;
    in_buf_7_we0 : OUT STD_LOGIC;
    in_buf_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_8_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_8_ce0 : OUT STD_LOGIC;
    in_buf_8_we0 : OUT STD_LOGIC;
    in_buf_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_9_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_9_ce0 : OUT STD_LOGIC;
    in_buf_9_we0 : OUT STD_LOGIC;
    in_buf_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_10_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_10_ce0 : OUT STD_LOGIC;
    in_buf_10_we0 : OUT STD_LOGIC;
    in_buf_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_11_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_11_ce0 : OUT STD_LOGIC;
    in_buf_11_we0 : OUT STD_LOGIC;
    in_buf_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_12_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_12_ce0 : OUT STD_LOGIC;
    in_buf_12_we0 : OUT STD_LOGIC;
    in_buf_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_13_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_13_ce0 : OUT STD_LOGIC;
    in_buf_13_we0 : OUT STD_LOGIC;
    in_buf_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_14_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_14_ce0 : OUT STD_LOGIC;
    in_buf_14_we0 : OUT STD_LOGIC;
    in_buf_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_15_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_15_ce0 : OUT STD_LOGIC;
    in_buf_15_we0 : OUT STD_LOGIC;
    in_buf_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_16_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_16_ce0 : OUT STD_LOGIC;
    in_buf_16_we0 : OUT STD_LOGIC;
    in_buf_16_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_17_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_17_ce0 : OUT STD_LOGIC;
    in_buf_17_we0 : OUT STD_LOGIC;
    in_buf_17_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_18_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_18_ce0 : OUT STD_LOGIC;
    in_buf_18_we0 : OUT STD_LOGIC;
    in_buf_18_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_19_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_19_ce0 : OUT STD_LOGIC;
    in_buf_19_we0 : OUT STD_LOGIC;
    in_buf_19_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_20_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_20_ce0 : OUT STD_LOGIC;
    in_buf_20_we0 : OUT STD_LOGIC;
    in_buf_20_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_21_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_21_ce0 : OUT STD_LOGIC;
    in_buf_21_we0 : OUT STD_LOGIC;
    in_buf_21_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_22_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_22_ce0 : OUT STD_LOGIC;
    in_buf_22_we0 : OUT STD_LOGIC;
    in_buf_22_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_23_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_23_ce0 : OUT STD_LOGIC;
    in_buf_23_we0 : OUT STD_LOGIC;
    in_buf_23_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    sext_ln67 : IN STD_LOGIC_VECTOR (57 downto 0) );
end;


architecture behav of conv1_pool1_conv1_pool1_Pipeline_LOAD is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv480_lc_1 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv12_900 : STD_LOGIC_VECTOR (11 downto 0) := "100100000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv24_1556 : STD_LOGIC_VECTOR (23 downto 0) := "000000000001010101010110";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv25_1C72 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001110001110010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv12_2F : STD_LOGIC_VECTOR (11 downto 0) := "000000101111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln67_reg_840 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_reg_840_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_844 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_844_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op60_read_state11 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln67_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal AXI_IN_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln67_reg_840_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_reg_840_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_reg_840_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_reg_840_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_reg_840_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_reg_840_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_reg_840_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_reg_840_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_844_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_844_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_844_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_844_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_844_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_844_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_844_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_844_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln69_2_fu_569_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln69_2_reg_848 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln69_2_reg_848_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln69_2_reg_848_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln69_2_reg_848_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln69_2_reg_848_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln69_2_reg_848_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln69_2_reg_848_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln69_2_reg_848_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln69_2_reg_848_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln69_2_reg_848_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal AXI_IN_addr_read_reg_857 : STD_LOGIC_VECTOR (511 downto 0);
    signal trunc_ln69_4_fu_611_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_4_reg_862 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_empty_phi_fu_506_p4 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter11_empty_reg_503 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln67_fu_618_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln69_2_fu_733_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_urem_fu_160 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal select_ln67_fu_776_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal phi_mul49_fu_164 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    signal add_ln69_2_fu_671_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal phi_mul_fu_168 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal add_ln69_1_fu_573_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal shiftreg_fu_172 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal i_fu_176 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln67_fu_550_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal in_buf_19_we0_local : STD_LOGIC;
    signal bitcast_ln69_fu_633_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_buf_19_ce0_local : STD_LOGIC;
    signal in_buf_18_we0_local : STD_LOGIC;
    signal in_buf_18_ce0_local : STD_LOGIC;
    signal in_buf_20_we0_local : STD_LOGIC;
    signal in_buf_20_ce0_local : STD_LOGIC;
    signal in_buf_16_we0_local : STD_LOGIC;
    signal in_buf_16_ce0_local : STD_LOGIC;
    signal in_buf_15_we0_local : STD_LOGIC;
    signal in_buf_15_ce0_local : STD_LOGIC;
    signal in_buf_17_we0_local : STD_LOGIC;
    signal in_buf_17_ce0_local : STD_LOGIC;
    signal in_buf_13_we0_local : STD_LOGIC;
    signal in_buf_13_ce0_local : STD_LOGIC;
    signal in_buf_12_we0_local : STD_LOGIC;
    signal in_buf_12_ce0_local : STD_LOGIC;
    signal in_buf_14_we0_local : STD_LOGIC;
    signal in_buf_14_ce0_local : STD_LOGIC;
    signal in_buf_10_we0_local : STD_LOGIC;
    signal in_buf_10_ce0_local : STD_LOGIC;
    signal in_buf_9_we0_local : STD_LOGIC;
    signal in_buf_9_ce0_local : STD_LOGIC;
    signal in_buf_11_we0_local : STD_LOGIC;
    signal in_buf_11_ce0_local : STD_LOGIC;
    signal in_buf_7_we0_local : STD_LOGIC;
    signal in_buf_7_ce0_local : STD_LOGIC;
    signal in_buf_6_we0_local : STD_LOGIC;
    signal in_buf_6_ce0_local : STD_LOGIC;
    signal in_buf_8_we0_local : STD_LOGIC;
    signal in_buf_8_ce0_local : STD_LOGIC;
    signal in_buf_4_we0_local : STD_LOGIC;
    signal in_buf_4_ce0_local : STD_LOGIC;
    signal in_buf_3_we0_local : STD_LOGIC;
    signal in_buf_3_ce0_local : STD_LOGIC;
    signal in_buf_5_we0_local : STD_LOGIC;
    signal in_buf_5_ce0_local : STD_LOGIC;
    signal in_buf_1_we0_local : STD_LOGIC;
    signal in_buf_1_ce0_local : STD_LOGIC;
    signal in_buf_we0_local : STD_LOGIC;
    signal in_buf_ce0_local : STD_LOGIC;
    signal in_buf_2_we0_local : STD_LOGIC;
    signal in_buf_2_ce0_local : STD_LOGIC;
    signal in_buf_22_we0_local : STD_LOGIC;
    signal in_buf_22_ce0_local : STD_LOGIC;
    signal in_buf_21_we0_local : STD_LOGIC;
    signal in_buf_21_ce0_local : STD_LOGIC;
    signal in_buf_23_we0_local : STD_LOGIC;
    signal in_buf_23_ce0_local : STD_LOGIC;
    signal trunc_ln67_fu_556_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_589_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_589_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_589_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_fu_629_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_677_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_695_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl_fu_687_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln69_fu_703_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln69_1_fu_713_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln69_fu_707_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln69_1_fu_723_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln69_fu_727_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln67_1_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln67_1_fu_764_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_589_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv1_pool1_urem_6ns_3ns_2_10_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component conv1_pool1_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_6ns_3ns_2_10_1_U1 : component conv1_pool1_urem_6ns_3ns_2_10_1
    generic map (
        ID => 1,
        NUM_STAGE => 10,
        din0_WIDTH => 6,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_589_p0,
        din1 => grp_fu_589_p1,
        ce => grp_fu_589_ce,
        dout => grp_fu_589_p2);

    flow_control_loop_pipe_sequential_init_U : component conv1_pool1_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_176 <= ap_const_lv12_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln67_fu_544_p2 = ap_const_lv1_0))) then 
                    i_fu_176 <= add_ln67_fu_550_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_mul49_fu_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    phi_mul49_fu_164 <= ap_const_lv25_0;
                elsif ((ap_enable_reg_pp0_iter11 = ap_const_logic_1)) then 
                    phi_mul49_fu_164 <= add_ln69_2_fu_671_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_mul_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul_fu_168 <= ap_const_lv24_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln67_fu_544_p2 = ap_const_lv1_0))) then 
                    phi_mul_fu_168 <= add_ln69_1_fu_573_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    phi_urem_fu_160 <= ap_const_lv12_0;
                elsif ((ap_enable_reg_pp0_iter11 = ap_const_logic_1)) then 
                    phi_urem_fu_160 <= select_ln67_fu_776_p3;
                end if;
            end if; 
        end if;
    end process;

    shiftreg_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    shiftreg_fu_172 <= ap_const_lv480_lc_1;
                elsif ((ap_enable_reg_pp0_iter11 = ap_const_logic_1)) then 
                    shiftreg_fu_172 <= ap_phi_mux_empty_phi_fu_506_p4(511 downto 32);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                AXI_IN_addr_read_reg_857 <= m_axi_AXI_IN_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln67_reg_840_pp0_iter10_reg <= icmp_ln67_reg_840_pp0_iter9_reg;
                icmp_ln67_reg_840_pp0_iter2_reg <= icmp_ln67_reg_840;
                icmp_ln67_reg_840_pp0_iter3_reg <= icmp_ln67_reg_840_pp0_iter2_reg;
                icmp_ln67_reg_840_pp0_iter4_reg <= icmp_ln67_reg_840_pp0_iter3_reg;
                icmp_ln67_reg_840_pp0_iter5_reg <= icmp_ln67_reg_840_pp0_iter4_reg;
                icmp_ln67_reg_840_pp0_iter6_reg <= icmp_ln67_reg_840_pp0_iter5_reg;
                icmp_ln67_reg_840_pp0_iter7_reg <= icmp_ln67_reg_840_pp0_iter6_reg;
                icmp_ln67_reg_840_pp0_iter8_reg <= icmp_ln67_reg_840_pp0_iter7_reg;
                icmp_ln67_reg_840_pp0_iter9_reg <= icmp_ln67_reg_840_pp0_iter8_reg;
                icmp_ln69_reg_844_pp0_iter10_reg <= icmp_ln69_reg_844_pp0_iter9_reg;
                icmp_ln69_reg_844_pp0_iter2_reg <= icmp_ln69_reg_844;
                icmp_ln69_reg_844_pp0_iter3_reg <= icmp_ln69_reg_844_pp0_iter2_reg;
                icmp_ln69_reg_844_pp0_iter4_reg <= icmp_ln69_reg_844_pp0_iter3_reg;
                icmp_ln69_reg_844_pp0_iter5_reg <= icmp_ln69_reg_844_pp0_iter4_reg;
                icmp_ln69_reg_844_pp0_iter6_reg <= icmp_ln69_reg_844_pp0_iter5_reg;
                icmp_ln69_reg_844_pp0_iter7_reg <= icmp_ln69_reg_844_pp0_iter6_reg;
                icmp_ln69_reg_844_pp0_iter8_reg <= icmp_ln69_reg_844_pp0_iter7_reg;
                icmp_ln69_reg_844_pp0_iter9_reg <= icmp_ln69_reg_844_pp0_iter8_reg;
                trunc_ln69_2_reg_848_pp0_iter10_reg <= trunc_ln69_2_reg_848_pp0_iter9_reg;
                trunc_ln69_2_reg_848_pp0_iter2_reg <= trunc_ln69_2_reg_848;
                trunc_ln69_2_reg_848_pp0_iter3_reg <= trunc_ln69_2_reg_848_pp0_iter2_reg;
                trunc_ln69_2_reg_848_pp0_iter4_reg <= trunc_ln69_2_reg_848_pp0_iter3_reg;
                trunc_ln69_2_reg_848_pp0_iter5_reg <= trunc_ln69_2_reg_848_pp0_iter4_reg;
                trunc_ln69_2_reg_848_pp0_iter6_reg <= trunc_ln69_2_reg_848_pp0_iter5_reg;
                trunc_ln69_2_reg_848_pp0_iter7_reg <= trunc_ln69_2_reg_848_pp0_iter6_reg;
                trunc_ln69_2_reg_848_pp0_iter8_reg <= trunc_ln69_2_reg_848_pp0_iter7_reg;
                trunc_ln69_2_reg_848_pp0_iter9_reg <= trunc_ln69_2_reg_848_pp0_iter8_reg;
                trunc_ln69_4_reg_862 <= trunc_ln69_4_fu_611_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln67_reg_840 <= icmp_ln67_fu_544_p2;
                icmp_ln69_reg_844 <= icmp_ln69_fu_560_p2;
                trunc_ln69_2_reg_848 <= trunc_ln69_2_fu_569_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    AXI_IN_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter10, m_axi_AXI_IN_0_RVALID, ap_predicate_op60_read_state11, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op60_read_state11 = ap_const_boolean_1))) then 
            AXI_IN_blk_n_R <= m_axi_AXI_IN_0_RVALID;
        else 
            AXI_IN_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    add_ln67_1_fu_764_p2 <= std_logic_vector(unsigned(phi_urem_fu_160) + unsigned(ap_const_lv12_1));
    add_ln67_fu_550_p2 <= std_logic_vector(unsigned(i_fu_176) + unsigned(ap_const_lv12_1));
    add_ln69_1_fu_573_p2 <= std_logic_vector(unsigned(phi_mul_fu_168) + unsigned(ap_const_lv24_1556));
    add_ln69_2_fu_671_p2 <= std_logic_vector(unsigned(phi_mul49_fu_164) + unsigned(ap_const_lv25_1C72));
    add_ln69_fu_727_p2 <= std_logic_vector(unsigned(sub_ln69_fu_707_p2) + unsigned(zext_ln69_1_fu_723_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_state11_pp0_stage0_iter10_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_state11_pp0_stage0_iter10_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_state11_pp0_stage0_iter10_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state11_pp0_stage0_iter10_grp1_assign_proc : process(m_axi_AXI_IN_0_RVALID, ap_predicate_op60_read_state11)
    begin
                ap_block_state11_pp0_stage0_iter10_grp1 <= ((m_axi_AXI_IN_0_RVALID = ap_const_logic_0) and (ap_predicate_op60_read_state11 = ap_const_boolean_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln67_fu_544_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln67_fu_544_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_empty_phi_fu_506_p4_assign_proc : process(icmp_ln67_reg_840_pp0_iter10_reg, icmp_ln69_reg_844_pp0_iter10_reg, AXI_IN_addr_read_reg_857, ap_phi_reg_pp0_iter11_empty_reg_503, zext_ln67_fu_618_p1)
    begin
        if ((icmp_ln67_reg_840_pp0_iter10_reg = ap_const_lv1_0)) then
            if ((icmp_ln69_reg_844_pp0_iter10_reg = ap_const_lv1_0)) then 
                ap_phi_mux_empty_phi_fu_506_p4 <= zext_ln67_fu_618_p1;
            elsif ((icmp_ln69_reg_844_pp0_iter10_reg = ap_const_lv1_1)) then 
                ap_phi_mux_empty_phi_fu_506_p4 <= AXI_IN_addr_read_reg_857;
            else 
                ap_phi_mux_empty_phi_fu_506_p4 <= ap_phi_reg_pp0_iter11_empty_reg_503;
            end if;
        else 
            ap_phi_mux_empty_phi_fu_506_p4 <= ap_phi_reg_pp0_iter11_empty_reg_503;
        end if; 
    end process;

    ap_phi_reg_pp0_iter11_empty_reg_503 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op60_read_state11_assign_proc : process(icmp_ln67_reg_840_pp0_iter9_reg, icmp_ln69_reg_844_pp0_iter9_reg)
    begin
                ap_predicate_op60_read_state11 <= ((icmp_ln69_reg_844_pp0_iter9_reg = ap_const_lv1_1) and (icmp_ln67_reg_840_pp0_iter9_reg = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln69_fu_633_p1 <= trunc_ln69_fu_629_p1;

    grp_fu_589_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_589_ce <= ap_const_logic_1;
        else 
            grp_fu_589_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_589_p0 <= phi_mul_fu_168(23 downto 18);
    grp_fu_589_p1 <= ap_const_lv6_3(3 - 1 downto 0);
    icmp_ln67_1_fu_770_p2 <= "1" when (phi_urem_fu_160 = ap_const_lv12_2F) else "0";
    icmp_ln67_fu_544_p2 <= "1" when (i_fu_176 = ap_const_lv12_900) else "0";
    icmp_ln69_fu_560_p2 <= "1" when (trunc_ln67_fu_556_p1 = ap_const_lv4_0) else "0";
    in_buf_10_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_10_ce0 <= in_buf_10_ce0_local;

    in_buf_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_10_ce0_local <= ap_const_logic_1;
        else 
            in_buf_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_10_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_10_we0 <= in_buf_10_we0_local;

    in_buf_10_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_10_we0_local <= ap_const_logic_1;
        else 
            in_buf_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_11_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_11_ce0 <= in_buf_11_ce0_local;

    in_buf_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_11_ce0_local <= ap_const_logic_1;
        else 
            in_buf_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_11_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_11_we0 <= in_buf_11_we0_local;

    in_buf_11_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if ((not((trunc_ln69_4_reg_862 = ap_const_lv2_0)) and not((trunc_ln69_4_reg_862 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_11_we0_local <= ap_const_logic_1;
        else 
            in_buf_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_12_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_12_ce0 <= in_buf_12_ce0_local;

    in_buf_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_12_ce0_local <= ap_const_logic_1;
        else 
            in_buf_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_12_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_12_we0 <= in_buf_12_we0_local;

    in_buf_12_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_0) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_4) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_12_we0_local <= ap_const_logic_1;
        else 
            in_buf_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_13_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_13_ce0 <= in_buf_13_ce0_local;

    in_buf_13_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_13_ce0_local <= ap_const_logic_1;
        else 
            in_buf_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_13_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_13_we0 <= in_buf_13_we0_local;

    in_buf_13_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_4) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_13_we0_local <= ap_const_logic_1;
        else 
            in_buf_13_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_14_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_14_ce0 <= in_buf_14_ce0_local;

    in_buf_14_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_14_ce0_local <= ap_const_logic_1;
        else 
            in_buf_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_14_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_14_we0 <= in_buf_14_we0_local;

    in_buf_14_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if ((not((trunc_ln69_4_reg_862 = ap_const_lv2_0)) and not((trunc_ln69_4_reg_862 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_4) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_14_we0_local <= ap_const_logic_1;
        else 
            in_buf_14_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_15_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_15_ce0 <= in_buf_15_ce0_local;

    in_buf_15_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_15_ce0_local <= ap_const_logic_1;
        else 
            in_buf_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_15_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_15_we0 <= in_buf_15_we0_local;

    in_buf_15_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_0) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_5) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_15_we0_local <= ap_const_logic_1;
        else 
            in_buf_15_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_16_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_16_ce0 <= in_buf_16_ce0_local;

    in_buf_16_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_16_ce0_local <= ap_const_logic_1;
        else 
            in_buf_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_16_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_16_we0 <= in_buf_16_we0_local;

    in_buf_16_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_5) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_16_we0_local <= ap_const_logic_1;
        else 
            in_buf_16_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_17_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_17_ce0 <= in_buf_17_ce0_local;

    in_buf_17_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_17_ce0_local <= ap_const_logic_1;
        else 
            in_buf_17_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_17_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_17_we0 <= in_buf_17_we0_local;

    in_buf_17_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if ((not((trunc_ln69_4_reg_862 = ap_const_lv2_0)) and not((trunc_ln69_4_reg_862 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_5) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_17_we0_local <= ap_const_logic_1;
        else 
            in_buf_17_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_18_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_18_ce0 <= in_buf_18_ce0_local;

    in_buf_18_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_18_ce0_local <= ap_const_logic_1;
        else 
            in_buf_18_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_18_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_18_we0 <= in_buf_18_we0_local;

    in_buf_18_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_0) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_6) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_18_we0_local <= ap_const_logic_1;
        else 
            in_buf_18_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_19_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_19_ce0 <= in_buf_19_ce0_local;

    in_buf_19_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_19_ce0_local <= ap_const_logic_1;
        else 
            in_buf_19_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_19_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_19_we0 <= in_buf_19_we0_local;

    in_buf_19_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_6) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_19_we0_local <= ap_const_logic_1;
        else 
            in_buf_19_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_1_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_1_ce0 <= in_buf_1_ce0_local;

    in_buf_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_1_ce0_local <= ap_const_logic_1;
        else 
            in_buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_1_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_1_we0 <= in_buf_1_we0_local;

    in_buf_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_1_we0_local <= ap_const_logic_1;
        else 
            in_buf_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_20_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_20_ce0 <= in_buf_20_ce0_local;

    in_buf_20_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_20_ce0_local <= ap_const_logic_1;
        else 
            in_buf_20_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_20_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_20_we0 <= in_buf_20_we0_local;

    in_buf_20_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if ((not((trunc_ln69_4_reg_862 = ap_const_lv2_0)) and not((trunc_ln69_4_reg_862 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_6) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_20_we0_local <= ap_const_logic_1;
        else 
            in_buf_20_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_21_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_21_ce0 <= in_buf_21_ce0_local;

    in_buf_21_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_21_ce0_local <= ap_const_logic_1;
        else 
            in_buf_21_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_21_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_21_we0 <= in_buf_21_we0_local;

    in_buf_21_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_0) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_7) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_21_we0_local <= ap_const_logic_1;
        else 
            in_buf_21_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_22_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_22_ce0 <= in_buf_22_ce0_local;

    in_buf_22_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_22_ce0_local <= ap_const_logic_1;
        else 
            in_buf_22_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_22_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_22_we0 <= in_buf_22_we0_local;

    in_buf_22_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_7) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_22_we0_local <= ap_const_logic_1;
        else 
            in_buf_22_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_23_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_23_ce0 <= in_buf_23_ce0_local;

    in_buf_23_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_23_ce0_local <= ap_const_logic_1;
        else 
            in_buf_23_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_23_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_23_we0 <= in_buf_23_we0_local;

    in_buf_23_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if ((not((trunc_ln69_4_reg_862 = ap_const_lv2_0)) and not((trunc_ln69_4_reg_862 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_7) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_23_we0_local <= ap_const_logic_1;
        else 
            in_buf_23_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_2_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_2_ce0 <= in_buf_2_ce0_local;

    in_buf_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_2_ce0_local <= ap_const_logic_1;
        else 
            in_buf_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_2_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_2_we0 <= in_buf_2_we0_local;

    in_buf_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if ((not((trunc_ln69_4_reg_862 = ap_const_lv2_0)) and not((trunc_ln69_4_reg_862 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_2_we0_local <= ap_const_logic_1;
        else 
            in_buf_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_3_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_3_ce0 <= in_buf_3_ce0_local;

    in_buf_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_3_ce0_local <= ap_const_logic_1;
        else 
            in_buf_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_3_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_3_we0 <= in_buf_3_we0_local;

    in_buf_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_0) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_3_we0_local <= ap_const_logic_1;
        else 
            in_buf_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_4_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_4_ce0 <= in_buf_4_ce0_local;

    in_buf_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_4_ce0_local <= ap_const_logic_1;
        else 
            in_buf_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_4_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_4_we0 <= in_buf_4_we0_local;

    in_buf_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_4_we0_local <= ap_const_logic_1;
        else 
            in_buf_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_5_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_5_ce0 <= in_buf_5_ce0_local;

    in_buf_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_5_ce0_local <= ap_const_logic_1;
        else 
            in_buf_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_5_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_5_we0 <= in_buf_5_we0_local;

    in_buf_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if ((not((trunc_ln69_4_reg_862 = ap_const_lv2_0)) and not((trunc_ln69_4_reg_862 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_5_we0_local <= ap_const_logic_1;
        else 
            in_buf_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_6_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_6_ce0 <= in_buf_6_ce0_local;

    in_buf_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_6_ce0_local <= ap_const_logic_1;
        else 
            in_buf_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_6_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_6_we0 <= in_buf_6_we0_local;

    in_buf_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_0) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_6_we0_local <= ap_const_logic_1;
        else 
            in_buf_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_7_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_7_ce0 <= in_buf_7_ce0_local;

    in_buf_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_7_ce0_local <= ap_const_logic_1;
        else 
            in_buf_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_7_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_7_we0 <= in_buf_7_we0_local;

    in_buf_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_7_we0_local <= ap_const_logic_1;
        else 
            in_buf_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_8_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_8_ce0 <= in_buf_8_ce0_local;

    in_buf_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_8_ce0_local <= ap_const_logic_1;
        else 
            in_buf_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_8_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_8_we0 <= in_buf_8_we0_local;

    in_buf_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if ((not((trunc_ln69_4_reg_862 = ap_const_lv2_0)) and not((trunc_ln69_4_reg_862 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_8_we0_local <= ap_const_logic_1;
        else 
            in_buf_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_9_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_9_ce0 <= in_buf_9_ce0_local;

    in_buf_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_9_ce0_local <= ap_const_logic_1;
        else 
            in_buf_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_9_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_9_we0 <= in_buf_9_we0_local;

    in_buf_9_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_0) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_9_we0_local <= ap_const_logic_1;
        else 
            in_buf_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_address0 <= zext_ln69_2_fu_733_p1(7 - 1 downto 0);
    in_buf_ce0 <= in_buf_ce0_local;

    in_buf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_ce0_local <= ap_const_logic_1;
        else 
            in_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_d0 <= bitcast_ln69_fu_633_p1;
    in_buf_we0 <= in_buf_we0_local;

    in_buf_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1, trunc_ln69_2_reg_848_pp0_iter10_reg, trunc_ln69_4_reg_862)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln69_4_reg_862 = ap_const_lv2_0) and (trunc_ln69_2_reg_848_pp0_iter10_reg = ap_const_lv3_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            in_buf_we0_local <= ap_const_logic_1;
        else 
            in_buf_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln69_1_fu_713_p4 <= phi_urem_fu_160(5 downto 3);
    m_axi_AXI_IN_0_ARADDR <= ap_const_lv64_0;
    m_axi_AXI_IN_0_ARBURST <= ap_const_lv2_0;
    m_axi_AXI_IN_0_ARCACHE <= ap_const_lv4_0;
    m_axi_AXI_IN_0_ARID <= ap_const_lv1_0;
    m_axi_AXI_IN_0_ARLEN <= ap_const_lv32_0;
    m_axi_AXI_IN_0_ARLOCK <= ap_const_lv2_0;
    m_axi_AXI_IN_0_ARPROT <= ap_const_lv3_0;
    m_axi_AXI_IN_0_ARQOS <= ap_const_lv4_0;
    m_axi_AXI_IN_0_ARREGION <= ap_const_lv4_0;
    m_axi_AXI_IN_0_ARSIZE <= ap_const_lv3_0;
    m_axi_AXI_IN_0_ARUSER <= ap_const_lv1_0;
    m_axi_AXI_IN_0_ARVALID <= ap_const_logic_0;
    m_axi_AXI_IN_0_AWADDR <= ap_const_lv64_0;
    m_axi_AXI_IN_0_AWBURST <= ap_const_lv2_0;
    m_axi_AXI_IN_0_AWCACHE <= ap_const_lv4_0;
    m_axi_AXI_IN_0_AWID <= ap_const_lv1_0;
    m_axi_AXI_IN_0_AWLEN <= ap_const_lv32_0;
    m_axi_AXI_IN_0_AWLOCK <= ap_const_lv2_0;
    m_axi_AXI_IN_0_AWPROT <= ap_const_lv3_0;
    m_axi_AXI_IN_0_AWQOS <= ap_const_lv4_0;
    m_axi_AXI_IN_0_AWREGION <= ap_const_lv4_0;
    m_axi_AXI_IN_0_AWSIZE <= ap_const_lv3_0;
    m_axi_AXI_IN_0_AWUSER <= ap_const_lv1_0;
    m_axi_AXI_IN_0_AWVALID <= ap_const_logic_0;
    m_axi_AXI_IN_0_BREADY <= ap_const_logic_0;

    m_axi_AXI_IN_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter10, ap_predicate_op60_read_state11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op60_read_state11 = ap_const_boolean_1))) then 
            m_axi_AXI_IN_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_AXI_IN_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_AXI_IN_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_AXI_IN_0_WID <= ap_const_lv1_0;
    m_axi_AXI_IN_0_WLAST <= ap_const_logic_0;
    m_axi_AXI_IN_0_WSTRB <= ap_const_lv64_0;
    m_axi_AXI_IN_0_WUSER <= ap_const_lv1_0;
    m_axi_AXI_IN_0_WVALID <= ap_const_logic_0;
    p_shl_fu_687_p3 <= (tmp_fu_677_p4 & ap_const_lv3_0);
    select_ln67_fu_776_p3 <= 
        ap_const_lv12_0 when (icmp_ln67_1_fu_770_p2(0) = '1') else 
        add_ln67_1_fu_764_p2;
    sub_ln69_fu_707_p2 <= std_logic_vector(unsigned(p_shl_fu_687_p3) - unsigned(zext_ln69_fu_703_p1));
    tmp_1_fu_695_p3 <= (tmp_fu_677_p4 & ap_const_lv1_0);
    tmp_fu_677_p4 <= phi_mul49_fu_164(23 downto 20);
    trunc_ln67_fu_556_p1 <= i_fu_176(4 - 1 downto 0);
    trunc_ln69_2_fu_569_p1 <= i_fu_176(3 - 1 downto 0);
    trunc_ln69_4_fu_611_p1 <= grp_fu_589_p2(2 - 1 downto 0);
    trunc_ln69_fu_629_p1 <= ap_phi_mux_empty_phi_fu_506_p4(32 - 1 downto 0);
    zext_ln67_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shiftreg_fu_172),512));
    zext_ln69_1_fu_723_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln69_1_fu_713_p4),7));
    zext_ln69_2_fu_733_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln69_fu_727_p2),64));
    zext_ln69_fu_703_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_695_p3),7));
end behav;
