-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv3_conv3_Pipeline_LOAD_IC_LOAD_IY is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_AXI_IN_0_AWVALID : OUT STD_LOGIC;
    m_axi_AXI_IN_0_AWREADY : IN STD_LOGIC;
    m_axi_AXI_IN_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_IN_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AXI_IN_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_IN_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_IN_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_WVALID : OUT STD_LOGIC;
    m_axi_AXI_IN_0_WREADY : IN STD_LOGIC;
    m_axi_AXI_IN_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_IN_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_AXI_IN_0_WLAST : OUT STD_LOGIC;
    m_axi_AXI_IN_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_ARVALID : OUT STD_LOGIC;
    m_axi_AXI_IN_0_ARREADY : IN STD_LOGIC;
    m_axi_AXI_IN_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_IN_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AXI_IN_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_IN_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_IN_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_IN_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_RVALID : IN STD_LOGIC;
    m_axi_AXI_IN_0_RREADY : OUT STD_LOGIC;
    m_axi_AXI_IN_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_IN_0_RLAST : IN STD_LOGIC;
    m_axi_AXI_IN_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_AXI_IN_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_BVALID : IN STD_LOGIC;
    m_axi_AXI_IN_0_BREADY : OUT STD_LOGIC;
    m_axi_AXI_IN_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_IN_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_IN_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln28 : IN STD_LOGIC_VECTOR (60 downto 0);
    in_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    in_buf_ce0 : OUT STD_LOGIC;
    in_buf_we0 : OUT STD_LOGIC;
    in_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    in_buf_1_ce0 : OUT STD_LOGIC;
    in_buf_1_we0 : OUT STD_LOGIC;
    in_buf_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_buf_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    in_buf_2_ce0 : OUT STD_LOGIC;
    in_buf_2_we0 : OUT STD_LOGIC;
    in_buf_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of conv3_conv3_Pipeline_LOAD_IC_LOAD_IY is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv9_140 : STD_LOGIC_VECTOR (8 downto 0) := "101000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal icmp_ln28_reg_494 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage1_iter0_grp1 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_state5_pp0_stage4_iter0_grp4 : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal AXI_IN_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage1_grp1 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_grp2 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_grp3 : BOOLEAN;
    signal ap_block_pp0_stage4_grp4 : BOOLEAN;
    signal ap_block_pp0_stage0_grp5 : BOOLEAN;
    signal reg_218 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001_grp1 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp2 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0_grp3 : BOOLEAN;
    signal ap_block_pp0_stage3_11001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage4_11001_grp4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln28_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln34_1_fu_331_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln34_1_reg_503 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal trunc_ln34_fu_337_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln34_reg_511 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln34_2_fu_364_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln34_2_reg_516 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal trunc_ln34_2_fu_379_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln34_2_reg_521 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln34_3_fu_390_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln34_3_reg_526 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal trunc_ln34_4_fu_404_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln34_4_reg_532 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln34_6_fu_417_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln34_6_reg_537 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln34_4_fu_428_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln34_4_reg_542 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln34_8_fu_443_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln34_8_reg_547 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2_grp0 : BOOLEAN;
    signal ap_block_pp0_stage3_grp0 : BOOLEAN;
    signal ap_block_pp0_stage4_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal zext_ln34_5_fu_454_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1_grp0 : BOOLEAN;
    signal iy_fu_90 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln30_fu_341_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ic_fu_94 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln28_1_fu_293_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten_fu_98 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln28_1_fu_250_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal in_buf_we0_local : STD_LOGIC;
    signal in_buf_d0_local : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln34_fu_370_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_buf_ce0_local : STD_LOGIC;
    signal in_buf_address0_local : STD_LOGIC_VECTOR (10 downto 0);
    signal bitcast_ln34_3_fu_399_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln34_6_fu_434_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln34_9_fu_463_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_buf_1_we0_local : STD_LOGIC;
    signal in_buf_1_d0_local : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln34_1_fu_374_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_buf_1_ce0_local : STD_LOGIC;
    signal in_buf_1_address0_local : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage4_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage4_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage4_subdone_grp0 : BOOLEAN;
    signal bitcast_ln34_4_fu_408_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln34_7_fu_438_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_buf_2_we0_local : STD_LOGIC;
    signal in_buf_2_d0_local : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln34_2_fu_395_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_buf_2_ce0_local : STD_LOGIC;
    signal in_buf_2_address0_local : STD_LOGIC_VECTOR (10 downto 0);
    signal bitcast_ln34_5_fu_412_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln34_8_fu_459_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln30_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln28_fu_273_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_309_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_301_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln34_fu_317_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln28_fu_285_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln34_fu_321_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln34_1_fu_327_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_357_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_383_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_6_fu_421_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_fu_447_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv3_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component conv3_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0)) then 
                        ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage4_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage4_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then 
                        ap_block_pp0_stage4_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0)) then 
                        ap_block_pp0_stage4_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ic_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                ic_fu_94 <= ap_const_lv6_0;
            elsif (((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
                ic_fu_94 <= select_ln28_1_fu_293_p3;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln28_fu_244_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_98 <= add_ln28_1_fu_250_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_98 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    iy_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                iy_fu_90 <= ap_const_lv4_0;
            elsif (((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
                iy_fu_90 <= add_ln30_fu_341_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0))) then
                add_ln34_1_reg_503 <= add_ln34_1_fu_331_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln28_reg_494 <= icmp_ln28_fu_244_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp5)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp4) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)))) then
                reg_218 <= m_axi_AXI_IN_0_RDATA(63 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2))) then
                trunc_ln34_2_reg_521 <= trunc_ln34_2_fu_379_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3))) then
                trunc_ln34_4_reg_532 <= trunc_ln34_4_fu_404_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp4))) then
                trunc_ln34_6_reg_537 <= trunc_ln34_6_fu_417_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp5))) then
                trunc_ln34_8_reg_547 <= trunc_ln34_8_fu_443_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1))) then
                trunc_ln34_reg_511 <= trunc_ln34_fu_337_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0))) then
                    zext_ln34_2_reg_516(10 downto 2) <= zext_ln34_2_fu_364_p1(10 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0))) then
                    zext_ln34_3_reg_526(10 downto 2) <= zext_ln34_3_fu_390_p1(10 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                    zext_ln34_4_reg_542(10 downto 2) <= zext_ln34_4_fu_428_p1(10 downto 2);
            end if;
        end if;
    end process;
    zext_ln34_2_reg_516(1 downto 0) <= "00";
    zext_ln34_2_reg_516(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln34_3_reg_526(1 downto 0) <= "01";
    zext_ln34_3_reg_526(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln34_4_reg_542(1 downto 0) <= "10";
    zext_ln34_4_reg_542(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_condition_exit_pp0_iter0_stage1, ap_block_pp0_stage4_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;

    AXI_IN_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, m_axi_AXI_IN_0_RVALID, icmp_ln28_reg_494, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage1_grp1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_grp3, ap_block_pp0_stage4_grp4, ap_block_pp0_stage0_grp5)
    begin
        if ((((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp4) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp5)))) then 
            AXI_IN_blk_n_R <= m_axi_AXI_IN_0_RVALID;
        else 
            AXI_IN_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    add_ln28_1_fu_250_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv9_1));
    add_ln28_fu_273_p2 <= std_logic_vector(unsigned(ic_fu_94) + unsigned(ap_const_lv6_1));
    add_ln30_fu_341_p2 <= std_logic_vector(unsigned(select_ln28_fu_285_p3) + unsigned(ap_const_lv4_1));
    add_ln34_1_fu_331_p2 <= std_logic_vector(unsigned(add_ln34_fu_321_p2) + unsigned(zext_ln34_1_fu_327_p1));
    add_ln34_fu_321_p2 <= std_logic_vector(unsigned(tmp_fu_301_p3) + unsigned(zext_ln34_fu_317_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_AXI_IN_0_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_AXI_IN_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_AXI_IN_0_RVALID)
    begin
                ap_block_pp0_stage0_11001_grp5 <= ((m_axi_AXI_IN_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_AXI_IN_0_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_AXI_IN_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp1_assign_proc : process(ap_block_state2_pp0_stage1_iter0_grp1, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_11001_grp1 <= ((ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_block_state2_pp0_stage1_iter0_grp1, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp2)
    begin
                ap_block_pp0_stage2_11001_grp2 <= ((ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage2_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp2)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage2_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp3)
    begin
                ap_block_pp0_stage3_11001_grp3 <= ((ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage3_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp3)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage3_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp4)
    begin
                ap_block_pp0_stage4_11001_grp4 <= ((ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp4) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage4_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp4)
    begin
                ap_block_pp0_stage4_subdone <= ((ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp4) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage4_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage1_iter0_grp1_assign_proc : process(m_axi_AXI_IN_0_RVALID, icmp_ln28_reg_494)
    begin
                ap_block_state2_pp0_stage1_iter0_grp1 <= ((icmp_ln28_reg_494 = ap_const_lv1_0) and (m_axi_AXI_IN_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage2_iter0_grp2_assign_proc : process(m_axi_AXI_IN_0_RVALID, icmp_ln28_reg_494)
    begin
                ap_block_state3_pp0_stage2_iter0_grp2 <= ((icmp_ln28_reg_494 = ap_const_lv1_0) and (m_axi_AXI_IN_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage3_iter0_grp3_assign_proc : process(m_axi_AXI_IN_0_RVALID, icmp_ln28_reg_494)
    begin
                ap_block_state4_pp0_stage3_iter0_grp3 <= ((icmp_ln28_reg_494 = ap_const_lv1_0) and (m_axi_AXI_IN_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage4_iter0_grp4_assign_proc : process(m_axi_AXI_IN_0_RVALID, icmp_ln28_reg_494)
    begin
                ap_block_state5_pp0_stage4_iter0_grp4 <= ((icmp_ln28_reg_494 = ap_const_lv1_0) and (m_axi_AXI_IN_0_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln28_reg_494, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone)
    begin
        if (((icmp_ln28_reg_494 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_subdone)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten_fu_98, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_98;
        end if; 
    end process;

    bitcast_ln34_1_fu_374_p1 <= reg_218;
    bitcast_ln34_2_fu_395_p1 <= trunc_ln34_2_reg_521;
    bitcast_ln34_3_fu_399_p1 <= reg_218;
    bitcast_ln34_4_fu_408_p1 <= trunc_ln34_4_reg_532;
    bitcast_ln34_5_fu_412_p1 <= reg_218;
    bitcast_ln34_6_fu_434_p1 <= trunc_ln34_6_reg_537;
    bitcast_ln34_7_fu_438_p1 <= reg_218;
    bitcast_ln34_8_fu_459_p1 <= trunc_ln34_8_reg_547;
    bitcast_ln34_9_fu_463_p1 <= reg_218;
    bitcast_ln34_fu_370_p1 <= trunc_ln34_reg_511;
    icmp_ln28_fu_244_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv9_140) else "0";
    icmp_ln30_fu_279_p2 <= "1" when (iy_fu_90 = ap_const_lv4_A) else "0";
    in_buf_1_address0 <= in_buf_1_address0_local;

    in_buf_1_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, zext_ln34_2_fu_364_p1, zext_ln34_3_reg_526, zext_ln34_4_fu_428_p1, ap_block_pp0_stage2_grp0, ap_block_pp0_stage4_grp0, ap_block_pp0_stage0_grp0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp0))) then 
            in_buf_1_address0_local <= zext_ln34_4_fu_428_p1(11 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_1_address0_local <= zext_ln34_3_reg_526(11 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_1_address0_local <= zext_ln34_2_fu_364_p1(11 - 1 downto 0);
        else 
            in_buf_1_address0_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    in_buf_1_ce0 <= in_buf_1_ce0_local;

    in_buf_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg, ap_block_pp0_stage4_11001_grp0, ap_block_pp0_stage4_subdone_grp0_done_reg)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)))) then 
            in_buf_1_ce0_local <= ap_const_logic_1;
        else 
            in_buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_1_d0 <= in_buf_1_d0_local;

    in_buf_1_d0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp0, ap_block_pp0_stage4_grp0, ap_block_pp0_stage0_grp0, bitcast_ln34_1_fu_374_p1, bitcast_ln34_4_fu_408_p1, bitcast_ln34_7_fu_438_p1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp0))) then 
            in_buf_1_d0_local <= bitcast_ln34_7_fu_438_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_1_d0_local <= bitcast_ln34_4_fu_408_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_1_d0_local <= bitcast_ln34_1_fu_374_p1;
        else 
            in_buf_1_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    in_buf_1_we0 <= in_buf_1_we0_local;

    in_buf_1_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln28_reg_494, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg, ap_block_pp0_stage4_11001_grp0, ap_block_pp0_stage4_subdone_grp0_done_reg)
    begin
        if ((((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0)))) then 
            in_buf_1_we0_local <= ap_const_logic_1;
        else 
            in_buf_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_2_address0 <= in_buf_2_address0_local;

    in_buf_2_address0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage3, zext_ln34_2_reg_516, zext_ln34_3_reg_526, zext_ln34_4_reg_542, ap_block_pp0_stage3_grp0, ap_block_pp0_stage4_grp0, ap_block_pp0_stage1_grp0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp0))) then 
            in_buf_2_address0_local <= zext_ln34_4_reg_542(11 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_2_address0_local <= zext_ln34_3_reg_526(11 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_2_address0_local <= zext_ln34_2_reg_516(11 - 1 downto 0);
        else 
            in_buf_2_address0_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    in_buf_2_ce0 <= in_buf_2_ce0_local;

    in_buf_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg, ap_block_pp0_stage3_11001_grp0, ap_block_pp0_stage3_subdone_grp0_done_reg, ap_block_pp0_stage4_11001_grp0, ap_block_pp0_stage4_subdone_grp0_done_reg)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)))) then 
            in_buf_2_ce0_local <= ap_const_logic_1;
        else 
            in_buf_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_2_d0 <= in_buf_2_d0_local;

    in_buf_2_d0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_grp0, ap_block_pp0_stage4_grp0, ap_block_pp0_stage1_grp0, bitcast_ln34_2_fu_395_p1, bitcast_ln34_5_fu_412_p1, bitcast_ln34_8_fu_459_p1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp0))) then 
            in_buf_2_d0_local <= bitcast_ln34_8_fu_459_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_2_d0_local <= bitcast_ln34_5_fu_412_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_2_d0_local <= bitcast_ln34_2_fu_395_p1;
        else 
            in_buf_2_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    in_buf_2_we0 <= in_buf_2_we0_local;

    in_buf_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln28_reg_494, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg, ap_block_pp0_stage3_11001_grp0, ap_block_pp0_stage3_subdone_grp0_done_reg, ap_block_pp0_stage4_11001_grp0, ap_block_pp0_stage4_subdone_grp0_done_reg)
    begin
        if ((((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0)))) then 
            in_buf_2_we0_local <= ap_const_logic_1;
        else 
            in_buf_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_address0 <= in_buf_address0_local;

    in_buf_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, zext_ln34_2_fu_364_p1, zext_ln34_3_fu_390_p1, zext_ln34_4_fu_428_p1, ap_block_pp0_stage2_grp0, ap_block_pp0_stage3_grp0, ap_block_pp0_stage0_grp0, zext_ln34_5_fu_454_p1, ap_block_pp0_stage1_grp0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp0))) then 
            in_buf_address0_local <= zext_ln34_5_fu_454_p1(11 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp0))) then 
            in_buf_address0_local <= zext_ln34_4_fu_428_p1(11 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_address0_local <= zext_ln34_3_fu_390_p1(11 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_address0_local <= zext_ln34_2_fu_364_p1(11 - 1 downto 0);
        else 
            in_buf_address0_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    in_buf_ce0 <= in_buf_ce0_local;

    in_buf_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg, ap_block_pp0_stage3_11001_grp0, ap_block_pp0_stage3_subdone_grp0_done_reg)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)))) then 
            in_buf_ce0_local <= ap_const_logic_1;
        else 
            in_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_d0 <= in_buf_d0_local;

    in_buf_d0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage2_grp0, ap_block_pp0_stage3_grp0, ap_block_pp0_stage0_grp0, ap_block_pp0_stage1_grp0, bitcast_ln34_fu_370_p1, bitcast_ln34_3_fu_399_p1, bitcast_ln34_6_fu_434_p1, bitcast_ln34_9_fu_463_p1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp0))) then 
            in_buf_d0_local <= bitcast_ln34_9_fu_463_p1;
        elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp0))) then 
            in_buf_d0_local <= bitcast_ln34_6_fu_434_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_d0_local <= bitcast_ln34_3_fu_399_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            in_buf_d0_local <= bitcast_ln34_fu_370_p1;
        else 
            in_buf_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    in_buf_we0 <= in_buf_we0_local;

    in_buf_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln28_reg_494, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg, ap_block_pp0_stage3_11001_grp0, ap_block_pp0_stage3_subdone_grp0_done_reg)
    begin
        if ((((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0)))) then 
            in_buf_we0_local <= ap_const_logic_1;
        else 
            in_buf_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_AXI_IN_0_ARADDR <= ap_const_lv64_0;
    m_axi_AXI_IN_0_ARBURST <= ap_const_lv2_0;
    m_axi_AXI_IN_0_ARCACHE <= ap_const_lv4_0;
    m_axi_AXI_IN_0_ARID <= ap_const_lv1_0;
    m_axi_AXI_IN_0_ARLEN <= ap_const_lv32_0;
    m_axi_AXI_IN_0_ARLOCK <= ap_const_lv2_0;
    m_axi_AXI_IN_0_ARPROT <= ap_const_lv3_0;
    m_axi_AXI_IN_0_ARQOS <= ap_const_lv4_0;
    m_axi_AXI_IN_0_ARREGION <= ap_const_lv4_0;
    m_axi_AXI_IN_0_ARSIZE <= ap_const_lv3_0;
    m_axi_AXI_IN_0_ARUSER <= ap_const_lv1_0;
    m_axi_AXI_IN_0_ARVALID <= ap_const_logic_0;
    m_axi_AXI_IN_0_AWADDR <= ap_const_lv64_0;
    m_axi_AXI_IN_0_AWBURST <= ap_const_lv2_0;
    m_axi_AXI_IN_0_AWCACHE <= ap_const_lv4_0;
    m_axi_AXI_IN_0_AWID <= ap_const_lv1_0;
    m_axi_AXI_IN_0_AWLEN <= ap_const_lv32_0;
    m_axi_AXI_IN_0_AWLOCK <= ap_const_lv2_0;
    m_axi_AXI_IN_0_AWPROT <= ap_const_lv3_0;
    m_axi_AXI_IN_0_AWQOS <= ap_const_lv4_0;
    m_axi_AXI_IN_0_AWREGION <= ap_const_lv4_0;
    m_axi_AXI_IN_0_AWSIZE <= ap_const_lv3_0;
    m_axi_AXI_IN_0_AWUSER <= ap_const_lv1_0;
    m_axi_AXI_IN_0_AWVALID <= ap_const_logic_0;
    m_axi_AXI_IN_0_BREADY <= ap_const_logic_0;

    m_axi_AXI_IN_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln28_reg_494, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage1_11001_grp1, ap_block_pp0_stage2_11001_grp2, ap_block_pp0_stage3_11001_grp3, ap_block_pp0_stage4_11001_grp4, ap_block_pp0_stage0_11001_grp5)
    begin
        if ((((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((icmp_ln28_reg_494 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp4) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp5)))) then 
            m_axi_AXI_IN_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_AXI_IN_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_AXI_IN_0_WDATA <= ap_const_lv64_0;
    m_axi_AXI_IN_0_WID <= ap_const_lv1_0;
    m_axi_AXI_IN_0_WLAST <= ap_const_logic_0;
    m_axi_AXI_IN_0_WSTRB <= ap_const_lv8_0;
    m_axi_AXI_IN_0_WUSER <= ap_const_lv1_0;
    m_axi_AXI_IN_0_WVALID <= ap_const_logic_0;
    select_ln28_1_fu_293_p3 <= 
        add_ln28_fu_273_p2 when (icmp_ln30_fu_279_p2(0) = '1') else 
        ic_fu_94;
    select_ln28_fu_285_p3 <= 
        ap_const_lv4_0 when (icmp_ln30_fu_279_p2(0) = '1') else 
        iy_fu_90;
    tmp_1_fu_309_p3 <= (select_ln28_1_fu_293_p3 & ap_const_lv1_0);
    tmp_2_fu_357_p3 <= (add_ln34_1_reg_503 & ap_const_lv2_0);
    tmp_5_fu_383_p3 <= (add_ln34_1_reg_503 & ap_const_lv2_1);
    tmp_6_fu_421_p3 <= (add_ln34_1_reg_503 & ap_const_lv2_2);
    tmp_7_fu_447_p3 <= (add_ln34_1_reg_503 & ap_const_lv2_3);
    tmp_fu_301_p3 <= (select_ln28_1_fu_293_p3 & ap_const_lv3_0);
    trunc_ln34_2_fu_379_p1 <= m_axi_AXI_IN_0_RDATA(32 - 1 downto 0);
    trunc_ln34_4_fu_404_p1 <= m_axi_AXI_IN_0_RDATA(32 - 1 downto 0);
    trunc_ln34_6_fu_417_p1 <= m_axi_AXI_IN_0_RDATA(32 - 1 downto 0);
    trunc_ln34_8_fu_443_p1 <= m_axi_AXI_IN_0_RDATA(32 - 1 downto 0);
    trunc_ln34_fu_337_p1 <= m_axi_AXI_IN_0_RDATA(32 - 1 downto 0);
    zext_ln34_1_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln28_fu_285_p3),9));
    zext_ln34_2_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_357_p3),64));
    zext_ln34_3_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_383_p3),64));
    zext_ln34_4_fu_428_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_421_p3),64));
    zext_ln34_5_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_447_p3),64));
    zext_ln34_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_309_p3),9));
end behav;
