-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv3_conv3_Pipeline_CONV_OC_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_AWVALID : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_AWREADY : IN STD_LOGIC;
    m_axi_AXI_OUT_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_OUT_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AXI_OUT_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_OUT_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_OUT_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_WVALID : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_WREADY : IN STD_LOGIC;
    m_axi_AXI_OUT_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_AXI_OUT_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_OUT_0_WLAST : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_ARVALID : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_ARREADY : IN STD_LOGIC;
    m_axi_AXI_OUT_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_AXI_OUT_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_AXI_OUT_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_OUT_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_AXI_OUT_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_AXI_OUT_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_RVALID : IN STD_LOGIC;
    m_axi_AXI_OUT_0_RREADY : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_AXI_OUT_0_RLAST : IN STD_LOGIC;
    m_axi_AXI_OUT_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_AXI_OUT_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_BVALID : IN STD_LOGIC;
    m_axi_AXI_OUT_0_BREADY : OUT STD_LOGIC;
    m_axi_AXI_OUT_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_AXI_OUT_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_AXI_OUT_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    in_buf_ce0 : OUT STD_LOGIC;
    in_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_buf_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    in_buf_1_ce0 : OUT STD_LOGIC;
    in_buf_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_buf_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    in_buf_2_ce0 : OUT STD_LOGIC;
    in_buf_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln43 : IN STD_LOGIC_VECTOR (57 downto 0) );
end;


architecture behav of conv3_conv3_Pipeline_CONV_OC_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv21_120000 : STD_LOGIC_VECTOR (20 downto 0) := "100100000000000000000";
    constant ap_const_lv21_1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_const_lv16_4800 : STD_LOGIC_VECTOR (15 downto 0) := "0100100000000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv10_120 : STD_LOGIC_VECTOR (9 downto 0) := "0100100000";
    constant ap_const_lv13_900 : STD_LOGIC_VECTOR (12 downto 0) := "0100100000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv9_16 : STD_LOGIC_VECTOR (8 downto 0) := "000010110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv6_1F : STD_LOGIC_VECTOR (5 downto 0) := "011111";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln43_reg_1521 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage3 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal WEIGHTS3_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal WEIGHTS3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal BIASES3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal AXI_OUT_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal icmp_ln54_2_reg_1648 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_2_reg_1648_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_reg_1679 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_reg_1679_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_1683 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_1683_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_1_reg_1652 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_1_reg_1652_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln45_reg_1691 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln45_reg_1691_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_predicate_pred179_state21 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln52_1_reg_1679_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_1683_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op283_write_state21 : BOOLEAN;
    signal ap_block_state21_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal indvar_flatten28_load_reg_1506 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal indvar_flatten49_load_reg_1511 : STD_LOGIC_VECTOR (9 downto 0);
    signal indvar_flatten84_load_reg_1516 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln43_fu_407_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_1521_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_1521_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_1521_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal kx_load_reg_1525 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln45_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_1530 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_1530_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_1530_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_1530_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_1530_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln43_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln43_reg_1543 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_reg_1549 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_1554 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_3_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_3_reg_1559 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_3_reg_1559_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_3_reg_1559_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_3_reg_1559_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_3_reg_1559_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_23_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_23_reg_1571 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_23_reg_1571_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_23_reg_1571_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_23_reg_1571_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_23_reg_1571_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten86_mid2191203_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten86_mid2191203_reg_1579 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten51_mid2131_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten51_mid2131_reg_1585 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten51_mid2131_reg_1585_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten51_mid2131_reg_1585_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten51_mid2131_reg_1585_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten51_mid2131_reg_1585_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_4234_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_4234_reg_1599 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal empty_25_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_25_reg_1604 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_4_mid1_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_4_mid1_reg_1609 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten30_mid283_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten30_mid283_reg_1614 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_27_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_27_reg_1621 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_mid248_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_mid248_reg_1626 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_1_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_1_reg_1632 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln56_3_fu_654_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln56_3_reg_1637 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln56_fu_658_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln56_reg_1642 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln54_2_fu_676_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_2_reg_1648_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_2_reg_1648_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_2_reg_1648_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_1_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_1_reg_1652_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_1_reg_1652_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_1_reg_1652_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln50_fu_837_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln50_reg_1656 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln52_fu_863_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_reg_1663 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln54_1_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_1_reg_1669 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_1674 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln52_1_fu_912_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_reg_1679_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_reg_1679_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_fu_918_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_1683_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_1683_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_3_fu_1013_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_3_reg_1687 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_3_reg_1687_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_3_reg_1687_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln45_fu_1019_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln45_reg_1691_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln45_reg_1691_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_1039_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_1696 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln56_2_fu_1045_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln56_2_reg_1701 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln43_2_fu_1064_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln43_2_reg_1706 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln56_3_fu_1122_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_3_reg_1712 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_5_fu_1131_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln56_5_reg_1717 : STD_LOGIC_VECTOR (10 downto 0);
    signal BIASES3_addr_reg_1722 : STD_LOGIC_VECTOR (5 downto 0);
    signal in_buf_load_reg_1747 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_buf_1_load_reg_1752 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_buf_2_load_reg_1757 : STD_LOGIC_VECTOR (31 downto 0);
    signal WEIGHTS3_load_reg_1762 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_1177_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_reg_1772 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_314_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_reg_1778 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_310_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_reg_1788 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln45_2_fu_1263_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal select_ln45_2_reg_1794 : STD_LOGIC_VECTOR (255 downto 0);
    signal select_ln62_fu_1318_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln62_reg_1799 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln_reg_1805 : STD_LOGIC_VECTOR (223 downto 0);
    signal zext_ln43_fu_1142_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln56_4_fu_1162_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln56_7_fu_1167_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal acc_2_fu_164 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal acc_4_mid271_fu_1208_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_acc_2_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_sig_allocacmp_acc_2_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal kx_fu_168 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln54_fu_670_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal select_ln4516_fu_172 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal select_ln45_fu_1366_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal or_ln6220_fu_176 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal or_ln1_fu_1352_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal ky_fu_180 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal indvar_flatten28_fu_184 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln52_1_fu_693_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ic_fu_188 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal indvar_flatten49_fu_192 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal select_ln50_1_fu_706_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shiftreg_fu_196 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal select_ln47_1_fu_1270_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal ox_fu_200 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln47_fu_579_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten84_fu_204 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal select_ln47_2_fu_719_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal phi_ln45_fu_208 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal oy_fu_212 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln45_1_fu_983_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten132_fu_216 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal select_ln45_3_fu_500_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal oc_fu_220 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal indvar_flatten192_fu_224 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    signal add_ln43_1_fu_413_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal acc10_fu_228 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal in_buf_ce0_local : STD_LOGIC;
    signal in_buf_1_ce0_local : STD_LOGIC;
    signal in_buf_2_ce0_local : STD_LOGIC;
    signal WEIGHTS3_ce0_local : STD_LOGIC;
    signal BIASES3_ce0_local : STD_LOGIC;
    signal icmp_ln50_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten86_not204_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_2_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln45_1_fu_494_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln43_1_fu_527_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ox_mid293_fu_531_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_24_fu_549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln47_fu_543_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond_flatten30_mid2127_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten51_mid2131_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_26_fu_586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten30_mid2127_not_fu_596_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_fu_569_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_mid2123_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_mid279_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten30_mid283_fu_602_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_28_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_29_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_30_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal kx_mid2_fu_641_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_664_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_664_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln52_1_fu_688_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln50_1_fu_701_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln47_1_fu_714_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal first_iter_3236_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_2238_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_2_fu_763_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_3_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_3_mid2117_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_2_mid2121_fu_784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ic_1_mid259_fu_789_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln50_fu_806_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal first_iter_3_mid1_fu_819_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_3_mid273_fu_796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_2_mid277_fu_801_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ky_mid238_fu_812_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln52_fu_844_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal first_iter_2_mid1_fu_850_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_2_mid246_fu_832_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_2_mid2_fu_856_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln54_fu_870_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_3_mid2_fu_825_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_fu_876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln54_1_fu_881_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln56_fu_896_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln56_fu_896_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln56_fu_896_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal first_iter_5231_fu_944_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_fu_937_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln45_fu_959_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal first_iter_5_mid1_fu_965_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_fu_950_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_1_fu_955_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_4_mid2113_fu_978_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_4_mid2_fu_990_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln54_2_fu_996_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_5_mid2_fu_971_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_2_fu_1002_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln54_3_fu_1007_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_shl_fu_1026_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln56_1_fu_1023_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln56_fu_1033_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln43_fu_1058_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_4_fu_1081_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_3_fu_1074_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln52_fu_1088_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln52_2_fu_1092_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_2_fu_1098_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln56_1_fu_1101_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_6_fu_1115_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln56_fu_1071_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_5_fu_1107_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln56_6_fu_1128_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_fu_1149_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln43_4_cast_fu_1146_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln56_4_fu_1156_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_664_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_1177_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_1177_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal acc_4_mid2111_fu_1201_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_1_fu_1249_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal shiftreg_mid294_fu_1256_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal bitcast_ln60_fu_1277_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_1280_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln60_fu_1290_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln60_1_fu_1300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_fu_1294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln60_fu_1306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln60_fu_1312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal grp_fu_310_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal grp_fu_314_ce : STD_LOGIC;
    signal grp_fu_318_ce : STD_LOGIC;
    signal ap_block_pp0_stage2_00001 : BOOLEAN;
    signal grp_fu_664_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter4_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0_1to5 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln56_fu_896_p00 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_1177_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_1177_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_1177_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv3_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv3_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv3_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv3_urem_4ns_3ns_2_8_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component conv3_mul_4ns_6ns_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component conv3_sparsemux_7_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv3_conv3_Pipeline_CONV_OC_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_WEIGHTS3_ROM_Abkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv3_conv3_Pipeline_CONV_OC_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_BIASES3_ROM_AUcud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv3_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    WEIGHTS3_U : component conv3_conv3_Pipeline_CONV_OC_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_WEIGHTS3_ROM_Abkb
    generic map (
        DataWidth => 32,
        AddressRange => 18432,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => WEIGHTS3_address0,
        ce0 => WEIGHTS3_ce0_local,
        q0 => WEIGHTS3_q0);

    BIASES3_U : component conv3_conv3_Pipeline_CONV_OC_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_BIASES3_ROM_AUcud
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => BIASES3_addr_reg_1722,
        ce0 => BIASES3_ce0_local,
        q0 => BIASES3_q0);

    fadd_32ns_32ns_32_5_full_dsp_1_U6 : component conv3_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_sig_allocacmp_acc_2_load_1,
        din1 => mul_reg_1778,
        ce => grp_fu_310_ce,
        dout => grp_fu_310_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U7 : component conv3_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_fu_1177_p9,
        din1 => WEIGHTS3_load_reg_1762,
        ce => grp_fu_314_ce,
        dout => grp_fu_314_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U8 : component conv3_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => acc_1_reg_1788,
        din1 => ap_const_lv32_0,
        ce => grp_fu_318_ce,
        opcode => ap_const_lv5_2,
        dout => grp_fu_318_p2);

    urem_4ns_3ns_2_8_1_U9 : component conv3_urem_4ns_3ns_2_8_1
    generic map (
        ID => 1,
        NUM_STAGE => 8,
        din0_WIDTH => 4,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_664_p0,
        din1 => grp_fu_664_p1,
        ce => grp_fu_664_ce,
        dout => grp_fu_664_p2);

    mul_4ns_6ns_9_1_1_U10 : component conv3_mul_4ns_6ns_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 6,
        dout_WIDTH => 9)
    port map (
        din0 => mul_ln56_fu_896_p0,
        din1 => mul_ln56_fu_896_p1,
        dout => mul_ln56_fu_896_p2);

    sparsemux_7_2_32_1_1_U11 : component conv3_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => in_buf_load_reg_1747,
        din1 => in_buf_1_load_reg_1752,
        din2 => in_buf_2_load_reg_1757,
        def => tmp_fu_1177_p7,
        sel => tmp_fu_1177_p8,
        dout => tmp_fu_1177_p9);

    flow_control_loop_pipe_sequential_init_U : component conv3_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage3,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage3)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    acc_2_fu_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                if (((or_ln54_3_reg_1687_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    acc_2_fu_164 <= acc_4_mid271_fu_1208_p3;
                elsif (((or_ln54_3_reg_1687_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    acc_2_fu_164 <= acc_reg_1772;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    acc_2_fu_164 <= grp_fu_310_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    ic_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ic_fu_188 <= ap_const_lv6_0;
            elsif (((icmp_ln43_reg_1521 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                ic_fu_188 <= select_ln50_fu_837_p3;
            end if; 
        end if;
    end process;

    indvar_flatten132_fu_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten132_fu_216 <= ap_const_lv16_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln43_fu_407_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                indvar_flatten132_fu_216 <= select_ln45_3_fu_500_p3;
            end if; 
        end if;
    end process;

    indvar_flatten192_fu_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten192_fu_224 <= ap_const_lv21_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln43_fu_407_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                indvar_flatten192_fu_224 <= add_ln43_1_fu_413_p2;
            end if; 
        end if;
    end process;

    indvar_flatten28_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten28_fu_184 <= ap_const_lv4_0;
            elsif (((icmp_ln43_reg_1521 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                indvar_flatten28_fu_184 <= select_ln52_1_fu_693_p3;
            end if; 
        end if;
    end process;

    indvar_flatten49_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten49_fu_192 <= ap_const_lv10_0;
            elsif (((icmp_ln43_reg_1521 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                indvar_flatten49_fu_192 <= select_ln50_1_fu_706_p3;
            end if; 
        end if;
    end process;

    indvar_flatten84_fu_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten84_fu_204 <= ap_const_lv13_0;
            elsif (((icmp_ln43_reg_1521 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                indvar_flatten84_fu_204 <= select_ln47_2_fu_719_p3;
            end if; 
        end if;
    end process;

    kx_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                kx_fu_168 <= ap_const_lv2_0;
            elsif (((icmp_ln43_reg_1521 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                kx_fu_168 <= add_ln54_fu_670_p2;
            end if; 
        end if;
    end process;

    ky_fu_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ky_fu_180 <= ap_const_lv2_0;
            elsif (((icmp_ln43_reg_1521 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                ky_fu_180 <= select_ln52_fu_863_p3;
            end if; 
        end if;
    end process;

    oc_fu_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                oc_fu_220 <= ap_const_lv7_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                oc_fu_220 <= select_ln43_2_fu_1064_p3;
            end if; 
        end if;
    end process;

    ox_fu_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ox_fu_200 <= ap_const_lv4_0;
            elsif (((icmp_ln43_reg_1521 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ox_fu_200 <= select_ln47_fu_579_p3;
            end if; 
        end if;
    end process;

    oy_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    oy_fu_212 <= ap_const_lv4_0;
                elsif (((icmp_ln43_reg_1521 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    oy_fu_212 <= select_ln45_1_fu_983_p3;
                end if;
            end if; 
        end if;
    end process;

    phi_ln45_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                phi_ln45_fu_208 <= ap_const_lv256_lc_1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                phi_ln45_fu_208 <= select_ln45_2_fu_1263_p3;
            end if; 
        end if;
    end process;

    shiftreg_fu_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                shiftreg_fu_196 <= ap_const_lv256_lc_1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                shiftreg_fu_196 <= select_ln47_1_fu_1270_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                BIASES3_addr_reg_1722 <= zext_ln43_fu_1142_p1(6 - 1 downto 0);
                add_ln56_reg_1642 <= add_ln56_fu_658_p2;
                empty_25_reg_1604 <= empty_25_fu_553_p2;
                empty_27_reg_1621 <= empty_27_fu_591_p2;
                exitcond_flatten30_mid283_reg_1614 <= exitcond_flatten30_mid283_fu_573_p2;
                first_iter_4234_reg_1599 <= first_iter_4234_fu_521_p2;
                first_iter_4_mid1_reg_1609 <= first_iter_4_mid1_fu_558_p2;
                icmp_ln47_1_reg_1652 <= icmp_ln47_1_fu_682_p2;
                icmp_ln47_1_reg_1652_pp0_iter1_reg <= icmp_ln47_1_reg_1652;
                icmp_ln47_1_reg_1652_pp0_iter2_reg <= icmp_ln47_1_reg_1652_pp0_iter1_reg;
                icmp_ln47_1_reg_1652_pp0_iter3_reg <= icmp_ln47_1_reg_1652_pp0_iter2_reg;
                icmp_ln47_1_reg_1652_pp0_iter4_reg <= icmp_ln47_1_reg_1652_pp0_iter3_reg;
                icmp_ln54_1_reg_1632 <= icmp_ln54_1_fu_648_p2;
                icmp_ln54_2_reg_1648 <= icmp_ln54_2_fu_676_p2;
                icmp_ln54_2_reg_1648_pp0_iter1_reg <= icmp_ln54_2_reg_1648;
                icmp_ln54_2_reg_1648_pp0_iter2_reg <= icmp_ln54_2_reg_1648_pp0_iter1_reg;
                icmp_ln54_2_reg_1648_pp0_iter3_reg <= icmp_ln54_2_reg_1648_pp0_iter2_reg;
                icmp_ln54_2_reg_1648_pp0_iter4_reg <= icmp_ln54_2_reg_1648_pp0_iter3_reg;
                icmp_ln54_mid248_reg_1626 <= icmp_ln54_mid248_fu_618_p2;
                    zext_ln56_3_reg_1637(1 downto 0) <= zext_ln56_3_fu_654_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                WEIGHTS3_load_reg_1762 <= WEIGHTS3_q0;
                acc_reg_1772 <= BIASES3_q0;
                    ap_predicate_pred179_state21 <= ((trunc_ln45_reg_1691_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln47_1_reg_1652_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln50_1_reg_1683_pp0_iter3_reg = ap_const_lv1_1) and (icmp_ln52_1_reg_1679_pp0_iter3_reg = ap_const_lv1_1) and (icmp_ln54_2_reg_1648_pp0_iter4_reg = ap_const_lv1_1));
                icmp_ln50_1_reg_1683 <= icmp_ln50_1_fu_918_p2;
                icmp_ln50_1_reg_1683_pp0_iter1_reg <= icmp_ln50_1_reg_1683;
                icmp_ln50_1_reg_1683_pp0_iter2_reg <= icmp_ln50_1_reg_1683_pp0_iter1_reg;
                icmp_ln50_1_reg_1683_pp0_iter3_reg <= icmp_ln50_1_reg_1683_pp0_iter2_reg;
                icmp_ln50_1_reg_1683_pp0_iter4_reg <= icmp_ln50_1_reg_1683_pp0_iter3_reg;
                icmp_ln52_1_reg_1679 <= icmp_ln52_1_fu_912_p2;
                icmp_ln52_1_reg_1679_pp0_iter1_reg <= icmp_ln52_1_reg_1679;
                icmp_ln52_1_reg_1679_pp0_iter2_reg <= icmp_ln52_1_reg_1679_pp0_iter1_reg;
                icmp_ln52_1_reg_1679_pp0_iter3_reg <= icmp_ln52_1_reg_1679_pp0_iter2_reg;
                icmp_ln52_1_reg_1679_pp0_iter4_reg <= icmp_ln52_1_reg_1679_pp0_iter3_reg;
                in_buf_1_load_reg_1752 <= in_buf_1_q0;
                in_buf_2_load_reg_1757 <= in_buf_2_q0;
                in_buf_load_reg_1747 <= in_buf_q0;
                lshr_ln_reg_1805 <= select_ln47_1_fu_1270_p3(255 downto 32);
                or_ln54_1_reg_1669 <= or_ln54_1_fu_887_p2;
                select_ln45_2_reg_1794 <= select_ln45_2_fu_1263_p3;
                select_ln50_reg_1656 <= select_ln50_fu_837_p3;
                select_ln52_reg_1663 <= select_ln52_fu_863_p3;
                select_ln62_reg_1799 <= select_ln62_fu_1318_p3;
                tmp_8_reg_1674 <= mul_ln56_fu_896_p2(8 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (or_ln54_3_reg_1687_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                acc10_fu_228 <= acc_reg_1772;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                acc_1_reg_1788 <= grp_fu_310_p2;
                add_ln56_3_reg_1712 <= add_ln56_3_fu_1122_p2;
                add_ln56_5_reg_1717 <= add_ln56_5_fu_1131_p2;
                and_ln43_3_reg_1559 <= and_ln43_3_fu_464_p2;
                and_ln43_3_reg_1559_pp0_iter1_reg <= and_ln43_3_reg_1559;
                and_ln43_3_reg_1559_pp0_iter2_reg <= and_ln43_3_reg_1559_pp0_iter1_reg;
                and_ln43_3_reg_1559_pp0_iter3_reg <= and_ln43_3_reg_1559_pp0_iter2_reg;
                and_ln43_3_reg_1559_pp0_iter4_reg <= and_ln43_3_reg_1559_pp0_iter3_reg;
                empty_23_reg_1571 <= empty_23_fu_470_p2;
                empty_23_reg_1571_pp0_iter1_reg <= empty_23_reg_1571;
                empty_23_reg_1571_pp0_iter2_reg <= empty_23_reg_1571_pp0_iter1_reg;
                empty_23_reg_1571_pp0_iter3_reg <= empty_23_reg_1571_pp0_iter2_reg;
                empty_23_reg_1571_pp0_iter4_reg <= empty_23_reg_1571_pp0_iter3_reg;
                exitcond_flatten51_mid2131_reg_1585 <= exitcond_flatten51_mid2131_fu_488_p2;
                exitcond_flatten51_mid2131_reg_1585_pp0_iter1_reg <= exitcond_flatten51_mid2131_reg_1585;
                exitcond_flatten51_mid2131_reg_1585_pp0_iter2_reg <= exitcond_flatten51_mid2131_reg_1585_pp0_iter1_reg;
                exitcond_flatten51_mid2131_reg_1585_pp0_iter3_reg <= exitcond_flatten51_mid2131_reg_1585_pp0_iter2_reg;
                exitcond_flatten51_mid2131_reg_1585_pp0_iter4_reg <= exitcond_flatten51_mid2131_reg_1585_pp0_iter3_reg;
                icmp_ln43_reg_1521 <= icmp_ln43_fu_407_p2;
                icmp_ln43_reg_1521_pp0_iter1_reg <= icmp_ln43_reg_1521;
                icmp_ln43_reg_1521_pp0_iter2_reg <= icmp_ln43_reg_1521_pp0_iter1_reg;
                icmp_ln43_reg_1521_pp0_iter3_reg <= icmp_ln43_reg_1521_pp0_iter2_reg;
                icmp_ln45_reg_1530 <= icmp_ln45_fu_422_p2;
                icmp_ln45_reg_1530_pp0_iter1_reg <= icmp_ln45_reg_1530;
                icmp_ln45_reg_1530_pp0_iter2_reg <= icmp_ln45_reg_1530_pp0_iter1_reg;
                icmp_ln45_reg_1530_pp0_iter3_reg <= icmp_ln45_reg_1530_pp0_iter2_reg;
                icmp_ln45_reg_1530_pp0_iter4_reg <= icmp_ln45_reg_1530_pp0_iter3_reg;
                icmp_ln52_reg_1554 <= icmp_ln52_fu_440_p2;
                icmp_ln54_reg_1549 <= icmp_ln54_fu_434_p2;
                indvar_flatten28_load_reg_1506 <= indvar_flatten28_fu_184;
                indvar_flatten49_load_reg_1511 <= indvar_flatten49_fu_192;
                indvar_flatten84_load_reg_1516 <= indvar_flatten84_fu_204;
                kx_load_reg_1525 <= kx_fu_168;
                not_exitcond_flatten86_mid2191203_reg_1579 <= not_exitcond_flatten86_mid2191203_fu_482_p2;
                select_ln43_2_reg_1706 <= select_ln43_2_fu_1064_p3;
                xor_ln43_reg_1543 <= xor_ln43_fu_428_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln56_2_reg_1701 <= add_ln56_2_fu_1045_p2;
                empty_reg_1696 <= empty_fu_1039_p2;
                or_ln54_3_reg_1687 <= or_ln54_3_fu_1013_p2;
                or_ln54_3_reg_1687_pp0_iter2_reg <= or_ln54_3_reg_1687;
                or_ln54_3_reg_1687_pp0_iter3_reg <= or_ln54_3_reg_1687_pp0_iter2_reg;
                trunc_ln45_reg_1691 <= trunc_ln45_fu_1019_p1;
                trunc_ln45_reg_1691_pp0_iter2_reg <= trunc_ln45_reg_1691;
                trunc_ln45_reg_1691_pp0_iter3_reg <= trunc_ln45_reg_1691_pp0_iter2_reg;
                trunc_ln45_reg_1691_pp0_iter4_reg <= trunc_ln45_reg_1691_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                mul_reg_1778 <= grp_fu_314_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or_ln6220_fu_176 <= or_ln1_fu_1352_p3;
                select_ln4516_fu_172 <= select_ln45_fu_1366_p3;
            end if;
        end if;
    end process;
    zext_ln56_3_reg_1637(3 downto 2) <= "00";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage3_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter4_stage0, ap_idle_pp0_0to3, ap_idle_pp0_1to5, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to5 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    AXI_OUT_blk_n_W_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, m_axi_AXI_OUT_0_WREADY, ap_block_pp0_stage0_grp1, ap_predicate_pred179_state21)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_pred179_state21 = ap_const_boolean_1))) then 
            AXI_OUT_blk_n_W <= m_axi_AXI_OUT_0_WREADY;
        else 
            AXI_OUT_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    BIASES3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            BIASES3_ce0_local <= ap_const_logic_1;
        else 
            BIASES3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    WEIGHTS3_address0 <= zext_ln56_4_fu_1162_p1(15 - 1 downto 0);

    WEIGHTS3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            WEIGHTS3_ce0_local <= ap_const_logic_1;
        else 
            WEIGHTS3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_4_mid2111_fu_1201_p3 <= 
        acc10_fu_228 when (and_ln43_3_reg_1559_pp0_iter2_reg(0) = '1') else 
        ap_sig_allocacmp_acc_2_load;
    acc_4_mid271_fu_1208_p3 <= 
        acc10_fu_228 when (exitcond_flatten51_mid2131_reg_1585_pp0_iter2_reg(0) = '1') else 
        acc_4_mid2111_fu_1201_p3;
    add_ln43_1_fu_413_p2 <= std_logic_vector(unsigned(indvar_flatten192_fu_224) + unsigned(ap_const_lv21_1));
    add_ln43_fu_1058_p2 <= std_logic_vector(unsigned(oc_fu_220) + unsigned(ap_const_lv7_1));
    add_ln45_1_fu_494_p2 <= std_logic_vector(unsigned(indvar_flatten132_fu_216) + unsigned(ap_const_lv16_1));
    add_ln45_fu_959_p2 <= std_logic_vector(unsigned(select_ln43_fu_937_p3) + unsigned(ap_const_lv4_1));
    add_ln47_1_fu_714_p2 <= std_logic_vector(unsigned(indvar_flatten84_load_reg_1516) + unsigned(ap_const_lv13_1));
    add_ln47_fu_543_p2 <= std_logic_vector(unsigned(ox_mid293_fu_531_p3) + unsigned(ap_const_lv4_1));
    add_ln50_1_fu_701_p2 <= std_logic_vector(unsigned(indvar_flatten49_load_reg_1511) + unsigned(ap_const_lv10_1));
    add_ln50_fu_806_p2 <= std_logic_vector(unsigned(ic_1_mid259_fu_789_p3) + unsigned(ap_const_lv6_1));
    add_ln52_1_fu_688_p2 <= std_logic_vector(unsigned(indvar_flatten28_load_reg_1506) + unsigned(ap_const_lv4_1));
    add_ln52_2_fu_1092_p2 <= std_logic_vector(unsigned(tmp_3_fu_1074_p3) + unsigned(zext_ln52_fu_1088_p1));
    add_ln52_fu_844_p2 <= std_logic_vector(unsigned(ky_mid238_fu_812_p3) + unsigned(ap_const_lv2_1));
    add_ln54_fu_670_p2 <= std_logic_vector(unsigned(kx_mid2_fu_641_p3) + unsigned(ap_const_lv2_1));
    add_ln56_1_fu_1101_p2 <= std_logic_vector(unsigned(add_ln52_2_fu_1092_p2) + unsigned(zext_ln56_2_fu_1098_p1));
    add_ln56_2_fu_1045_p2 <= std_logic_vector(unsigned(sub_ln56_fu_1033_p2) + unsigned(zext_ln56_3_reg_1637));
    add_ln56_3_fu_1122_p2 <= std_logic_vector(unsigned(tmp_6_fu_1115_p3) + unsigned(zext_ln56_fu_1071_p1));
    add_ln56_4_fu_1156_p2 <= std_logic_vector(unsigned(tmp_7_fu_1149_p3) + unsigned(select_ln43_4_cast_fu_1146_p1));
    add_ln56_5_fu_1131_p2 <= std_logic_vector(unsigned(tmp_5_fu_1107_p3) + unsigned(zext_ln56_6_fu_1128_p1));
    add_ln56_fu_658_p2 <= std_logic_vector(unsigned(zext_ln56_3_fu_654_p1) + unsigned(select_ln47_fu_579_p3));
    and_ln43_1_fu_527_p2 <= (xor_ln43_reg_1543 and icmp_ln52_reg_1554);
    and_ln43_2_fu_452_p2 <= (xor_ln43_fu_428_p2 and icmp_ln50_fu_446_p2);
    and_ln43_3_fu_464_p2 <= (xor_ln43_fu_428_p2 and icmp_ln47_fu_458_p2);
    and_ln43_fu_569_p2 <= (xor_ln43_reg_1543 and icmp_ln54_reg_1549);
    and_ln60_fu_1312_p2 <= (or_ln60_fu_1306_p2 and grp_fu_318_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0_01001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_state21_io_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state21_io_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_state21_io_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state21_io_grp1));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_state21_io_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state21_io_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state21_io_grp1_assign_proc : process(m_axi_AXI_OUT_0_WREADY, ap_predicate_op283_write_state21)
    begin
                ap_block_state21_io_grp1 <= ((m_axi_AXI_OUT_0_WREADY = ap_const_logic_0) and (ap_predicate_op283_write_state21 = ap_const_boolean_1));
    end process;


    ap_condition_exit_pp0_iter0_stage3_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln43_reg_1521)
    begin
        if (((icmp_ln43_reg_1521 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter4_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone, icmp_ln43_reg_1521_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln43_reg_1521_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to5 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to5 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage3;

    ap_predicate_op283_write_state21_assign_proc : process(icmp_ln54_2_reg_1648_pp0_iter4_reg, icmp_ln47_1_reg_1652_pp0_iter4_reg, trunc_ln45_reg_1691_pp0_iter4_reg, icmp_ln52_1_reg_1679_pp0_iter4_reg, icmp_ln50_1_reg_1683_pp0_iter4_reg)
    begin
                ap_predicate_op283_write_state21 <= ((icmp_ln50_1_reg_1683_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln52_1_reg_1679_pp0_iter4_reg = ap_const_lv1_1) and (trunc_ln45_reg_1691_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln47_1_reg_1652_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln54_2_reg_1648_pp0_iter4_reg = ap_const_lv1_1));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_2_load_assign_proc : process(ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, grp_fu_310_p2, acc_2_fu_164, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_sig_allocacmp_acc_2_load <= grp_fu_310_p2;
        else 
            ap_sig_allocacmp_acc_2_load <= acc_2_fu_164;
        end if; 
    end process;


    ap_sig_allocacmp_acc_2_load_1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, or_ln54_3_reg_1687_pp0_iter3_reg, acc_reg_1772, grp_fu_310_p2, acc_2_fu_164, acc_4_mid271_fu_1208_p3, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
            if (((or_ln54_3_reg_1687_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                ap_sig_allocacmp_acc_2_load_1 <= acc_4_mid271_fu_1208_p3;
            elsif (((or_ln54_3_reg_1687_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                ap_sig_allocacmp_acc_2_load_1 <= acc_reg_1772;
            elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                ap_sig_allocacmp_acc_2_load_1 <= grp_fu_310_p2;
            else 
                ap_sig_allocacmp_acc_2_load_1 <= acc_2_fu_164;
            end if;
        else 
            ap_sig_allocacmp_acc_2_load_1 <= acc_2_fu_164;
        end if; 
    end process;

    bitcast_ln60_fu_1277_p1 <= acc_1_reg_1788;
    empty_23_fu_470_p2 <= (icmp_ln45_fu_422_p2 or and_ln43_3_fu_464_p2);
    empty_24_fu_549_p2 <= (exitcond_flatten51_mid2131_reg_1585 or and_ln43_3_reg_1559);
    empty_25_fu_553_p2 <= (icmp_ln45_reg_1530 or empty_24_fu_549_p2);
    empty_26_fu_586_p2 <= (exitcond_flatten51_mid2131_reg_1585 or exitcond_flatten30_mid283_fu_573_p2);
    empty_27_fu_591_p2 <= (empty_26_fu_586_p2 or empty_23_reg_1571);
    empty_28_fu_624_p2 <= (exitcond_flatten30_mid283_fu_573_p2 or empty_24_fu_549_p2);
    empty_29_fu_630_p2 <= (icmp_ln54_mid248_fu_618_p2 or empty_28_fu_624_p2);
    empty_30_fu_636_p2 <= (icmp_ln45_reg_1530 or empty_29_fu_630_p2);
    empty_fu_1039_p2 <= std_logic_vector(unsigned(zext_ln56_1_fu_1023_p1) + unsigned(select_ln45_1_fu_983_p3));
    exitcond_flatten30_mid2127_fu_538_p2 <= (not_exitcond_flatten86_mid2191203_reg_1579 and and_ln43_1_fu_527_p2);
    exitcond_flatten30_mid2127_not_fu_596_p2 <= (exitcond_flatten30_mid2127_fu_538_p2 xor ap_const_lv1_1);
    exitcond_flatten30_mid283_fu_573_p2 <= (not_exitcond_flatten51_mid2131_fu_564_p2 and exitcond_flatten30_mid2127_fu_538_p2);
    exitcond_flatten51_mid2131_fu_488_p2 <= (not_exitcond_flatten86_mid2191203_fu_482_p2 and and_ln43_2_fu_452_p2);
    exitcond_flatten86_not204_fu_476_p2 <= (icmp_ln47_fu_458_p2 xor ap_const_lv1_1);
    first_iter_2238_fu_768_p2 <= "1" when (ky_fu_180 = ap_const_lv2_0) else "0";
    first_iter_2_mid1_fu_850_p2 <= "1" when (add_ln52_fu_844_p2 = ap_const_lv2_0) else "0";
    first_iter_2_mid2121_fu_784_p2 <= (or_ln43_3_fu_774_p2 or and_ln43_3_reg_1559);
    first_iter_2_mid246_fu_832_p2 <= (first_iter_2_mid277_fu_801_p2 or exitcond_flatten30_mid283_reg_1614);
    first_iter_2_mid277_fu_801_p2 <= (first_iter_2_mid2121_fu_784_p2 or exitcond_flatten51_mid2131_reg_1585);
    first_iter_2_mid2_fu_856_p3 <= 
        first_iter_2_mid1_fu_850_p2 when (icmp_ln54_mid248_reg_1626(0) = '1') else 
        first_iter_2_mid246_fu_832_p2;
    first_iter_3236_fu_757_p2 <= "1" when (ic_fu_188 = ap_const_lv6_0) else "0";
    first_iter_3_mid1_fu_819_p2 <= "1" when (add_ln50_fu_806_p2 = ap_const_lv6_0) else "0";
    first_iter_3_mid2117_fu_779_p2 <= (or_ln43_2_fu_763_p2 or and_ln43_3_reg_1559);
    first_iter_3_mid273_fu_796_p2 <= (first_iter_3_mid2117_fu_779_p2 or exitcond_flatten51_mid2131_reg_1585);
    first_iter_3_mid2_fu_825_p3 <= 
        first_iter_3_mid1_fu_819_p2 when (exitcond_flatten30_mid283_reg_1614(0) = '1') else 
        first_iter_3_mid273_fu_796_p2;
    first_iter_4234_fu_521_p2 <= "1" when (ox_fu_200 = ap_const_lv4_0) else "0";
    first_iter_4_mid1_fu_558_p2 <= "1" when (add_ln47_fu_543_p2 = ap_const_lv4_0) else "0";
    first_iter_4_mid2113_fu_978_p2 <= (or_ln43_1_fu_955_p2 or and_ln43_3_reg_1559);
    first_iter_4_mid2_fu_990_p3 <= 
        first_iter_4_mid1_reg_1609 when (exitcond_flatten51_mid2131_reg_1585(0) = '1') else 
        first_iter_4_mid2113_fu_978_p2;
    first_iter_5231_fu_944_p2 <= "1" when (oy_fu_212 = ap_const_lv4_0) else "0";
    first_iter_5_mid1_fu_965_p2 <= "1" when (add_ln45_fu_959_p2 = ap_const_lv4_0) else "0";
    first_iter_5_mid2_fu_971_p3 <= 
        first_iter_5_mid1_fu_965_p2 when (and_ln43_3_reg_1559(0) = '1') else 
        or_ln43_fu_950_p2;

    grp_fu_310_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            grp_fu_310_ce <= ap_const_logic_1;
        else 
            grp_fu_310_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_314_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            grp_fu_314_ce <= ap_const_logic_1;
        else 
            grp_fu_314_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_318_ce_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            grp_fu_318_ce <= ap_const_logic_1;
        else 
            grp_fu_318_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_664_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            grp_fu_664_ce <= ap_const_logic_1;
        else 
            grp_fu_664_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_664_p0 <= std_logic_vector(unsigned(zext_ln56_3_fu_654_p1) + unsigned(select_ln47_fu_579_p3));
    grp_fu_664_p1 <= ap_const_lv4_3(3 - 1 downto 0);
    ic_1_mid259_fu_789_p3 <= 
        ap_const_lv6_0 when (empty_25_reg_1604(0) = '1') else 
        ic_fu_188;
    icmp_ln43_fu_407_p2 <= "1" when (indvar_flatten192_fu_224 = ap_const_lv21_120000) else "0";
    icmp_ln45_fu_422_p2 <= "1" when (indvar_flatten132_fu_216 = ap_const_lv16_4800) else "0";
    icmp_ln47_1_fu_682_p2 <= "1" when (select_ln47_fu_579_p3 = ap_const_lv4_7) else "0";
    icmp_ln47_fu_458_p2 <= "1" when (indvar_flatten84_fu_204 = ap_const_lv13_900) else "0";
    icmp_ln50_1_fu_918_p2 <= "1" when (select_ln50_fu_837_p3 = ap_const_lv6_1F) else "0";
    icmp_ln50_fu_446_p2 <= "1" when (indvar_flatten49_fu_192 = ap_const_lv10_120) else "0";
    icmp_ln52_1_fu_912_p2 <= "1" when (select_ln52_fu_863_p3 = ap_const_lv2_2) else "0";
    icmp_ln52_fu_440_p2 <= "1" when (indvar_flatten28_fu_184 = ap_const_lv4_9) else "0";
    icmp_ln54_1_fu_648_p2 <= "0" when (kx_mid2_fu_641_p3 = ap_const_lv2_0) else "1";
    icmp_ln54_2_fu_676_p2 <= "1" when (add_ln54_fu_670_p2 = ap_const_lv2_3) else "0";
    icmp_ln54_fu_434_p2 <= "1" when (kx_fu_168 = ap_const_lv2_3) else "0";
    icmp_ln54_mid2123_fu_607_p2 <= (not_exitcond_flatten86_mid2191203_reg_1579 and and_ln43_fu_569_p2);
    icmp_ln54_mid248_fu_618_p2 <= (not_exitcond_flatten30_mid283_fu_602_p2 and icmp_ln54_mid279_fu_612_p2);
    icmp_ln54_mid279_fu_612_p2 <= (not_exitcond_flatten51_mid2131_fu_564_p2 and icmp_ln54_mid2123_fu_607_p2);
    icmp_ln60_1_fu_1300_p2 <= "1" when (trunc_ln60_fu_1290_p1 = ap_const_lv23_0) else "0";
    icmp_ln60_fu_1294_p2 <= "0" when (tmp_1_fu_1280_p4 = ap_const_lv8_FF) else "1";
    in_buf_1_address0 <= zext_ln56_7_fu_1167_p1(11 - 1 downto 0);
    in_buf_1_ce0 <= in_buf_1_ce0_local;

    in_buf_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in_buf_1_ce0_local <= ap_const_logic_1;
        else 
            in_buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_2_address0 <= zext_ln56_7_fu_1167_p1(11 - 1 downto 0);
    in_buf_2_ce0 <= in_buf_2_ce0_local;

    in_buf_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in_buf_2_ce0_local <= ap_const_logic_1;
        else 
            in_buf_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_address0 <= zext_ln56_7_fu_1167_p1(11 - 1 downto 0);
    in_buf_ce0 <= in_buf_ce0_local;

    in_buf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in_buf_ce0_local <= ap_const_logic_1;
        else 
            in_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    kx_mid2_fu_641_p3 <= 
        ap_const_lv2_0 when (empty_30_fu_636_p2(0) = '1') else 
        kx_load_reg_1525;
    ky_mid238_fu_812_p3 <= 
        ap_const_lv2_0 when (empty_27_reg_1621(0) = '1') else 
        ky_fu_180;
    m_axi_AXI_OUT_0_ARADDR <= ap_const_lv64_0;
    m_axi_AXI_OUT_0_ARBURST <= ap_const_lv2_0;
    m_axi_AXI_OUT_0_ARCACHE <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_ARID <= ap_const_lv1_0;
    m_axi_AXI_OUT_0_ARLEN <= ap_const_lv32_0;
    m_axi_AXI_OUT_0_ARLOCK <= ap_const_lv2_0;
    m_axi_AXI_OUT_0_ARPROT <= ap_const_lv3_0;
    m_axi_AXI_OUT_0_ARQOS <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_ARREGION <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_ARSIZE <= ap_const_lv3_0;
    m_axi_AXI_OUT_0_ARUSER <= ap_const_lv1_0;
    m_axi_AXI_OUT_0_ARVALID <= ap_const_logic_0;
    m_axi_AXI_OUT_0_AWADDR <= ap_const_lv64_0;
    m_axi_AXI_OUT_0_AWBURST <= ap_const_lv2_0;
    m_axi_AXI_OUT_0_AWCACHE <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_AWID <= ap_const_lv1_0;
    m_axi_AXI_OUT_0_AWLEN <= ap_const_lv32_0;
    m_axi_AXI_OUT_0_AWLOCK <= ap_const_lv2_0;
    m_axi_AXI_OUT_0_AWPROT <= ap_const_lv3_0;
    m_axi_AXI_OUT_0_AWQOS <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_AWREGION <= ap_const_lv4_0;
    m_axi_AXI_OUT_0_AWSIZE <= ap_const_lv3_0;
    m_axi_AXI_OUT_0_AWUSER <= ap_const_lv1_0;
    m_axi_AXI_OUT_0_AWVALID <= ap_const_logic_0;
    m_axi_AXI_OUT_0_BREADY <= ap_const_logic_0;
    m_axi_AXI_OUT_0_RREADY <= ap_const_logic_0;
    m_axi_AXI_OUT_0_WDATA <= ((select_ln62_reg_1799 & lshr_ln_reg_1805) & select_ln45_2_reg_1794);
    m_axi_AXI_OUT_0_WID <= ap_const_lv1_0;
    m_axi_AXI_OUT_0_WLAST <= ap_const_logic_0;
    m_axi_AXI_OUT_0_WSTRB <= ap_const_lv64_FFFFFFFFFFFFFFFF;
    m_axi_AXI_OUT_0_WUSER <= ap_const_lv1_0;

    m_axi_AXI_OUT_0_WVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, ap_predicate_op283_write_state21, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_predicate_op283_write_state21 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_AXI_OUT_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_AXI_OUT_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln56_fu_896_p0 <= mul_ln56_fu_896_p00(4 - 1 downto 0);
    mul_ln56_fu_896_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_reg_1642),9));
    mul_ln56_fu_896_p1 <= ap_const_lv9_16(6 - 1 downto 0);
    not_exitcond_flatten30_mid283_fu_602_p2 <= (exitcond_flatten51_mid2131_reg_1585 or exitcond_flatten30_mid2127_not_fu_596_p2);
    not_exitcond_flatten51_mid2131_fu_564_p2 <= (exitcond_flatten51_mid2131_reg_1585 xor ap_const_lv1_1);
    not_exitcond_flatten86_mid2191203_fu_482_p2 <= (icmp_ln45_fu_422_p2 or exitcond_flatten86_not204_fu_476_p2);
    or_ln1_fu_1352_p3 <= (select_ln62_reg_1799 & lshr_ln_reg_1805);
    or_ln43_1_fu_955_p2 <= (icmp_ln45_reg_1530 or first_iter_4234_reg_1599);
    or_ln43_2_fu_763_p2 <= (icmp_ln45_reg_1530 or first_iter_3236_fu_757_p2);
    or_ln43_3_fu_774_p2 <= (icmp_ln45_reg_1530 or first_iter_2238_fu_768_p2);
    or_ln43_fu_950_p2 <= (icmp_ln45_reg_1530 or first_iter_5231_fu_944_p2);
    or_ln54_1_fu_887_p2 <= (xor_ln54_1_fu_881_p2 or or_ln54_fu_876_p2);
    or_ln54_2_fu_1002_p2 <= (xor_ln54_2_fu_996_p2 or or_ln54_1_reg_1669);
    or_ln54_3_fu_1013_p2 <= (xor_ln54_3_fu_1007_p2 or or_ln54_2_fu_1002_p2);
    or_ln54_fu_876_p2 <= (xor_ln54_fu_870_p2 or icmp_ln54_1_reg_1632);
    or_ln60_fu_1306_p2 <= (icmp_ln60_fu_1294_p2 or icmp_ln60_1_fu_1300_p2);
    ox_mid293_fu_531_p3 <= 
        ap_const_lv4_0 when (empty_23_reg_1571(0) = '1') else 
        ox_fu_200;
    p_shl_fu_1026_p3 <= (select_ln52_reg_1663 & ap_const_lv2_0);
    select_ln43_1_fu_1249_p3 <= 
        ap_const_lv256_lc_1 when (icmp_ln45_reg_1530_pp0_iter4_reg(0) = '1') else 
        phi_ln45_fu_208;
    select_ln43_2_fu_1064_p3 <= 
        add_ln43_fu_1058_p2 when (icmp_ln45_reg_1530(0) = '1') else 
        oc_fu_220;
    select_ln43_4_cast_fu_1146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln43_2_reg_1706),15));
    select_ln43_fu_937_p3 <= 
        ap_const_lv4_0 when (icmp_ln45_reg_1530(0) = '1') else 
        oy_fu_212;
    select_ln45_1_fu_983_p3 <= 
        add_ln45_fu_959_p2 when (and_ln43_3_reg_1559(0) = '1') else 
        select_ln43_fu_937_p3;
    select_ln45_2_fu_1263_p3 <= 
        select_ln4516_fu_172 when (and_ln43_3_reg_1559_pp0_iter4_reg(0) = '1') else 
        select_ln43_1_fu_1249_p3;
    select_ln45_3_fu_500_p3 <= 
        ap_const_lv16_1 when (icmp_ln45_fu_422_p2(0) = '1') else 
        add_ln45_1_fu_494_p2;
    select_ln45_fu_1366_p3 <= 
        ap_const_lv256_lc_1 when (trunc_ln45_reg_1691_pp0_iter4_reg(0) = '1') else 
        or_ln1_fu_1352_p3;
    select_ln47_1_fu_1270_p3 <= 
        or_ln6220_fu_176 when (exitcond_flatten51_mid2131_reg_1585_pp0_iter4_reg(0) = '1') else 
        shiftreg_mid294_fu_1256_p3;
    select_ln47_2_fu_719_p3 <= 
        ap_const_lv13_1 when (empty_23_reg_1571(0) = '1') else 
        add_ln47_1_fu_714_p2;
    select_ln47_fu_579_p3 <= 
        add_ln47_fu_543_p2 when (exitcond_flatten51_mid2131_reg_1585(0) = '1') else 
        ox_mid293_fu_531_p3;
    select_ln50_1_fu_706_p3 <= 
        ap_const_lv10_1 when (empty_25_fu_553_p2(0) = '1') else 
        add_ln50_1_fu_701_p2;
    select_ln50_fu_837_p3 <= 
        add_ln50_fu_806_p2 when (exitcond_flatten30_mid283_reg_1614(0) = '1') else 
        ic_1_mid259_fu_789_p3;
    select_ln52_1_fu_693_p3 <= 
        ap_const_lv4_1 when (empty_27_fu_591_p2(0) = '1') else 
        add_ln52_1_fu_688_p2;
    select_ln52_fu_863_p3 <= 
        add_ln52_fu_844_p2 when (icmp_ln54_mid248_reg_1626(0) = '1') else 
        ky_mid238_fu_812_p3;
    select_ln62_fu_1318_p3 <= 
        bitcast_ln60_fu_1277_p1 when (and_ln60_fu_1312_p2(0) = '1') else 
        ap_const_lv32_0;
    shiftreg_mid294_fu_1256_p3 <= 
        ap_const_lv256_lc_1 when (empty_23_reg_1571_pp0_iter4_reg(0) = '1') else 
        shiftreg_fu_196;
    sub_ln56_fu_1033_p2 <= std_logic_vector(unsigned(p_shl_fu_1026_p3) - unsigned(zext_ln56_1_fu_1023_p1));
    tmp_1_fu_1280_p4 <= bitcast_ln60_fu_1277_p1(30 downto 23);
    tmp_3_fu_1074_p3 <= (select_ln50_reg_1656 & ap_const_lv3_0);
    tmp_4_fu_1081_p3 <= (select_ln50_reg_1656 & ap_const_lv1_0);
    tmp_5_fu_1107_p3 <= (add_ln56_1_fu_1101_p2 & ap_const_lv2_0);
    tmp_6_fu_1115_p3 <= (add_ln56_2_reg_1701 & ap_const_lv5_0);
    tmp_7_fu_1149_p3 <= (add_ln56_3_reg_1712 & ap_const_lv6_0);
    tmp_fu_1177_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_fu_1177_p8 <= grp_fu_664_p2(2 - 1 downto 0);
    trunc_ln45_fu_1019_p1 <= select_ln45_1_fu_983_p3(1 - 1 downto 0);
    trunc_ln60_fu_1290_p1 <= bitcast_ln60_fu_1277_p1(23 - 1 downto 0);
    xor_ln43_fu_428_p2 <= (icmp_ln45_fu_422_p2 xor ap_const_lv1_1);
    xor_ln54_1_fu_881_p2 <= (first_iter_3_mid2_fu_825_p3 xor ap_const_lv1_1);
    xor_ln54_2_fu_996_p2 <= (first_iter_4_mid2_fu_990_p3 xor ap_const_lv1_1);
    xor_ln54_3_fu_1007_p2 <= (first_iter_5_mid2_fu_971_p3 xor ap_const_lv1_1);
    xor_ln54_fu_870_p2 <= (first_iter_2_mid2_fu_856_p3 xor ap_const_lv1_1);
    zext_ln43_fu_1142_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln43_2_reg_1706),64));
    zext_ln52_fu_1088_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_1081_p3),9));
    zext_ln56_1_fu_1023_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln52_reg_1663),4));
    zext_ln56_2_fu_1098_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_1696),9));
    zext_ln56_3_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kx_mid2_fu_641_p3),4));
    zext_ln56_4_fu_1162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_4_fu_1156_p2),64));
    zext_ln56_6_fu_1128_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_reg_1674),11));
    zext_ln56_7_fu_1167_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_5_reg_1717),64));
    zext_ln56_fu_1071_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln50_reg_1656),9));
end behav;
