// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv2_pool2_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        acc,
        zext_ln42,
        in_buf_address0,
        in_buf_ce0,
        in_buf_q0,
        in_buf_1_address0,
        in_buf_1_ce0,
        in_buf_1_q0,
        in_buf_2_address0,
        in_buf_2_ce0,
        in_buf_2_q0,
        conv_buf_address0,
        conv_buf_ce0,
        conv_buf_we0,
        conv_buf_d0,
        conv_buf_1_address0,
        conv_buf_1_ce0,
        conv_buf_1_we0,
        conv_buf_1_d0,
        grp_fu_322_p_din0,
        grp_fu_322_p_din1,
        grp_fu_322_p_opcode,
        grp_fu_322_p_dout0,
        grp_fu_322_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] acc;
input  [4:0] zext_ln42;
output  [11:0] in_buf_address0;
output   in_buf_ce0;
input  [31:0] in_buf_q0;
output  [11:0] in_buf_1_address0;
output   in_buf_1_ce0;
input  [31:0] in_buf_1_q0;
output  [11:0] in_buf_2_address0;
output   in_buf_2_ce0;
input  [31:0] in_buf_2_q0;
output  [7:0] conv_buf_address0;
output   conv_buf_ce0;
output   conv_buf_we0;
output  [31:0] conv_buf_d0;
output  [7:0] conv_buf_1_address0;
output   conv_buf_1_ce0;
output   conv_buf_1_we0;
output  [31:0] conv_buf_1_d0;
output  [31:0] grp_fu_322_p_din0;
output  [31:0] grp_fu_322_p_din1;
output  [4:0] grp_fu_322_p_opcode;
input  [0:0] grp_fu_322_p_dout0;
output   grp_fu_322_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln44_reg_1005;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [12:0] WEIGHTS2_address0;
wire   [31:0] WEIGHTS2_q0;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] indvar_flatten6_load_reg_995;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [8:0] indvar_flatten21_load_reg_1000;
wire   [0:0] icmp_ln44_fu_328_p2;
reg   [0:0] icmp_ln44_reg_1005_pp0_iter1_reg;
reg   [0:0] icmp_ln44_reg_1005_pp0_iter2_reg;
reg   [0:0] icmp_ln44_reg_1005_pp0_iter3_reg;
reg   [0:0] icmp_ln44_reg_1005_pp0_iter4_reg;
reg   [1:0] kx_load_reg_1009;
wire   [0:0] icmp_ln46_fu_355_p2;
reg   [0:0] icmp_ln46_reg_1014;
reg   [0:0] icmp_ln46_reg_1014_pp0_iter1_reg;
reg   [0:0] icmp_ln46_reg_1014_pp0_iter2_reg;
reg   [0:0] icmp_ln46_reg_1014_pp0_iter3_reg;
wire   [4:0] select_ln44_fu_361_p3;
reg   [4:0] select_ln44_reg_1020;
wire   [0:0] and_ln44_2_fu_399_p2;
reg   [0:0] and_ln44_2_reg_1025;
reg   [0:0] and_ln44_2_reg_1025_pp0_iter1_reg;
reg   [0:0] and_ln44_2_reg_1025_pp0_iter2_reg;
reg   [0:0] and_ln44_2_reg_1025_pp0_iter3_reg;
wire   [4:0] select_ln44_2_fu_405_p3;
reg   [4:0] select_ln44_2_reg_1032;
wire   [4:0] add_ln46_fu_413_p2;
reg   [4:0] add_ln46_reg_1037;
wire   [0:0] empty_fu_419_p2;
reg   [0:0] empty_reg_1042;
wire   [0:0] exitcond_flatten8_mid246_fu_449_p2;
reg   [0:0] exitcond_flatten8_mid246_reg_1049;
wire   [0:0] icmp_ln53_mid220_fu_461_p2;
reg   [0:0] icmp_ln53_mid220_reg_1056;
wire   [4:0] select_ln49_fu_541_p3;
reg   [4:0] select_ln49_reg_1067;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire   [1:0] kx_mid2_fu_563_p3;
reg   [1:0] kx_mid2_reg_1072;
wire   [1:0] select_ln51_fu_570_p3;
reg   [1:0] select_ln51_reg_1077;
wire   [0:0] trunc_ln46_fu_577_p1;
reg   [0:0] trunc_ln46_reg_1084;
reg   [0:0] trunc_ln46_reg_1084_pp0_iter1_reg;
reg   [0:0] trunc_ln46_reg_1084_pp0_iter2_reg;
reg   [0:0] trunc_ln46_reg_1084_pp0_iter3_reg;
reg   [0:0] trunc_ln46_reg_1084_pp0_iter4_reg;
wire   [4:0] add_ln55_fu_589_p2;
reg   [3:0] tmp_3_reg_1098;
wire   [0:0] icmp_ln53_1_fu_627_p2;
reg   [0:0] icmp_ln53_1_reg_1103;
reg   [0:0] icmp_ln53_1_reg_1103_pp0_iter1_reg;
reg   [0:0] icmp_ln53_1_reg_1103_pp0_iter2_reg;
reg   [0:0] icmp_ln53_1_reg_1103_pp0_iter3_reg;
reg   [0:0] icmp_ln53_1_reg_1103_pp0_iter4_reg;
wire   [0:0] icmp_ln51_1_fu_633_p2;
reg   [0:0] icmp_ln51_1_reg_1107;
reg   [0:0] icmp_ln51_1_reg_1107_pp0_iter1_reg;
reg   [0:0] icmp_ln51_1_reg_1107_pp0_iter2_reg;
reg   [0:0] icmp_ln51_1_reg_1107_pp0_iter3_reg;
reg   [0:0] icmp_ln51_1_reg_1107_pp0_iter4_reg;
wire   [0:0] icmp_ln49_1_fu_639_p2;
reg   [0:0] icmp_ln49_1_reg_1111;
reg   [0:0] icmp_ln49_1_reg_1111_pp0_iter1_reg;
reg   [0:0] icmp_ln49_1_reg_1111_pp0_iter2_reg;
reg   [0:0] icmp_ln49_1_reg_1111_pp0_iter3_reg;
reg   [0:0] icmp_ln49_1_reg_1111_pp0_iter4_reg;
reg   [3:0] lshr_ln_reg_1115;
wire   [4:0] empty_28_fu_732_p2;
reg   [4:0] empty_28_reg_1120;
wire    ap_block_pp0_stage3_11001;
wire   [7:0] add_ln55_3_fu_754_p2;
reg   [7:0] add_ln55_3_reg_1125;
reg   [7:0] add_ln55_3_reg_1125_pp0_iter1_reg;
wire   [7:0] grp_fu_897_p3;
reg   [7:0] add_ln59_reg_1140;
reg   [7:0] add_ln59_reg_1140_pp0_iter2_reg;
reg   [7:0] add_ln59_reg_1140_pp0_iter3_reg;
reg   [7:0] add_ln59_reg_1140_pp0_iter4_reg;
reg   [7:0] add_ln59_reg_1140_pp0_iter5_reg;
wire   [11:0] add_ln55_5_fu_776_p2;
reg   [11:0] add_ln55_5_reg_1145;
wire   [31:0] tmp_fu_803_p9;
reg   [31:0] tmp_reg_1170;
wire   [31:0] grp_fu_256_p2;
reg   [31:0] mul_reg_1180;
wire   [31:0] grp_fu_252_p2;
reg   [31:0] acc_1_reg_1190;
wire   [31:0] select_ln59_fu_885_p3;
reg   [31:0] select_ln59_reg_1197;
wire    ap_block_pp0_stage2_subdone;
wire   [63:0] zext_ln55_7_fu_782_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln55_4_fu_794_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln59_1_fu_892_p1;
reg   [31:0] acc_2_fu_122;
reg   [31:0] ap_sig_allocacmp_acc_2_load;
wire    ap_block_pp0_stage3;
wire    ap_loop_init;
reg   [1:0] kx_fu_126;
wire   [1:0] add_ln53_fu_621_p2;
reg   [1:0] ky_fu_130;
reg   [3:0] indvar_flatten6_fu_134;
wire   [3:0] select_ln51_1_fu_660_p3;
reg   [4:0] ic_fu_138;
reg   [8:0] indvar_flatten21_fu_142;
wire   [8:0] select_ln49_1_fu_673_p3;
reg   [4:0] ox_fu_146;
wire   [4:0] select_ln46_fu_513_p3;
reg   [12:0] indvar_flatten47_fu_150;
wire   [12:0] select_ln46_1_fu_477_p3;
reg   [4:0] oy_fu_154;
reg   [15:0] indvar_flatten83_fu_158;
wire   [15:0] add_ln44_1_fu_334_p2;
reg    in_buf_ce0_local;
reg    in_buf_1_ce0_local;
reg    in_buf_2_ce0_local;
reg    WEIGHTS2_ce0_local;
reg    conv_buf_we0_local;
reg    conv_buf_ce0_local;
reg    conv_buf_1_we0_local;
reg    conv_buf_1_ce0_local;
wire   [31:0] grp_fu_252_p0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln53_fu_375_p2;
wire   [0:0] xor_ln44_fu_369_p2;
wire   [0:0] icmp_ln49_fu_393_p2;
wire   [4:0] add_ln44_fu_349_p2;
wire   [0:0] exitcond_flatten23_not_fu_425_p2;
wire   [0:0] and_ln44_fu_381_p2;
wire   [0:0] not_exitcond_flatten23_mid282_fu_431_p2;
wire   [0:0] icmp_ln51_fu_387_p2;
wire   [0:0] and_ln44_1_fu_443_p2;
wire   [0:0] icmp_ln53_mid242_fu_437_p2;
wire   [0:0] not_exitcond_flatten8_mid246_fu_455_p2;
wire   [12:0] add_ln46_1_fu_471_p2;
wire   [4:0] ic_1_mid228_fu_506_p3;
wire   [0:0] empty_24_fu_524_p2;
wire   [0:0] empty_25_fu_528_p2;
wire   [4:0] add_ln49_fu_518_p2;
wire   [1:0] ky_mid213_fu_533_p3;
wire   [0:0] empty_26_fu_554_p2;
wire   [0:0] empty_27_fu_558_p2;
wire   [1:0] add_ln51_fu_548_p2;
wire   [4:0] zext_ln53_fu_585_p1;
wire   [4:0] mul_ln55_fu_599_p0;
wire   [6:0] mul_ln55_fu_599_p1;
wire   [10:0] mul_ln55_fu_599_p2;
wire   [2:0] grp_fu_615_p1;
wire   [3:0] add_ln51_1_fu_655_p2;
wire   [8:0] add_ln49_1_fu_668_p2;
wire   [3:0] p_shl_fu_716_p3;
wire   [3:0] zext_ln55_1_fu_713_p1;
wire   [4:0] zext_ln51_1_fu_729_p1;
wire   [3:0] sub_ln55_fu_723_p2;
wire   [3:0] zext_ln55_3_fu_737_p1;
wire   [3:0] add_ln55_2_fu_740_p2;
wire   [7:0] tmp_2_fu_746_p3;
wire   [7:0] zext_ln55_fu_710_p1;
wire   [8:0] grp_fu_905_p3;
wire   [11:0] tmp_1_fu_766_p3;
wire   [11:0] zext_ln55_6_fu_773_p1;
wire   [12:0] add_ln55_4_fu_788_p3;
wire   [1:0] grp_fu_615_p2;
wire   [31:0] tmp_fu_803_p7;
wire   [1:0] tmp_fu_803_p8;
wire   [31:0] select_ln44_1_fu_826_p3;
wire   [31:0] bitcast_ln59_fu_844_p1;
wire   [7:0] tmp_s_fu_847_p4;
wire   [22:0] trunc_ln59_fu_857_p1;
wire   [0:0] icmp_ln59_1_fu_867_p2;
wire   [0:0] icmp_ln59_fu_861_p2;
wire   [0:0] or_ln59_fu_873_p2;
wire   [0:0] and_ln59_fu_879_p2;
wire   [4:0] grp_fu_897_p0;
wire   [3:0] grp_fu_897_p1;
wire   [3:0] grp_fu_897_p2;
wire   [4:0] grp_fu_905_p0;
wire   [4:0] grp_fu_905_p1;
wire   [4:0] grp_fu_905_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage2;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to5;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [7:0] grp_fu_897_p00;
wire   [7:0] grp_fu_897_p20;
wire   [8:0] grp_fu_905_p00;
wire   [8:0] grp_fu_905_p20;
wire   [10:0] mul_ln55_fu_599_p00;
wire   [1:0] tmp_fu_803_p1;
wire   [1:0] tmp_fu_803_p3;
wire  signed [1:0] tmp_fu_803_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 acc_2_fu_122 = 32'd0;
#0 kx_fu_126 = 2'd0;
#0 ky_fu_130 = 2'd0;
#0 indvar_flatten6_fu_134 = 4'd0;
#0 ic_fu_138 = 5'd0;
#0 indvar_flatten21_fu_142 = 9'd0;
#0 ox_fu_146 = 5'd0;
#0 indvar_flatten47_fu_150 = 13'd0;
#0 oy_fu_154 = 5'd0;
#0 indvar_flatten83_fu_158 = 16'd0;
#0 ap_done_reg = 1'b0;
end

conv2_pool2_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_WEIGHTS2_ROM_AUTbkb #(
    .DataWidth( 32 ),
    .AddressRange( 4608 ),
    .AddressWidth( 13 ))
WEIGHTS2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(WEIGHTS2_address0),
    .ce0(WEIGHTS2_ce0_local),
    .q0(WEIGHTS2_q0)
);

conv2_pool2_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_252_p0),
    .din1(mul_reg_1180),
    .ce(1'b1),
    .dout(grp_fu_252_p2)
);

conv2_pool2_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_reg_1170),
    .din1(WEIGHTS2_q0),
    .ce(1'b1),
    .dout(grp_fu_256_p2)
);

conv2_pool2_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U11(
    .din0(mul_ln55_fu_599_p0),
    .din1(mul_ln55_fu_599_p1),
    .dout(mul_ln55_fu_599_p2)
);

conv2_pool2_urem_5ns_3ns_2_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_5ns_3ns_2_9_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln55_fu_589_p2),
    .din1(grp_fu_615_p1),
    .ce(1'b1),
    .dout(grp_fu_615_p2)
);

(* dissolve_hierarchy = "yes" *) conv2_pool2_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U13(
    .din0(in_buf_q0),
    .din1(in_buf_1_q0),
    .din2(in_buf_2_q0),
    .def(tmp_fu_803_p7),
    .sel(tmp_fu_803_p8),
    .dout(tmp_fu_803_p9)
);

conv2_pool2_mac_muladd_5ns_4ns_4ns_8_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
mac_muladd_5ns_4ns_4ns_8_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_897_p0),
    .din1(grp_fu_897_p1),
    .din2(grp_fu_897_p2),
    .ce(1'b1),
    .dout(grp_fu_897_p3)
);

conv2_pool2_mac_muladd_5ns_5ns_5ns_9_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 9 ))
mac_muladd_5ns_5ns_5ns_9_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_905_p0),
    .din1(grp_fu_905_p1),
    .din2(grp_fu_905_p2),
    .ce(1'b1),
    .dout(grp_fu_905_p3)
);

conv2_pool2_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_2_fu_122 <= acc;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        acc_2_fu_122 <= grp_fu_252_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage2))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage2))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ic_fu_138 <= 5'd0;
    end else if (((icmp_ln44_reg_1005 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ic_fu_138 <= select_ln49_fu_541_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten21_fu_142 <= 9'd0;
    end else if (((icmp_ln44_reg_1005 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten21_fu_142 <= select_ln49_1_fu_673_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten47_fu_150 <= 13'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln44_fu_328_p2 == 1'd0))) begin
        indvar_flatten47_fu_150 <= select_ln46_1_fu_477_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten6_fu_134 <= 4'd0;
    end else if (((icmp_ln44_reg_1005 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten6_fu_134 <= select_ln51_1_fu_660_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten83_fu_158 <= 16'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln44_fu_328_p2 == 1'd0))) begin
        indvar_flatten83_fu_158 <= add_ln44_1_fu_334_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kx_fu_126 <= 2'd0;
    end else if (((icmp_ln44_reg_1005 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        kx_fu_126 <= add_ln53_fu_621_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ky_fu_130 <= 2'd0;
    end else if (((icmp_ln44_reg_1005 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ky_fu_130 <= select_ln51_fu_570_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ox_fu_146 <= 5'd0;
    end else if (((icmp_ln44_reg_1005 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ox_fu_146 <= select_ln46_fu_513_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        oy_fu_154 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln44_fu_328_p2 == 1'd0))) begin
        oy_fu_154 <= select_ln44_2_fu_405_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        acc_1_reg_1190 <= grp_fu_252_p2;
        add_ln55_3_reg_1125 <= add_ln55_3_fu_754_p2;
        add_ln55_3_reg_1125_pp0_iter1_reg <= add_ln55_3_reg_1125;
        empty_28_reg_1120 <= empty_28_fu_732_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln46_reg_1037 <= add_ln46_fu_413_p2;
        add_ln55_5_reg_1145 <= add_ln55_5_fu_776_p2;
        and_ln44_2_reg_1025 <= and_ln44_2_fu_399_p2;
        and_ln44_2_reg_1025_pp0_iter1_reg <= and_ln44_2_reg_1025;
        and_ln44_2_reg_1025_pp0_iter2_reg <= and_ln44_2_reg_1025_pp0_iter1_reg;
        and_ln44_2_reg_1025_pp0_iter3_reg <= and_ln44_2_reg_1025_pp0_iter2_reg;
        empty_reg_1042 <= empty_fu_419_p2;
        exitcond_flatten8_mid246_reg_1049 <= exitcond_flatten8_mid246_fu_449_p2;
        icmp_ln44_reg_1005 <= icmp_ln44_fu_328_p2;
        icmp_ln44_reg_1005_pp0_iter1_reg <= icmp_ln44_reg_1005;
        icmp_ln44_reg_1005_pp0_iter2_reg <= icmp_ln44_reg_1005_pp0_iter1_reg;
        icmp_ln44_reg_1005_pp0_iter3_reg <= icmp_ln44_reg_1005_pp0_iter2_reg;
        icmp_ln44_reg_1005_pp0_iter4_reg <= icmp_ln44_reg_1005_pp0_iter3_reg;
        icmp_ln46_reg_1014 <= icmp_ln46_fu_355_p2;
        icmp_ln46_reg_1014_pp0_iter1_reg <= icmp_ln46_reg_1014;
        icmp_ln46_reg_1014_pp0_iter2_reg <= icmp_ln46_reg_1014_pp0_iter1_reg;
        icmp_ln46_reg_1014_pp0_iter3_reg <= icmp_ln46_reg_1014_pp0_iter2_reg;
        icmp_ln53_mid220_reg_1056 <= icmp_ln53_mid220_fu_461_p2;
        indvar_flatten21_load_reg_1000 <= indvar_flatten21_fu_142;
        indvar_flatten6_load_reg_995 <= indvar_flatten6_fu_134;
        kx_load_reg_1009 <= kx_fu_126;
        select_ln44_2_reg_1032 <= select_ln44_2_fu_405_p3;
        select_ln44_reg_1020 <= select_ln44_fu_361_p3;
        select_ln59_reg_1197 <= select_ln59_fu_885_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln59_reg_1140 <= grp_fu_897_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln59_reg_1140_pp0_iter2_reg <= add_ln59_reg_1140;
        add_ln59_reg_1140_pp0_iter3_reg <= add_ln59_reg_1140_pp0_iter2_reg;
        add_ln59_reg_1140_pp0_iter4_reg <= add_ln59_reg_1140_pp0_iter3_reg;
        add_ln59_reg_1140_pp0_iter5_reg <= add_ln59_reg_1140_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        icmp_ln49_1_reg_1111 <= icmp_ln49_1_fu_639_p2;
        icmp_ln49_1_reg_1111_pp0_iter1_reg <= icmp_ln49_1_reg_1111;
        icmp_ln49_1_reg_1111_pp0_iter2_reg <= icmp_ln49_1_reg_1111_pp0_iter1_reg;
        icmp_ln49_1_reg_1111_pp0_iter3_reg <= icmp_ln49_1_reg_1111_pp0_iter2_reg;
        icmp_ln49_1_reg_1111_pp0_iter4_reg <= icmp_ln49_1_reg_1111_pp0_iter3_reg;
        icmp_ln51_1_reg_1107 <= icmp_ln51_1_fu_633_p2;
        icmp_ln51_1_reg_1107_pp0_iter1_reg <= icmp_ln51_1_reg_1107;
        icmp_ln51_1_reg_1107_pp0_iter2_reg <= icmp_ln51_1_reg_1107_pp0_iter1_reg;
        icmp_ln51_1_reg_1107_pp0_iter3_reg <= icmp_ln51_1_reg_1107_pp0_iter2_reg;
        icmp_ln51_1_reg_1107_pp0_iter4_reg <= icmp_ln51_1_reg_1107_pp0_iter3_reg;
        icmp_ln53_1_reg_1103 <= icmp_ln53_1_fu_627_p2;
        icmp_ln53_1_reg_1103_pp0_iter1_reg <= icmp_ln53_1_reg_1103;
        icmp_ln53_1_reg_1103_pp0_iter2_reg <= icmp_ln53_1_reg_1103_pp0_iter1_reg;
        icmp_ln53_1_reg_1103_pp0_iter3_reg <= icmp_ln53_1_reg_1103_pp0_iter2_reg;
        icmp_ln53_1_reg_1103_pp0_iter4_reg <= icmp_ln53_1_reg_1103_pp0_iter3_reg;
        kx_mid2_reg_1072 <= kx_mid2_fu_563_p3;
        lshr_ln_reg_1115 <= {{select_ln46_fu_513_p3[4:1]}};
        mul_reg_1180 <= grp_fu_256_p2;
        select_ln49_reg_1067 <= select_ln49_fu_541_p3;
        select_ln51_reg_1077 <= select_ln51_fu_570_p3;
        tmp_3_reg_1098 <= {{mul_ln55_fu_599_p2[10:7]}};
        tmp_reg_1170 <= tmp_fu_803_p9;
        trunc_ln46_reg_1084 <= trunc_ln46_fu_577_p1;
        trunc_ln46_reg_1084_pp0_iter1_reg <= trunc_ln46_reg_1084;
        trunc_ln46_reg_1084_pp0_iter2_reg <= trunc_ln46_reg_1084_pp0_iter1_reg;
        trunc_ln46_reg_1084_pp0_iter3_reg <= trunc_ln46_reg_1084_pp0_iter2_reg;
        trunc_ln46_reg_1084_pp0_iter4_reg <= trunc_ln46_reg_1084_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        WEIGHTS2_ce0_local = 1'b1;
    end else begin
        WEIGHTS2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln44_reg_1005 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln44_reg_1005_pp0_iter4_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter4_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_acc_2_load = grp_fu_252_p2;
    end else begin
        ap_sig_allocacmp_acc_2_load = acc_2_fu_122;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        conv_buf_1_ce0_local = 1'b1;
    end else begin
        conv_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln49_1_reg_1111_pp0_iter4_reg == 1'd1) & (icmp_ln51_1_reg_1107_pp0_iter4_reg == 1'd1) & (icmp_ln53_1_reg_1103_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (trunc_ln46_reg_1084_pp0_iter4_reg == 1'd1))) begin
        conv_buf_1_we0_local = 1'b1;
    end else begin
        conv_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        conv_buf_ce0_local = 1'b1;
    end else begin
        conv_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln49_1_reg_1111_pp0_iter4_reg == 1'd1) & (icmp_ln51_1_reg_1107_pp0_iter4_reg == 1'd1) & (icmp_ln53_1_reg_1103_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (trunc_ln46_reg_1084_pp0_iter4_reg == 1'd0))) begin
        conv_buf_we0_local = 1'b1;
    end else begin
        conv_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_buf_1_ce0_local = 1'b1;
    end else begin
        in_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_buf_2_ce0_local = 1'b1;
    end else begin
        in_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_buf_ce0_local = 1'b1;
    end else begin
        in_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign WEIGHTS2_address0 = zext_ln55_4_fu_794_p1;

assign add_ln44_1_fu_334_p2 = (indvar_flatten83_fu_158 + 16'd1);

assign add_ln44_fu_349_p2 = (oy_fu_154 + 5'd1);

assign add_ln46_1_fu_471_p2 = (indvar_flatten47_fu_150 + 13'd1);

assign add_ln46_fu_413_p2 = (select_ln44_fu_361_p3 + 5'd1);

assign add_ln49_1_fu_668_p2 = (indvar_flatten21_load_reg_1000 + 9'd1);

assign add_ln49_fu_518_p2 = (ic_1_mid228_fu_506_p3 + 5'd1);

assign add_ln51_1_fu_655_p2 = (indvar_flatten6_load_reg_995 + 4'd1);

assign add_ln51_fu_548_p2 = (ky_mid213_fu_533_p3 + 2'd1);

assign add_ln53_fu_621_p2 = (kx_mid2_fu_563_p3 + 2'd1);

assign add_ln55_2_fu_740_p2 = (sub_ln55_fu_723_p2 + zext_ln55_3_fu_737_p1);

assign add_ln55_3_fu_754_p2 = (tmp_2_fu_746_p3 + zext_ln55_fu_710_p1);

assign add_ln55_4_fu_788_p3 = {{add_ln55_3_reg_1125_pp0_iter1_reg}, {zext_ln42}};

assign add_ln55_5_fu_776_p2 = (tmp_1_fu_766_p3 + zext_ln55_6_fu_773_p1);

assign add_ln55_fu_589_p2 = (zext_ln53_fu_585_p1 + select_ln46_fu_513_p3);

assign and_ln44_1_fu_443_p2 = (xor_ln44_fu_369_p2 & icmp_ln51_fu_387_p2);

assign and_ln44_2_fu_399_p2 = (xor_ln44_fu_369_p2 & icmp_ln49_fu_393_p2);

assign and_ln44_fu_381_p2 = (xor_ln44_fu_369_p2 & icmp_ln53_fu_375_p2);

assign and_ln59_fu_879_p2 = (or_ln59_fu_873_p2 & grp_fu_322_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign bitcast_ln59_fu_844_p1 = acc_1_reg_1190;

assign conv_buf_1_address0 = zext_ln59_1_fu_892_p1;

assign conv_buf_1_ce0 = conv_buf_1_ce0_local;

assign conv_buf_1_d0 = select_ln59_reg_1197;

assign conv_buf_1_we0 = conv_buf_1_we0_local;

assign conv_buf_address0 = zext_ln59_1_fu_892_p1;

assign conv_buf_ce0 = conv_buf_ce0_local;

assign conv_buf_d0 = select_ln59_reg_1197;

assign conv_buf_we0 = conv_buf_we0_local;

assign empty_24_fu_524_p2 = (exitcond_flatten8_mid246_reg_1049 | and_ln44_2_reg_1025);

assign empty_25_fu_528_p2 = (icmp_ln46_reg_1014 | empty_24_fu_524_p2);

assign empty_26_fu_554_p2 = (exitcond_flatten8_mid246_reg_1049 | empty_reg_1042);

assign empty_27_fu_558_p2 = (icmp_ln53_mid220_reg_1056 | empty_26_fu_554_p2);

assign empty_28_fu_732_p2 = (zext_ln51_1_fu_729_p1 + select_ln44_2_reg_1032);

assign empty_fu_419_p2 = (icmp_ln46_fu_355_p2 | and_ln44_2_fu_399_p2);

assign exitcond_flatten23_not_fu_425_p2 = (icmp_ln49_fu_393_p2 ^ 1'd1);

assign exitcond_flatten8_mid246_fu_449_p2 = (not_exitcond_flatten23_mid282_fu_431_p2 & and_ln44_1_fu_443_p2);

assign grp_fu_252_p0 = ((and_ln44_2_reg_1025_pp0_iter3_reg[0:0] == 1'b1) ? acc : select_ln44_1_fu_826_p3);

assign grp_fu_322_p_ce = 1'b1;

assign grp_fu_322_p_din0 = acc_1_reg_1190;

assign grp_fu_322_p_din1 = 32'd0;

assign grp_fu_322_p_opcode = 5'd2;

assign grp_fu_615_p1 = 5'd3;

assign grp_fu_897_p0 = grp_fu_897_p00;

assign grp_fu_897_p00 = select_ln44_2_fu_405_p3;

assign grp_fu_897_p1 = 8'd11;

assign grp_fu_897_p2 = grp_fu_897_p20;

assign grp_fu_897_p20 = lshr_ln_reg_1115;

assign grp_fu_905_p0 = grp_fu_905_p00;

assign grp_fu_905_p00 = select_ln49_fu_541_p3;

assign grp_fu_905_p1 = 9'd23;

assign grp_fu_905_p2 = grp_fu_905_p20;

assign grp_fu_905_p20 = empty_28_reg_1120;

assign ic_1_mid228_fu_506_p3 = ((empty_reg_1042[0:0] == 1'b1) ? 5'd0 : ic_fu_138);

assign icmp_ln44_fu_328_p2 = ((indvar_flatten83_fu_158 == 16'd63504) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_355_p2 = ((indvar_flatten47_fu_150 == 13'd3024) ? 1'b1 : 1'b0);

assign icmp_ln49_1_fu_639_p2 = ((select_ln49_fu_541_p3 == 5'd15) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_393_p2 = ((indvar_flatten21_fu_142 == 9'd144) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_633_p2 = ((select_ln51_fu_570_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_387_p2 = ((indvar_flatten6_fu_134 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln53_1_fu_627_p2 = ((add_ln53_fu_621_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_375_p2 = ((kx_fu_126 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_mid220_fu_461_p2 = (not_exitcond_flatten8_mid246_fu_455_p2 & icmp_ln53_mid242_fu_437_p2);

assign icmp_ln53_mid242_fu_437_p2 = (not_exitcond_flatten23_mid282_fu_431_p2 & and_ln44_fu_381_p2);

assign icmp_ln59_1_fu_867_p2 = ((trunc_ln59_fu_857_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_861_p2 = ((tmp_s_fu_847_p4 != 8'd255) ? 1'b1 : 1'b0);

assign in_buf_1_address0 = zext_ln55_7_fu_782_p1;

assign in_buf_1_ce0 = in_buf_1_ce0_local;

assign in_buf_2_address0 = zext_ln55_7_fu_782_p1;

assign in_buf_2_ce0 = in_buf_2_ce0_local;

assign in_buf_address0 = zext_ln55_7_fu_782_p1;

assign in_buf_ce0 = in_buf_ce0_local;

assign kx_mid2_fu_563_p3 = ((empty_27_fu_558_p2[0:0] == 1'b1) ? 2'd0 : kx_load_reg_1009);

assign ky_mid213_fu_533_p3 = ((empty_25_fu_528_p2[0:0] == 1'b1) ? 2'd0 : ky_fu_130);

assign mul_ln55_fu_599_p0 = mul_ln55_fu_599_p00;

assign mul_ln55_fu_599_p00 = add_ln55_fu_589_p2;

assign mul_ln55_fu_599_p1 = 11'd43;

assign not_exitcond_flatten23_mid282_fu_431_p2 = (icmp_ln46_fu_355_p2 | exitcond_flatten23_not_fu_425_p2);

assign not_exitcond_flatten8_mid246_fu_455_p2 = (exitcond_flatten8_mid246_fu_449_p2 ^ 1'd1);

assign or_ln59_fu_873_p2 = (icmp_ln59_fu_861_p2 | icmp_ln59_1_fu_867_p2);

assign p_shl_fu_716_p3 = {{select_ln51_reg_1077}, {2'd0}};

assign select_ln44_1_fu_826_p3 = ((icmp_ln46_reg_1014_pp0_iter3_reg[0:0] == 1'b1) ? acc : ap_sig_allocacmp_acc_2_load);

assign select_ln44_2_fu_405_p3 = ((icmp_ln46_fu_355_p2[0:0] == 1'b1) ? add_ln44_fu_349_p2 : oy_fu_154);

assign select_ln44_fu_361_p3 = ((icmp_ln46_fu_355_p2[0:0] == 1'b1) ? 5'd0 : ox_fu_146);

assign select_ln46_1_fu_477_p3 = ((icmp_ln46_fu_355_p2[0:0] == 1'b1) ? 13'd1 : add_ln46_1_fu_471_p2);

assign select_ln46_fu_513_p3 = ((and_ln44_2_reg_1025[0:0] == 1'b1) ? add_ln46_reg_1037 : select_ln44_reg_1020);

assign select_ln49_1_fu_673_p3 = ((empty_reg_1042[0:0] == 1'b1) ? 9'd1 : add_ln49_1_fu_668_p2);

assign select_ln49_fu_541_p3 = ((exitcond_flatten8_mid246_reg_1049[0:0] == 1'b1) ? add_ln49_fu_518_p2 : ic_1_mid228_fu_506_p3);

assign select_ln51_1_fu_660_p3 = ((empty_25_fu_528_p2[0:0] == 1'b1) ? 4'd1 : add_ln51_1_fu_655_p2);

assign select_ln51_fu_570_p3 = ((icmp_ln53_mid220_reg_1056[0:0] == 1'b1) ? add_ln51_fu_548_p2 : ky_mid213_fu_533_p3);

assign select_ln59_fu_885_p3 = ((and_ln59_fu_879_p2[0:0] == 1'b1) ? acc_1_reg_1190 : 32'd0);

assign sub_ln55_fu_723_p2 = (p_shl_fu_716_p3 - zext_ln55_1_fu_713_p1);

assign tmp_1_fu_766_p3 = {{grp_fu_905_p3}, {3'd0}};

assign tmp_2_fu_746_p3 = {{add_ln55_2_fu_740_p2}, {4'd0}};

assign tmp_fu_803_p7 = 'bx;

assign tmp_fu_803_p8 = grp_fu_615_p2[1:0];

assign tmp_s_fu_847_p4 = {{bitcast_ln59_fu_844_p1[30:23]}};

assign trunc_ln46_fu_577_p1 = select_ln46_fu_513_p3[0:0];

assign trunc_ln59_fu_857_p1 = bitcast_ln59_fu_844_p1[22:0];

assign xor_ln44_fu_369_p2 = (icmp_ln46_fu_355_p2 ^ 1'd1);

assign zext_ln51_1_fu_729_p1 = select_ln51_reg_1077;

assign zext_ln53_fu_585_p1 = kx_mid2_fu_563_p3;

assign zext_ln55_1_fu_713_p1 = select_ln51_reg_1077;

assign zext_ln55_3_fu_737_p1 = kx_mid2_reg_1072;

assign zext_ln55_4_fu_794_p1 = add_ln55_4_fu_788_p3;

assign zext_ln55_6_fu_773_p1 = tmp_3_reg_1098;

assign zext_ln55_7_fu_782_p1 = add_ln55_5_reg_1145;

assign zext_ln55_fu_710_p1 = select_ln49_reg_1067;

assign zext_ln59_1_fu_892_p1 = add_ln59_reg_1140_pp0_iter5_reg;

endmodule //conv2_pool2_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX
