

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.BIASES2_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.in_buf_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.in_buf_1_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.in_buf_2_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv_buf_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv_buf_1_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_LOAD_IC_LOAD_IY_fu_168"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_LOAD_IC_LOAD_IY_fu_168.mac_muladd_5ns_5ns_5ns_9_4_1_U1"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_LOAD_IC_LOAD_IY_fu_168.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_fu_178"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_fu_178.WEIGHTS2_U"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_fu_178.fadd_32ns_32ns_32_5_full_dsp_1_U8"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_fu_178.fmul_32ns_32ns_32_4_max_dsp_1_U9"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_fu_178.mul_5ns_7ns_11_1_1_U11"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_fu_178.urem_5ns_3ns_2_9_1_U12"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_fu_178.sparsemux_7_2_32_1_1_U13"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_fu_178.mac_muladd_5ns_4ns_4ns_8_4_1_U14"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_fu_178.mac_muladd_5ns_5ns_5ns_9_4_1_U15"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_CONV_OY_CONV_OX_CONV_IC_CONV_KY_CONV_KX_fu_178.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_POOL_PY_POOL_PX_fu_192"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_POOL_PY_POOL_PX_fu_192.fcmp_32ns_32ns_1_2_no_dsp_1_U31"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_POOL_PY_POOL_PX_fu_192.fcmp_32ns_32ns_1_2_no_dsp_1_U32"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_POOL_PY_POOL_PX_fu_192.mac_muladd_5ns_4ns_4ns_8_4_1_U33"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_POOL_PY_POOL_PX_fu_192.mac_muladd_5ns_4ns_4ns_8_4_1_U34"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv2_pool2_Pipeline_POOL_PY_POOL_PX_fu_192.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.AXI_IN_m_axi_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.AXI_OUT_m_axi_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fcmp_32ns_32ns_1_2_no_dsp_1_U39"}]}
set DependenceCheckSize 0
